### ISSUE TITLE
Re-render chart

### ISSUE THREAD

**Issue by peter-stuart-turner** [FERNman/angular-google-charts#1]
Is there a way to re-render a chart without using the chart wrapper (because then I may as well not use this library?)

For instance, it renders fine the first time within a tab, but when I switch tabs and go back, the angular component is destroyed - when I re click the tab, it is initialized again but this time the chart does not load?

**Comment by leticiacabrero** [comment]
Hi,

Same problem here.

In my case, i am trying to open two different boostrap modal, with a chart in each one. The first opened modal renders the chart correctly, but when the second modal is opened, or the first one is reopened, the chart doesn't load.

Is there a solution for this issue?

Thanks.

**Comment by FERNman** [comment]
Hi,
You two were right - this was a bug. Luckily a small one, so I was able to fix it quickly. I hope you should be able to use it now!

**Comment by peter-stuart-turner** [comment]
Jeepers that was quick, thanks man - keep it up, great package and only alternative to the older one (ng2-google-charts). I ended up making a custom reusable component for the one chart, so happy to switch back to this now.

**Comment by leticiacabrero** [comment]
Oh, that was the thing, sorry for my mistake! Thank you so much for your quickly response @FERNman, and your helpful support!
