### ISSUE TITLE
When rendering an OrgChart, I get an error in the console:

### ISSUE THREAD

**Issue by peter-stuart-turner** [FERNman/angular-google-charts#10]
I get the following error: core.js:1673 ERROR TypeError: Cannot read property '__eventTarget' of null

I don;'t get these with charts from the core package, the OrgChart does however render correctly.

**Comment by FERNman** [comment]
I just created an OrgChart to try, and it worked like a charm. Are you sure that you have created it correctly?

**Comment by peter-stuart-turner** [comment]
Pretty sure yeah?  

> <google-chart #chart (ready)="chart_ready()" (select)="org_chart_select($event)" type="OrgChart" [data]="chartData.data"
>                 [columnNames]="chartData.columnNames" [options]="chartData.options"></google-chart>
>     </div>

> public generate_chart_data() {
>     const data: ChartData = {
>       data: [
>         ['ROA, ROIC, ROE', '', 'Return on Assets'],
>         ['TA', 'ROA, ROIC, ROE', 'Total Assets'],
>         ['NOPAT', 'ROA, ROIC, ROE', 'Net Operating Profit After Tax'],
>         ['IC', 'ROA, ROIC, ROE', 'Invested Capital'],
>         ['TE', 'ROA, ROIC, ROE', 'Total Equity'],
>         ['Exp', 'NOPAT', 'Expenses'],
>         ['Tax', 'NOPAT', 'Tax Rate'],
>         ['OR', 'NOPAT', 'Operating Revenue'],
>         ['TA', 'ROA', 'Total Assets'],
>         ['Utl', 'Exp', 'Utilities'],
>         ['Opex', 'Exp', 'Operational Expenditure'],
>         ['Oexp', 'Exp', 'Other Expenses'],
>         ['UntS', 'OR', 'Units Sold'],
>         ['SP', 'OR', 'Sales Price'],
>         ['Lbr', 'Opex', 'Labour Costs'],
>         ['Mnt', 'Opex', 'Maintenance Costs'],
>         ['Stock', 'UntS', 'Stock / Units Not Sold'],
>         ['UntPr', 'UntS', 'Units Produced'],
>         ['PCap', 'UntPr', 'Plant Capacity'],
>         ['TCU', 'UntPr', 'Total Capacity Utilization'],
>         ['OEE', 'TCU', 'Overall Equipment Effectiveness'],
>         ['Utz', 'TCU', 'Utilization'],
>         ['A', 'OEE', 'Availability'],
>         ['P', 'OEE', 'Performance'],
>         ['Q', 'OEE', 'Quality'],
>       ],
>       columnNames: ['Name', 'Manager', 'Tooltip'],
>       options: {
>         'title': 'Organizational Chart View',
>         allowHtml: true,
>         allowCollapse: true,
>         nodeClass: 'defaultNode',
>         selectedNodeClass: 'selectedNode',
>       }
>     }
>     return data;
>   }

**Comment by FERNman** [comment]
Strange. Your code works for me...

**Comment by peter-stuart-turner** [comment]
Ok - must be something my side then, will close?
