### ISSUE TITLE
Error when changing data to be null

### ISSUE THREAD

**Issue by sysmat** [FERNman/angular-google-charts#104]
When changing data and when become empty it still showing previous data and showing error.

ver: 0.1.6

Regards

**Comment by FERNman** [comment]
Thanks for the issue. I will change the behaviour to hide the chart if the provided data is `null` or `undefined`.

**Comment by FERNman** [comment]
After thinking about this for a bit now, I will leave the behaviour of the google chart component as it is in the official google library. The following error will be shown to the user if no data is provided:

![chart_error](https://user-images.githubusercontent.com/12270008/79136708-bce48e00-7db1-11ea-9437-41895efc802a.png)

If you want to hide the chart if there is no data, use `*ngIf`.
