### ISSUE TITLE
Using roles in a GeoChart

### ISSUE THREAD

**Issue by UnknownInnocent** [FERNman/angular-google-charts#105]
I have a basic html-file that creates a GeoChart using google charts which is attached to the issue:
[test.zip](https://github.com/FERNman/angular-google-charts/files/3864045/test.zip)

As you see above, this GeoChart has 3 columns. Now what I want to do is to add this chart to my Angular Application.
HTML:

```html
<google-chart #chart
   [title]="title"
   [type]="type"
   [data]="data"
   [columnNames]="columnNames"
   [options]="options"
   style="width: 100%; height: 100%;">
</google-chart>
```

TS:
```typescript
type="GeoChart";
  columnNames = [
    [{type: 'string', role: 'data'}],
    [{type: 'number', role: 'data'}]
  ]
  data = [
    ['India', 2],
    ['Australia', 4],
    ['Germany', 1],
    ['United States', 2],
    ['Brazil', 2],
    ['Canada', 3],
    ['France', 2],
    ['Russia', 2]      
  ];

  options = {
    backgroundColor: '#17263c',
    datalessRegionColor: '#242f3e',
    legend: 'none',
    tooltip: {
      isHtml: true,
      textStyle: {
        color: 'black'
      }
    },
    colors: ['#46127A', '#1102BB', '#1633C4', '#3185CE']
  };
```

This chart so far only has 2 columns. If I now want to add a third one as following:

```typescript
 columnNames = [
    [{type: 'string', role: 'data'}],
    [{type: 'number', role: 'data'}],
    [{type: 'string', role: 'tooltip'}]
  ]
  data = [
    ['India', 2, 'test'],
    ['Australia', 4, 'test'],
    ['Germany', 1, 'test'],
    ['United States', 2, 'test'],
    ['Brazil', 2, 'test'],
    ['Canada', 3, 'test'],
    ['France', 2, 'test'],
    ['Russia', 2, 'test']      
  ];
```

Then I always get following error:

`Incompatible data table: Error: Table contains more columns than expected (Expecting 2 columns)`

This means that GeoCharts accept only 2 columns BUT since there is a way to use three columns in the basic html file (not using Angular) i am sure there has to be a way to do this using angular too but I don't know how.

I also tried this:
```html
<google-chart #chart
   [title]="title"
   [type]="type"
   [data]="data"
   [columnNames]="columnNames"
   [options]="options"
   [firstRowIsData]="false"
   style="width: 100%; height: 100%;">
</google-chart>
```

```typescript
type="GeoChart";
  data = [
    ['Country', 'amount', {type: 'string', role: 'tooltip'}],
    ['Country', 0, ''],
    ['India', 2, 'visited'],
    ['Australia', 4, 'want to visit'],
    ['Germany', 1, 'homecountry'],
    ['United States', 2,  'visited'],
    ['Brazil', 2, 'visited'],
    ['Canada', 3, 'favorite destination'],
    ['France', 2, 'visited'],
    ['Russia', 2, 'visited']      
  ];
  options = {
    backgroundColor: '#17263c',
    datalessRegionColor: '#242f3e',
    legend: 'none',
    tooltip: {
      isHtml: true,
      textStyle: {
        color: 'black'
      }
    },
    colors: ['#46127A', '#1102BB', '#1633C4', '#3185CE']
  };
```

but this gave me the following error:

`core.js:9110 ERROR Error: Unknown type of value in 0,2
    at gvjs_Rba (jsapi_compiled_default_module.js:130)
    at Object.gvjs_Eo [as arrayToDataTable] (jsapi_compiled_default_module.js:130)
    at GoogleChartComponent.updateChart (angular-google-charts.js:266)
    at SafeSubscriber._next (angular-google-charts.js:473)
    at SafeSubscriber.__tryOrUnsub (Subscriber.js:185)
    at SafeSubscriber.next (Subscriber.js:124)
    at Subscriber._next (Subscriber.js:72)
    at Subscriber.next (Subscriber.js:49)
    at angular-google-charts.js:89
    at ZoneDelegate.invoke (zone-evergreen.js:359)`

**Comment by FERNman** [comment]
Hi @UnknownInnocent, I'm very sorry for the late reply. I hope you have figured it out by yourselves in the meantime. I'll just add the correct solution here for anybody who may stumble upon this in the future.

The reason why this was not working is that your `columnNames` are of type `Array<Array<Object>>`, but in reality they should be of type `Array<Object | string>`. If I'm being honest, I don't know why the first example using only data rows even worked.

So, in order to get this to work, the column names should look similar to the following:

```typescript
columnNames: [
  { type: 'string', role: 'data' },
  { type: 'number', role: 'data' },
  { type: 'string', role: 'tooltip' }
],
```

I hope this helps!
