### ISSUE TITLE
Disable select event until chart is ready

### ISSUE THREAD

**Issue by UnknownInnocent** [FERNman/angular-google-charts#106]
Hello, I just ran into the problem that I always get this error when clicking on a country in geo chart before the chart is ready. After the chart is fully loaded, I don't get any errors:
```
core.js:9110 ERROR TypeError: Cannot read property 'getSelection' of null
    at angular-google-charts.js:360
    at gvjs_tn.<anonymous> (jsapi_compiled_default_module.js:186)
    at gvjs_un (jsapi_compiled_default_module.js:64)
    at gvjs_tn.gvjs_.dispatchEvent (jsapi_compiled_default_module.js:62)
    at gvjs_T (jsapi_compiled_default_module.js:185)
    at jsapi_compiled_default_module.js:259
    at gvjs_tn.<anonymous> (jsapi_compiled_default_module.js:186)
    at gvjs_un (jsapi_compiled_default_module.js:64)
    at gvjs_tn.gvjs_.dispatchEvent (jsapi_compiled_default_module.js:62)
    at gvjs_T (jsapi_compiled_default_module.js:185)
```

For this reason, I would like to disable the `(select)` event until the chart is ready, but I don't know how to do this.

**Comment by FERNman** [comment]
So this happens when you click on the chart before it is fully loaded?

**Comment by UnknownInnocent** [comment]
> So this happens when you click on the chart before it is fully loaded?

Yes exactly. And I would be really happy if there was a way to reduce the loading time additionally

**Comment by FERNman** [comment]
I don't think there's a way to reduce the loading time as it fully depends on the google package. I will, however, look into the error you provided and see if I can fix it.

**Comment by jppribeiro** [comment]
Do you need the chart to be displayed while its data is not ready? You could avoid this by having a *ngIf  on the div containing the chart that only turns true after the data has been received.

**Comment by FERNman** [comment]
I don't really know how to reproduce this. If anyone can provide me with a valid reproduction, I'll be happy to look into it (and I'd be happy to accept any PRs on this as well). For now, I'll close this.
