### ISSUE TITLE
ERROR TypeError: Object(...) is not a function     at ScriptLoaderService.get [as onReady] (angular-google-charts.js:34)

### ISSUE THREAD

**Issue by jettcalleja** [FERNman/angular-google-charts#108]
I get an error when going back to the page where the chart is loaded:
```js 
ERROR TypeError: Object(...) is not a function
    at ScriptLoaderService.get [as onReady] (angular-google-charts.js:34)
```

Upon checking the source code for the cause of error
```js
export class ScriptLoaderService {
  // ...

  public get onReady(): Observable<boolean> {
    if (this.doneLoading) {
      return of(true); // <--- this is where error occurs
    }

    return this.onLoadSubject.asObservable();
  }
```

I think this is related to the version of rxjs on how the of should be imported? https://github.com/reactivex/rxjs/issues/4070

**Comment by FERNman** [comment]
Very interesting, I don't get this error. Which version of rxjs are you using?
The import of the `of` method is done as it should be:

```typescript
import { of } from 'rxjs';
```

**Comment by jettcalleja** [comment]
So the cause was I'm using Angular 5, which was using the old version of rxjs. 

Fix: upgrade to angular 6
https://medium.com/@filipjerga/angular-5-to-angular-6-migration-guide-7ba4d2544411
