### ISSUE TITLE
Redraw chart when staying in the same route but with different route-params

### ISSUE THREAD

**Issue by UnknownInnocent** [FERNman/angular-google-charts#109]
Hello, I have the problem that I have a GeoMap on a userprofil. In ngOnInit, I get the countries that should be marked from a database. This actually works as long as I just do it one time BUT if I change the user-id (user-profil/:id) ngOnInit is called but anyway the same countries are painted on the map as before. I need something that makes my map-component reload AND redraw every time the route-params change. I tried this:
`constructor(private router: Router) {
    // override the route reuse strategy
    this.router.routeReuseStrategy.shouldReuseRoute = function() {
        return false;
    };
}`
but it didn't work. How would I do this then?

**Comment by FERNman** [comment]
Did you try to subscribe to the `ActivatedRoute` params?

Example:

```typescript
constructor(private route: ActivatedRoute) {}

public ngOnInit() {
  this.route.paramMap.subscribe(params => { 
    // Do something with params
  });
}
```

**Comment by UnknownInnocent** [comment]
My GeoChart is in the Map-Component and this is in the User-Component. Do I have to put it in the MAp or in the User Component?

**Comment by FERNman** [comment]
I would put it in the component where you initialize the data for your chart.

**Comment by UnknownInnocent** [comment]
Okay, I tried that but I still have the same problem: Lets say I have 2 users.
user 1 marked canada and France
user 2 marked russia and brazil

I am on the profil of user 1 and refresh and I get canada and france marked
but if I now gi to the secons user canada, france, russia and brazil are marked and only if i press f5 to reload I get the right result.

![image](https://user-images.githubusercontent.com/52075921/69498013-87630500-0ee3-11ea-99fb-6ef8b0724da3.png)

this._countryService.getCountrys(); are all countries having "0" in the second column and i have to mention that if i log "res" I really get the data that is saved for this user but however it isn't assigned to "data"

**Comment by FERNman** [comment]
>it isn't assigned to "data"

What do you mean by this? It is obviously assigned correctly, as one can see in your screenshot. Do you have change detection set to `Default`?

**Comment by UnknownInnocent** [comment]
> What do you mean by this? 
I mean that "data" is not correct afterwards, as I mentioned, all countries but not only the ones of this user are marked

> Do you have change detection set to Default?
What does this mean?

**Comment by FERNman** [comment]
Can you show me how the initial data is bound to the component?

**Comment by UnknownInnocent** [comment]
I am not quit sure what you mean so here is the data from the service:
![image](https://user-images.githubusercontent.com/52075921/69558477-98297e80-0fa8-11ea-8e83-b2bc84c06dcd.png)
![image](https://user-images.githubusercontent.com/52075921/69558521-ab3c4e80-0fa8-11ea-83df-c14e0fd44fbd.png)
![image](https://user-images.githubusercontent.com/52075921/69558556-b5f6e380-0fa8-11ea-9b5c-89a7eed6aecc.png)
![image](https://user-images.githubusercontent.com/52075921/69558590-c0b17880-0fa8-11ea-8e2a-9f528003ec10.png)
![image](https://user-images.githubusercontent.com/52075921/69558610-cad37700-0fa8-11ea-92a9-535676928fe4.png)

And here is my chart:
![image](https://user-images.githubusercontent.com/52075921/69558677-ec346300-0fa8-11ea-95dd-3264e47fe13f.png)


You already have the ngOnInit above
