### ISSUE TITLE
PieChart : legend:{position:'none'} not working.

### ISSUE THREAD

**Issue by raj2823** [FERNman/angular-google-charts#110]
[ts]
Argument of type '{ title: string; backgroundColor: string; colors: string[]; fontSize: number; legend: { position:...' is not assignable to parameter of type 'PieChartOptions'.
  Types of property 'legend' are incompatible.
    Type '{ position: string; }' is not assignable to type '"none" | ChartLegend'.
      Type '{ position: string; }' is not assignable to type 'ChartLegend'.
        Types of property 'position' are incompatible.
          Type 'string' is not assignable to type 'ChartLegendPosition'.

**Comment by FERNman** [comment]
Can you provide me with some source code?

**Comment by Ovsk777** [comment]
Hi, 
I am facing this same issue. The default legend cannot be hidden. I have tried both 
1- legend: 'none'
2- legend: {position: 'none'}
Nothing seems to work. Please let me know if there is any feasible alternative for hiding legends in Google Pie chart in Angular 2+.
let fitGapData = [
      {
        "team": "OTC",
        "fit count": 0,
        "gap count": 1
      },
      {
        "team": "PTP",
        "fit count": 1,
        "gap count": 11
      }
    ] 
let reqFitGap = new google.visualization.DataTable();
    console.log('google',google.visualization)
    reqFitGap.addColumn('string', 'Count type');
    reqFitGap.addColumn('number', 'count');

    reqFitGap.addRows([
      ['Fit', fitGapData[1]['fit count']],
      ['Gap', fitGapData[1]['gap count']]
    ]);

    let fitGapOptions = {
      colors: ['#2D7CD1', '#EF9101'],
      title: 'FIT/GAP CHART-'+fitGapData[1].team,
      legend: 'none',
      height: 400,
      width: 550
    };

    let reqFitGapChart = new google.visualization.PieChart(document.getElementById('chart_requirementByFitGap'));
    reqFitGapChart.draw(reqFitGap, fitGapOptions);

**Comment by kussmaul** [comment]
@Ovsk777: `legend: 'none'` works for me:
https://stackblitz.com/edit/angular-ivy-ur6j7n
