### ISSUE TITLE
Unable to change pieChart Value format

### ISSUE THREAD

**Issue by amit509** [FERNman/angular-google-charts#113]
Hey,

I am unable to change format of value in pieChart as I have change in bar chart using annotations. See in below picture to understand clearly.
Example: In Bar I am able to show as 28.8K, 9.4K instead of 28800, 94000. But in Pie I am unable to show 105.0K instead of 105000.

![compare](https://user-images.githubusercontent.com/25607741/71572035-4f169e00-2b03-11ea-8167-5e1caffb31c1.png)

Please can anyone help me out on this?

**Comment by FERNman** [comment]
Hi  @amit509 ,

I hope you have already figured it out by yourself. If not, feel free to add a deeper explanation and at best even a simple reproduction repository.

For now, I'll close this issue.
