### ISSUE TITLE
Role annotation issue in GroupedColumnChart

### ISSUE THREAD

**Issue by amit509** [FERNman/angular-google-charts#114]
Hi All,

I am unable to show annotations for each column bar. All annotations are display at last column.
Please see below image 

![annotations](https://user-images.githubusercontent.com/25607741/71655697-027acf00-2d5e-11ea-9c8b-54f1848a8f1d.png)

**Comment by amit509** [comment]
Any Idea how to solve this?

**Comment by FERNman** [comment]
Hi @amit509 , could you provide me with some code to reproduce the issue?

**Comment by amit509** [comment]
Hi FERNman,
https://stackblitz.com/edit/angular-2nyuyx?embed=1&file=src/app/app.component.html
You can check the above url. Reproduced issue.

**Comment by FERNman** [comment]
Ok, so I hope that you already figured it out. I'll explain what's going on nevertheless just in case somebody else stumbles upon this.

If you don't want the roles to be appended to the `columns` in the chart, you must provide an index for every role. The role will then be inserted *after* the column with the index.

In your example, this would be `{"type":"string","role":"annotation", index: 1}` for the annotation for the first column, `{"type":"string","role":"annotation", index: 2}` for the second column and so on.

Additionally, you need to structure your data to follow the same pattern as your roles and columns, so you need to add the label at the same position in your data as the role.
As an example, this is what the first row in the given dataset should look like:

```typescript
["2",19246,"19.25k",13158,"13.16k",16464,"16.46k",15452,"15.45k",19266,"19.27k",17766,"17.77k",13590,"13.59k",20872,"20.87k"]
```

I hope this helps!
