### ISSUE TITLE
BUG rendering dynamic legend in columnsName 

### ISSUE THREAD

**Issue by Leonardo-demeloweb** [FERNman/angular-google-charts#116]
I am doing everything right according to me. The output printed in console is ok but the result  displayed in dynamic chart data is not correct.

`this.nomeInstrumento = nomeInstrumento;
            const nomeColuna = ["DATE"].concat(nomeInstrumento);
            this.columnNames = nomeColuna;
            console.log(this.columnNames);
`

Only the last  array of strings to compose columns name is being reflected:

<img width="422" alt="Captura de Tela 2020-02-11 às 23 07 01" src="https://user-images.githubusercontent.com/14796489/74296813-b1c6a080-4d23-11ea-9c50-d7a95ce05982.png">

Here is the output logged in console:
<img width="414" alt="Captura de Tela 2020-02-11 às 23 07 36" src="https://user-images.githubusercontent.com/14796489/74296831-bdb26280-4d23-11ea-8f72-ba30f3410fce.png">

The final result of the plotted data, with the repetition of the columns name.
<img width="1654" alt="Captura de Tela 2020-02-11 às 23 07 53" src="https://user-images.githubusercontent.com/14796489/74296843-c4d97080-4d23-11ea-8c45-2992caafc477.png">

**Comment by Leonardo-demeloweb** [comment]
@FERNman if you may help?

**Comment by FERNman** [comment]
Could you maybe me with some more source code, like the data you are passing into the chart?

**Comment by Leonardo-demeloweb** [comment]
@FERNman I tried by this way and return me this error: "Data column(s) for axis #0 cannot be of type string"

` .        const i = ["date"].concat(nomeInstrumento);
            console.log((this.data = [i].concat(vetores)));`

<img width="1680" alt="Captura de Tela 2020-03-03 às 16 51 24" src="https://user-images.githubusercontent.com/14796489/75817631-3aaa8800-5d76-11ea-9ef5-d656b462b152.png">

What wen can do to achieve the right result on the googgle charts?

**Comment by Leonardo-demeloweb** [comment]
@FERNman  or when I try this way, I can not achieve the current chart for each individual instrumentation:

`console.log((this.columnNames = ["date"].concat(nomeInstrumento)));
  console.log((this.data = vetores));
`

<img width="776" alt="Captura de Tela 2020-03-03 às 17 51 11" src="https://user-images.githubusercontent.com/14796489/75818701-1bacf580-5d78-11ea-9afd-0b96f76a4218.png">
<img width="880" alt="Captura de Tela 2020-03-03 às 17 51 18" src="https://user-images.githubusercontent.com/14796489/75818704-2071a980-5d78-11ea-8dbe-36c8857bf4ab.png">

You may see "INA-1, INA-2" for every chart plotted. What can I do to solve it? seems a bug with the library.

**Comment by Leonardo-demeloweb** [comment]
@FERNman  when I try with the examples provided in the tutorial, just show the last item of the array:

<img width="836" alt="Captura de Tela 2020-03-03 às 18 02 04" src="https://user-images.githubusercontent.com/14796489/75819371-52cfd680-5d79-11ea-9e1f-8f43ed83be4f.png">
<img width="771" alt="Captura de Tela 2020-03-03 às 18 02 17" src="https://user-images.githubusercontent.com/14796489/75819376-55cac700-5d79-11ea-9776-5b6b8a2e823e.png">

**Comment by FERNman** [comment]
@Leonardo-demeloweb did you manage to fix this? I really can't reproduce this at all without a bit more source code and a more detailed explanation of what you are trying to achieve...

**Comment by Leonardo-demeloweb** [comment]
@FERNman I provided enough information to simulate the BUG. We found the bug in the libraryand we have choose to change the library in our project. The bug found was the INTERPOLATION OF NULLS in the dynamic generation of different graphics. We preferred to use chart.js with the ng2-graphics directive. Now the thing works perfectly. This angular-google-charts library have no support and no examples to be provided. SO I advise against the use of your library.

**Comment by FERNman** [comment]
@Leonardo-demeloweb you know that this library is just a wrapper around the Google Charts library?

The original library has loads of examples and also very thorough documentation.  You can check it out here: https://developers.google.com/chart/interactive/docs/gallery

Nevertheless, this is not a problem with this library. I tried to help you solve the issue, but I still don't really understand what the problem is, sorry.
