### ISSUE TITLE
Migrating to 1.1.0

### ISSUE THREAD

**Issue by FERNman** [FERNman/angular-google-charts#131]
# 1.1.0 was released! 🎉

*Why 1.1.0 and not 1.0.0*?

Because this package already existed a few years ago, and I decided to unpublish it back then to redo it. Young and naive me didn't know that the unpublish functionality should really not be used. Now the version 1.0.0 can't be used anymore, and so it is 1.1.0.

## Breaking changes

As this is the first major release of this package, there are a few breaking changes to the interface. I hope that the new changes will ease working with this package a lot.

### Changes to the `GoogleChartComponent` interface

- `columnNames` was renamed to `columns`
- `roles` was removed and should now be passed in the `columns` array, just how it's done in plain Google Charts
- Added `ChartType` enum which can be used instead of passing plain strings as the chart type

### Changes to the `RawChartComponent` interface

- Renamed to `ChartWrapperComponent`
- Removed `firstRowIsData`, this is no longer necessary
- Removed `dynamicResize`, if you need this functionality, use the `GoogleChartComponent`
- Removed mouse events

### Changes to the `ScriptLoaderService` interface

- Removed `onReady` event, subscribe to `loadChartPackages` instead
- Renamed `doneLoading` to `isGoogleChartsAvailable`

### Additional changes

- When importing the `GoogleChartsModule` using `forRoot`, the config should now be a single object instead of multiple parameters
- `GoogleChartPackagesHelper.getPackageForChartName` was replaced by the function `getPackageForChart`
- The chart event interfaces have been renamed

## Further problems

If you experience any other problems that are not bugs but questions regarding the new version, feel free to ask them in this issue. If I missed some breaking change, I'll add it as soon as possible.

**Comment by smry-web** [comment]
I've noticed since the update the left y-axis now appears on my chart - but only about 80% of the time (same browser, sometimes loads axis on page refresh)

Which is a lot better than the previous 0% of the time with the 0.1.6 build 

In your opinion, is the failed visual a wrapper issue or is there something inherently fragile with google charts?

**Comment by FERNman** [comment]
I don't really think this has anything to do with this package. If you find something, feel free to create a bug. It's probably more of a problem with Google Charts itself. 
Did you take a look at their [forum](https://groups.google.com/forum/#!forum/google-visualization-api)?

**Comment by smry-web** [comment]
I'll review their forums and keep an eye out, thanks
