### ISSUE TITLE
Grouping the data using google.visualization.data.month

### ISSUE THREAD

**Issue by amit509** [FERNman/angular-google-charts#132]
Hi ,

I would like to group the data table by week or month or quarter or year and displaying chart according.

I think we can achieve by using google.visualization.data.month.

Could you please give me a small example or snippet, it would be useful.

Thanks in advance.

**Comment by FERNman** [comment]
Hi @amit509,

as far as I know, this can be done by using a `DataView` to display the data. This is currently not supported in the `GoogleChartComponent`, but maybe in an upcoming version.

For now, I suggest you should use the `ChartWrapperComponent` to access the chart wrapper directly, which allows adding a `DataView` to the chart specs.

Hope this helps!
