### ISSUE TITLE
Column labels on right side get cut off

### ISSUE THREAD

**Issue by jbistis** [FERNman/angular-google-charts#133]
# Feature request

## Describe the solution you'd like
The column labels on the right side of the chart truncate adding ... instead of making the chart smaller and retaining the whole word for the label.  Is there some css that would control this?  

## Describe alternatives you've considered
I've tried various css settings for overflow and position and nothing seems to work
<img width="535" alt="MaterialBarChart" src="https://user-images.githubusercontent.com/26030489/79701011-b64d8f00-8267-11ea-9d56-3864a134b914.png">

**Comment by FERNman** [comment]
Hi @jbistis,

this is not really an issue with this library, but more of a question regarding `GoogleCharts`. After a quick Google search, this [StackOverflow answer](https://stackoverflow.com/a/17338269/4471085) is probably what you want.

**Comment by jbistis** [comment]
Yes, that works great, thanks!
