### ISSUE TITLE
API Key Not used/sent/accepted for GeoChart

### ISSUE THREAD

**Issue by phihochzwei** [FERNman/angular-google-charts#135]
# Bug Report

## Description
I provide the API Key via the config-object in the forRoot-method. However, I receive error instantly 

`Geocoding Service: You must use an API key to authenticate each request to Google Maps Platform APIs. For additional information, please refer to http://g.co/dev/maps-no-account For more information on authentication and Google Maps JavaScript API services please see: https://developers.google.com/maps/documentation/javascript/get-api-key`

After a short period of time (3-6 seconds) I receive two warnings 
`[Warning] Google Maps JavaScript API warning: NoApiKeys https://developers.google.com/maps/documentation/javascript/error-messages#no-api-keys (util.js, line 230)
[Warning] Google Maps JavaScript API warning: InvalidKey https://developers.google.com/maps/documentation/javascript/error-messages#invalid-key (util.js, line 230)`

Also I receive no "select"-Event, but this might be cause by the missing API Key.

## To reproduce
- Integrate into NG9 Project
- import Module with 'forRoot()'

## Expected behaviour
No Error :) 

## Exception or Error
<pre><code>

Geocoding Service: You must use an API key to authenticate each request to Google Maps Platform APIs. For additional information, please refer to http://g.co/dev/maps-no-account For more information on authentication and Google Maps JavaScript API services please see: https://developers.google.com/maps/documentation/javascript/get-api-key

[Warning] Google Maps JavaScript API warning: NoApiKeys https://developers.google.com/maps/documentation/javascript/error-messages#no-api-keys (util.js, line 230)
[Warning] Google Maps JavaScript API warning: InvalidKey https://developers.google.com/maps/documentation/javascript/error-messages#invalid-key (util.js, line 230)
</code></pre>

## Your environment
<pre><code>

Angular CLI: 9.0.4
Node: 12.16.1
OS: darwin x64

Angular: 9.0.4
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.900.4
@angular-devkit/build-angular     0.900.4
@angular-devkit/build-optimizer   0.900.4
@angular-devkit/build-webpack     0.900.4
@angular-devkit/core              9.0.4
@angular-devkit/schematics        9.0.4
@angular/cdk                      9.1.0
@angular/material                 9.1.0
@angular/platform-server          9.0.7
@ngtools/webpack                  9.0.4
@nguniversal/builders             9.1.0
@nguniversal/common               9.0.0-rc.1
@nguniversal/express-engine       9.0.0-rc.1
@schematics/angular               9.0.4
@schematics/update                0.900.4
rxjs                              6.5.4
typescript                        3.7.5
webpack                           4.41.2

</code></pre>

**Comment by FERNman** [comment]
Hi @phihochzwei,

are you sure the API key you're using is valid? I can't really reproduce the issue, for me it's working as expected. You could try to create a small HTML application using plain Google Charts and verify the key is working as expected.

If possible, a small repository reproducing the error would be very welcome!
