### ISSUE TITLE
Select event emitter does not fire

### ISSUE THREAD

**Issue by OrpazL** [FERNman/angular-google-charts#136]
Hello,

I've updated my project to Angular 9 (was 7.0.2) and updated the this package as well.
after modifying everything there's one thing left that I wasn't able to solve, the (select) EventEmitter does not fire up and I couldn't find the reason why..

**Comment by FERNman** [comment]
Hi @OrpazL,

Thanks for submitting this issue! I don't know really why this is happening. Per the documentation, the Chart Wrapper should [emit select events](https://developers.google.com/chart/interactive/docs/reference#events), but it somehow doesn't
If anybody can explain what's happening, I'd be very interested in hearing so.

For now, I'll just change the behaviour to subscribe to the created chart directly.
