### ISSUE TITLE
Directive ChartBase has no selector

### ISSUE THREAD

**Issue by smry-web** [FERNman/angular-google-charts#138]
# Bug Report

## Description
Updated to 1.1.2, **ng build** fails with error claiming "_has no selector, please add it!_"

## To reproduce
1. Delete node_module
2. update package.json from 0.1.6 to "angular-google-charts": "^1.1.2"
3. use ng build (--prod in my instance)

## Expected behaviour
Solution should build without error

## Exception or Error
ERROR in Directive ChartBase in [...]/node_modules/angular-google-charts/angular-google-charts.d.ts has no selector, please add it!

**Comment by FERNman** [comment]
Hi  @smry-web, which version of Angular are you using?
