### ISSUE TITLE
How to collapse Org Charts?

### ISSUE THREAD

**Issue by sagaraher** [FERNman/angular-google-charts#142]
# Bug Report

## Prerequisites

Please answer the following questions for yourself before submitting an issue.
**YOU MAY DELETE THE PREREQUISITES SECTION.**

- [ ] I am running the latest version
- [ ] I checked the Readme and found no answer
- [ ] I checked to make sure that this issue has not already been filed
- [ ] This is related to angular-google-charts and not to Google Charts directly (if it's a Google Charts issue, [their forum](https://groups.google.com/forum/#!forum/google-visualization-api) may help)

## To reproduce
Steps to reproduce the behaviour:

## Exception or Error
<pre><code>

</code></pre>

## Your environment
<pre><code>

</code></pre>

**Comment by FERNman** [comment]
Hi @sagaraher,

to collapse an Org chart you need to call the `collapse` method on the chart object. You get the chart object from the `GoogleChartComponent` through its `chart` property. 

It is, however, important to know that this property will be `null` until the components' `ready` event is fired.

**Comment by sagaraher** [comment]
can you give me some code example for this , I am trying but this method not found in 'chart' property 
Property 'collapse' does not exist on type 'GoogleChartComponent'.

**Comment by FERNman** [comment]
Hi @sagaraher, I hope this helps:

```html
<!-- app.component.html -->
<google-chart (ready)="collapseChart($event)"></google-chart>
```

```typescript
// app.component.ts
import { ChartReadyEvent } from 'angular-google-charts';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html'
})
class MyChartComponent {
  public collapse(event: ChartReadyEvent<google.visualization.OrgChart>) {
    event.chart.collapse(0, true);
  }
}
```

**Comment by semochka** [comment]
Is it possible to set allowCollapse to true? It seems it does not have any effect.

Thank you

```
<google-chart [type]="'OrgChart'" [height]="400" options="{ allowCollapse : true}" [data]="[
    ['Mike', 'President', 'The President'],
    ['Jim', 'Mike', 'VP'],
    ['Alice', 'Mike', ''],
    ['Bob', 'Jim', 'Bob Sponge'],
    ['Carol', 'Bob', '']
 ]" columnNames="['Name','Manager','Tooltip']"></google-chart>
```
