### ISSUE TITLE
Compatibility with Angular Ivy?

### ISSUE THREAD

**Issue by haleyDesignhouse** [FERNman/angular-google-charts#144]
# Feature request
Compatibility with Angular Ivy compiler.

## Describe the solution you'd like
Is this library planning on supporting Angular 9 soon with the Ivy compiler?

**Comment by FERNman** [comment]
Hi @haleyDesignhouse,

As far as I am concerned, this library should be fully compatible with Angular 9. Is there any specific error message you are seeing?

**Comment by haleyDesignhouse** [comment]
> ERROR in node_modules/angular-google-charts/lib/google-charts.module.d.ts:3:22 - error NG6002: Appears in the NgModule.imports of AdminModule, but could not be resolved to an NgModule class.

> This likely means that the library (angular-google-charts) which declares GoogleChartsModule has not been processed correctly by ngcc, or is not compatible with Angular Ivy. Check if a newer version of the library is available, and update if so. Also consider checking with the library's authors to see if the library is expected to be compatible with Ivy.

This is what appears when trying to compile a project in Angular 9 with this library. Ivy is the default compiler whereas in 8, it was optional. I'm guessing it's not compatible with Angular Ivy in particular.

**Comment by FERNman** [comment]
I just created a new project with Angular 9, installed Google Charts and everything works and compiles as expected. Did you try reinstalling your node_modules?

**Comment by haleyDesignhouse** [comment]
Ah after exiting out of my ng serve and rerunning it, it compiles fine. I should have tried that before.. thank you.
