### ISSUE TITLE
setSelection

### ISSUE THREAD

**Issue by erdemmalliq** [FERNman/angular-google-charts#146]
How can I use setSelection?

Reference:
https://developers.google.com/chart/interactive/docs/reference#setselection

**Comment by boltex** [comment]
@erdemmalliq Hi! Did you ever found a way to access underlying google-chart methods directly?

**Comment by boltex** [comment]
Nevermind: got it by using a reference with the '#' character with :
```
<google-chart *ngIf="chartOptions && widgetData.widgetReady"
              #dashboardChart
              [data]="chartData"
              [type]="chartType"
              [columns]="chartColumns"
              [dynamicResize]="true"
              (select)="selectedElement($event, dashboardChart)"
              [options]="chartOptions"></google-chart>
```
and then in code I could refer to the element passed as dashboardChart (which i needed when reacting to select) 
for which i just needed to reset selection in my user case. but this shows how to access the real google-chart underneath. (as described in the ChartBase interface: chart-base.component.d.ts)
```
  public selectedElement(
    p_event: ChartSelectionChangedEvent,
    p_chart: ChartBase
  ): void {
    console.log('onSelect', p_event);
    console.log('chart', p_chart.chart);

    p_chart.chart.setSelection([]);
  }
```
