### ISSUE TITLE
Charts do not redraw after data or chart changes

### ISSUE THREAD

**Issue by m1niml** [FERNman/angular-google-charts#151]
# Bug Report

- [ x ] I am running the latest version
- [ x ] I checked the Readme and found no answer
- [ x ] I checked to make sure that this issue has not already been filed
- [ x ] This is related to angular-google-charts and not to Google Charts directly (if it's a Google Charts issue, [their forum](https://groups.google.com/forum/#!forum/google-visualization-api) may help)

## Description
When trying to change the chart type, changes are not reflected until user filters the data using controls or resizes the window.

## To reproduce
Steps to reproduce the behaviour:
HTML
`<div *ngIf="message">
    <p class="message">{{message}}</p>
</div>
<mat-progress-bar *ngIf="isLoading" color="primary" mode="query"> </mat-progress-bar>
<mat-card class="search-card">
    <mat-radio-group aria-label="Select a report type" [formControl]="action" required>
        <mat-radio-button *ngFor="let empReportType of empReportTypes" [value]="empReportType">
            {{empReportType}}
        </mat-radio-button>
    </mat-radio-group>
    <br />
    <mat-form-field>
        <mat-label>Date From</mat-label>
        <input matInput [matDatepicker]="dateFromDP" [formControl]="dateFrom" disabled>
        <mat-datepicker-toggle matSuffix [for]="dateFromDP"></mat-datepicker-toggle>
        <mat-datepicker #dateFromDP disabled="false"></mat-datepicker>
    </mat-form-field>
    &nbsp;
    <mat-form-field>
        <mat-label>Date To</mat-label>
        <input matInput [matDatepicker]="dateToDP" [formControl]="dateTo" disabled>
        <mat-datepicker-toggle matSuffix [for]="dateToDP"></mat-datepicker-toggle>
        <mat-datepicker #dateToDP disabled="false"></mat-datepicker>
    </mat-form-field>
    <button mat-raised-button color="primary" (click)="getReport()">
        <i class="material-icons">insert_chart_outlined</i> Get Report
    </button>
</mat-card>

<div fxLayout fxLayoutAlign="space-around center" *ngIf="showResults">
    <mat-card class="mat-elevation-z8 results-card" fxFlex *ngFor="let chart of charts; let i = index">

        <mat-card-header>
            <mat-card-title>
                {{chart.data.length}} results found
            </mat-card-title>
            <mat-card-subtitle>Generated: {{dateGenerated}}</mat-card-subtitle>
        </mat-card-header>

        <mat-card-content>
            <dashboard [columns]="chart.columns" [data]="chart.data">
                <control-wrapper *ngFor="let filter of chart.filters" [for]="dashboardChart" [type]="filter.controlType" [options]="filter.options"></control-wrapper>
                <google-chart #dashboardChart width="800" height="600" [title]="chart.title" [type]="chart.type"
                    [data]="chart.data" [columns]="chart.columns" [options]="chart.options" (ready)="onReady()">
                </google-chart>
            </dashboard>
        </mat-card-content>

        <mat-card-actions *ngIf="hasData">
            <button mat-raised-button (click)="changeChart(chart)">
                <i class="material-icons">open_in_browser</i> Switch View
            </button>
            <button mat-raised-button (click)="download()">
                <i class="material-icons">cloud_download</i> Download
            </button>
        </mat-card-actions>
    </mat-card>
</div>`

TS File
<pre><code>
import { Component, OnInit, ViewChild, AfterViewInit } from '@angular/core';
import { FormControl, Validators } from '@angular/forms';
import { DateAdapter, MatPaginator, MatSort, MatTableDataSource, MAT_DATE_FORMATS, MAT_DATE_LOCALE } from '@angular/material';
import { MAT_MOMENT_DATE_ADAPTER_OPTIONS, MomentDateAdapter } from '@angular/material-moment-adapter';
import * as _moment from 'moment';
// tslint:disable-next-line:no-duplicate-imports
import { default as _rollupMoment } from 'moment';
import { ReportsService } from 'src/app/reports.service';
import { UserStorageService } from 'src/app/service/user-storage.service';
import * as XLSX from 'xlsx';
import { ChartBase, ChartEditorComponent, ChartType, Column, GoogleChartComponent, FilterType } from 'angular-google-charts';
declare let google: any;

const moment = _rollupMoment || _moment;

// See the Moment.js docs for the meaning of these formats:
// https://momentjs.com/docs/#/displaying/format/
export const MY_FORMATS = {
  parse: {
    dateInput: 'LL',
  },
  display: {
    dateInput: 'MM-DD-YYYY',
    monthYearLabel: 'MMM YYYY',
    dateA11yLabel: 'LL',
    monthYearA11yLabel: 'MMMM YYYY',
  },
};

export interface ReportResult {
  employeeId: number;
  employeeName: String;
  action: string;
  count: number;
  orgCode: string;
  jobTitle: string;
}

@Component({
  selector: 'counts-by-employee',
  templateUrl: './counts-by-employee.component.html',
  styleUrls: ['./counts-by-employee.component.sass'],
  providers: [
    // `MomentDateAdapter` can be automatically provided by importing `MomentDateModule` in your
    // application's root module. We provide it at the component level here, due to limitations of
    // our example generation script.
    {
      provide: DateAdapter,
      useClass: MomentDateAdapter,
      deps: [MAT_DATE_LOCALE, MAT_MOMENT_DATE_ADAPTER_OPTIONS]
    },

    { provide: MAT_DATE_FORMATS, useValue: MY_FORMATS },
  ]
})
export class CountsByEmployeeComponent implements OnInit {
  action = new FormControl('', Validators.required);
  dateFrom = new FormControl(moment());
  dateTo = new FormControl(moment());
  dateGenerated: Date;
  message: string;
  empReportTypes: string[] = ['Scan', 'Index', 'Quality Check', 'Workflow', 'Self Service', 'Barcode'];
  displayedColumns: string[];
  displayedColumnsNWF: string[] = ['employee', 'count', 'orgCode', 'jobTitle'];
  displayedColumnsWF: string[] = ['employee', 'action', 'count', 'orgCode', 'jobTitle']
  isLoading: boolean = false;
  isWorkflow: boolean = false;
  hasData: boolean = false;
  colCount: number = 0;
  showResults: boolean = false;
  showChart: boolean = false;
  dataSource: MatTableDataSource<ReportResult> = new MatTableDataSource();
  @ViewChild(MatPaginator, { static: true }) paginator: MatPaginator;
  @ViewChild(MatSort, { static: true }) sort: MatSort;

  @ViewChild('chart', { static: true })
  public chart: GoogleChartComponent;

  @ViewChild(ChartEditorComponent, { static: false })
  public readonly editor: ChartEditorComponent;

  cbe: ReportResult[];

  chart_title = 'Counts By Employee';
  chart_type = 'PieChart';
  chart_data = [];
  chart_columnNames = [];
  chart_options = {};

  constructor(private userService: UserStorageService,
    private reportService: ReportsService) {

  }

  public charts: {
    title: string;
    type: ChartType;
    data: any[][];
    columns?: Column[];
    options?: {};
    filters?: any[];
  }[] = [];

  public chartFilters: {
    controlType: FilterType;
    containerId: string;
    options?: {};
    state?: {};
  }[] = [];

  drawChart(reportData: ReportResult[]) {
    if (reportData == null) {
      this.showChart = false;
      return;
    }
    this.charts = [];
    this.chartFilters = [];

    //let controlFilters = [];
    this.chartFilters.push({
      controlType: FilterType.String,
      containerId: 'dashboardChart',
      options: {
        filterColumnLabel: 'Employee'
      }
    });

    this.chartFilters.push({
      controlType: FilterType.NumberRange,
      containerId: 'dashboardChart',
      options: {
        filterColumnLabel: this.action.value + ' Count'
      },
      state: {
        //lowValue: 1,
        //highValue: reportData.sort((a,b) => (a.count > b.count) ? 1 : -1)[0].count
      }
    });

    let chart = {
      title: 'Counts By Employee',
      type: ChartType.PieChart,
      columns: ['Employee', this.action.value + ' Count'],
      data: [],
      options: { is3D: true },
      filters: this.chartFilters
    };

    reportData.forEach(function (report) {
      chart.data.push([(report.employeeName != null ? report.employeeName : report.employeeId), report.count]);
    });
    this.charts.push(chart);
  }

  changeChart(chart: any) {
    console.log(chart);
    if(chart.type == ChartType.PieChart) {
      chart.type = ChartType.Table;
    } else {
      chart.type = ChartType.PieChart;
    }
    console.log(chart.type);
    chart.draw(chart.data, chart.options);
  }

  onReady() {
    console.log('Chart ready');
  }

  ngOnInit() {
    let user = this.userService.getUserDetails();
    this.dataSource.paginator = this.paginator;
    this.dataSource.sort = this.sort;
  }

  getReport() {
    this.hasData = false;
    this.showChart = false;
    this.showResults = false;
    return this.loadList(this.action.value, this.dateFrom.value, this.dateTo.value);
  }

  loadList(action: string, dateFrom: any, dateTo: any) {
    if (action == 'Workflow') {
      this.displayedColumns = this.displayedColumnsWF;
    } else {
      this.displayedColumns = this.displayedColumnsNWF;
    }
    this.colCount = this.displayedColumns.length;
    this.isLoading = true;
    this.chart_data = [];
    this.reportService.getCountsByEmployee(action, dateFrom, dateTo).subscribe(
      (response: any) => {
        this.hasData = (response != null && response.response != null && response.response.body != null);
        if (this.hasData) {
          this.cbe = response.response.body;
          this.dataSource = new MatTableDataSource(this.cbe);
          this.dataSource.paginator = this.paginator;
          this.dataSource.sort = this.sort;
          this.drawChart(response.response.body);
        } else {
          this.dataSource = new MatTableDataSource();
          this.showChart = false;
          console.log(response);
        }
        this.isLoading = false;
        this.dateGenerated = new Date();
        this.showResults = true;
      }, error => {
        this.isLoading = false;
        this.hasData = false;
        console.log(error.error.status.message);
        this.message = error.error.status.message;
      }
    );
  }

  applyFilter(event: Event) {
    const filterValue = (event.target as HTMLInputElement).value;
    this.dataSource.filter = filterValue.trim().toLowerCase();

    if (this.dataSource.paginator) {
      this.dataSource.paginator.firstPage();
    }
  }

  download() {
    const worksheet: XLSX.WorkSheet = XLSX.utils.json_to_sheet(this.dataSource.data);
    const workbook: XLSX.WorkBook = { Sheets: { data: worksheet }, SheetNames: ['data'] };
    XLSX.writeFile(workbook, `counts_by_employee.xlsx`);
  }

}
</code></pre>

## Expected behaviour
The chart should automatically redraw itself or API method provided to manually force a refresh that does not pertain to data (already read the data hack thread regarding charts not updating and no solution provided there works).
## Exception or Error
<pre><code>

CountsByEmployeeComponent.html:84 ERROR TypeError: chart.draw is not a function
    at CountsByEmployeeComponent.push../src/app/modules/reports/counts-by-employee/counts-by-employee.component.ts.CountsByEmployeeComponent.changeChart (counts-by-employee.component.ts:163)
    at Object.eval [as handleEvent] (CountsByEmployeeComponent.html:84)
    at handleEvent (core.js:29238)
    at callWithDebugContext (core.js:30308)
    at Object.debugHandleEvent [as handleEvent] (core.js:30035)
    at dispatchEvent (core.js:19858)
    at core.js:28447
    at HTMLButtonElement.<anonymous> (platform-browser.js:1032)
    at ZoneDelegate.push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask (zone.js:423)
    at Object.onInvokeTask (core.js:26246)
</code></pre>

## Your environment
<pre><code>

Angular CLI: 8.3.8
Node: 11.13.0
OS: win32 x64
Angular: 8.2.9
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.803.8
@angular-devkit/build-angular      0.803.25
@angular-devkit/build-optimizer    0.803.25
@angular-devkit/build-webpack      0.803.25
@angular-devkit/core               8.3.8
@angular-devkit/schematics         8.3.8
@angular/cdk                       8.2.3
@angular/cli                       8.3.8
@angular/flex-layout               8.0.0-beta.27
@angular/material                  8.2.3
@angular/material-moment-adapter   8.2.3
@ngtools/webpack                   8.3.25
@schematics/angular                8.3.8
@schematics/update                 0.803.8
rxjs                               6.4.0
typescript                         3.5.3
webpack                            4.39.2
</code></pre>

**Comment by FERNman** [comment]
Could you maybe remove all the unnecessary code in the issue description and retain only the necessary code to reproduce this issue?
