### ISSUE TITLE
prod build is getting error

### ISSUE THREAD

**Issue by ramanacr** [FERNman/angular-google-charts#155]
# Bug Report

## Prerequisites

Please answer the following questions for yourself before submitting an issue.
**YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the Readme and found no answer
- [ ] I checked to make sure that this issue has not already been filed
- [x] This is related to angular-google-charts and not to Google Charts directly (if it's a Google Charts issue, [their forum](https://groups.google.com/forum/#!forum/google-visualization-api) may help)

## Description
I have updated to version 1.1.4
My angular version is 8.2.14
Getting below error for prod build:

```
ERROR in Can't bind to 'columnNames' since it isn't a known property of 'google-chart'.
1. If 'google-chart' is an Angular component and it has 'columnNames' input, then verify that it is part of this module.
2. If 'google-chart' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.
3. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. ("oogle-chart [type]="'Table'"
                            [title]="''"
                            [ERROR ->][columnNames]="agExpColumns"
                            [data]="dashboard.AgreementsExpiringIn6Mont")
```

## To reproduce
Steps to reproduce the behaviour:

## Exception or Error
<pre><code>

ERROR in Can't bind to 'columnNames' since it isn't a known property of 'google-chart'.
1. If 'google-chart' is an Angular component and it has 'columnNames' input, then verify that it is part of this module.
2. If 'google-chart' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.
3. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. ("oogle-chart [type]="'Table'"
                            [title]="''"
                            [ERROR ->][columnNames]="agExpColumns"
                            [data]="dashboard.AgreementsExpiringIn6Mont")
</code></pre>

## Your environment
<pre><code>

Angular CLI: 8.3.26
Node: 12.16.2
OS: win32 x64
Angular: 8.2.14
... animations, common, compiler, compiler-cli, core, elements
... forms, language-service, platform-browser
... platform-browser-dynamic, router, service-worker

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.803.26
@angular-devkit/build-angular     0.803.26
@angular-devkit/build-optimizer   0.803.26
@angular-devkit/build-webpack     0.803.26
@angular-devkit/core              8.3.26
@angular-devkit/schematics        8.3.26
@angular/cli                      8.3.26
@angular/pwa                      0.901.6
@ngtools/webpack                  8.3.26
@schematics/angular               8.3.26
@schematics/update                0.803.26
rxjs                              6.4.0
typescript                        3.5.3
webpack                           4.39.2
</code></pre>

## Anything else?
ng build works fine, but ng build --prod has the error with this version v1.1.4

**Comment by ramanacr** [comment]
```
<google-chart [type]="'Table'"
                            [title]="''"
                            [columnNames]="agExpColumns"
                            [data]="dashboard.AgreementsExpiringIn6Months"
                            [options]="tableChartOptions" style="width:100%;">
              </google-chart>
```
has been modified to:
```
<google-chart [type]="'Table'"
                            [title]="''"
                            [columns]="agExpColumns"
                            [data]="dashboard.AgreementsExpiringIn6Months"
                            [options]="tableChartOptions" style="width:100%;">
              </google-chart>
```
the issue has been resolved.

**Comment by ShreyasAmbre** [comment]
Thanks @ramanacr
