### ISSUE TITLE
'Bar' Material Chart - IsStacked option not working

### ISSUE THREAD

**Issue by abrasat** [FERNman/angular-google-charts#157]
# Bug Report

## Prerequisites

Please answer the following questions for yourself before submitting an issue.
**YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the Readme and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] This is related to angular-google-charts and not to Google Charts directly (if it's a Google Charts issue, [their forum](https://groups.google.com/forum/#!forum/google-visualization-api) may help)

## Description
Setting the option isStacked=True for the ChartType.Bar has no effect. The columns are displayed separately instead of stacked

## Expected behaviour
The column values are stacked in the display.

**Comment by FERNman** [comment]
This should definitely be working using this library. I hope you were able to fix your code!

If anybody is able to reproduce this and thinks this is a problem with this library, leave a comment!
