### ISSUE TITLE
Compatibility with Angular 10?

### ISSUE THREAD

**Issue by rubenv** [FERNman/angular-google-charts#158]
The dependencies do not allow for installation with Angular 10. Is this intentional (and incompatible), or does this module just need a bump now that Angular 10 is out?

**Comment by FERNman** [comment]
I think it just needs a bump. If you'd verify that it works, I'd be happy to upgrade the dependencies (or you could even do it yourself with a PR).

**Comment by rubenv** [comment]
How should I go about verifying this? My experience on how Angular libraries are packaged / tested is sadly *very* limited. The knowledge I have is still related to AngularJS (yup, that old stuff), which I guess doesn't apply anymore.

**Comment by Socratezz** [comment]
I just finished updating to Angular 10. All I needed to do was uninstall this and run the Angular 10 update, then re-add the module. Everything works fine. I only get npm warnings about it.
