### ISSUE TITLE
Line Chart is not rendered in IE11

### ISSUE THREAD

**Issue by rbaezaMiro** [FERNman/angular-google-charts#160]
When try to renderer line chart in IE11 nothing happen, in others browsers like Mozilla, Chrome is not problem.
I added the polyfills to support IE11 in angular 7 but still not working.

/***************************************************************************************************
 * BROWSER POLYFILLS
 */
import 'core-js/es6/symbol';
import 'core-js/es6/object';
import 'core-js/es6/function';
import 'core-js/es6/parse-int';
import 'core-js/es6/parse-float';
import 'core-js/es6/number';
import 'core-js/es6/math';
import 'core-js/es6/string';
import 'core-js/es6/date';
import 'core-js/es6/regexp';
import 'core-js/es6/map';
import 'core-js/es6/weak-map';
import 'core-js/es6/set';
import 'core-js/es6/array';
import 'core-js/es6/reflect';
import 'core-js/es6/promise'; 
import 'core-js/es7/reflect';
import 'core-js/es7/object';
import 'core-js/es7/array';
import 'core-js/es7/object';
import 'core-js/fn/string/includes';
import 'core-js/client/shim';

**Comment by FERNman** [comment]
I suppose this has to do with the Google Charts library and not this one, closing for now.
