### ISSUE TITLE
Version option in the config is not respected.

### ISSUE THREAD

**Issue by zakhcst** [FERNman/angular-google-charts#162]
# Bug Report

## Prerequisites

- [X] I am running the latest version
- [X] I checked the Readme and found no answer
- [X] I checked to make sure that this issue has not already been filed
- [X] This is related to angular-google-charts and not to Google Charts directly (if it's a Google Charts issue, [their forum](https://groups.google.com/forum/#!forum/google-visualization-api) may help)

## Description
Setting a version number or not setting any in the host module imports

`GoogleChartsModule.forRoot({ version: 'chart-version' })`

results in console warning:

`Attempting to load version '49' of Google Charts, but the previously loaded 'current' will be used instead.
`

The second request to loader.js, always defaults to version 49.

`Request URL: https://www.gstatic.com/charts/49/loader.js`

In both versions ES5 and ES2015 and Angular 9 and 10 the result is the same.

In Angular 8 I have been using 
`"angular-google-charts": "^0.1.6"`
where the google-charts version is 46.2 and the charts are working properly.

Changing manually config.version 'current' to '46.2' in the compiled library did not fix my issue with the charts not scaling properly in Angular 9 and 10 but this is another issue.

Debugging so far shows that

`const GOOGLE_CHARTS_CONFIG = new InjectionToken('GOOGLE_CHARTS_CONFIG');`

'GOOGLE_CHARTS_CONFIG' token is not injected in the 'ScriptLoaderService'.

**Comment by dolphinsd** [comment]
this is related to https://github.com/FERNman/angular-google-charts/issues/164

**Comment by FERNman** [comment]
Could this be related to the different injection scopes in Angular? Maybe the `ScriptLoaderService` is instantiated in an injection scope where the `GOOGLE_CHARTS_CONFIG` token is not available.

**Comment by kirillvarikow** [comment]
@FERNman any news? Do you know how to fix it?

**Comment by FERNman** [comment]
I can verify the warning when not specifying any version in the config. However, when specifying a concrete version (e.g. `48.1`), no warning appears and the correct version is used.

Can anybody provide me with a repo that reproduces this error and actually causes Google charts to use a different version than the one specified?

If this issue is only about the warning, then I don't actually know if I can do anything about it.

**Comment by FERNman** [comment]
I will close this for now. If it comes up again, feel free to comment here!
