### ISSUE TITLE
Google Maps API Key config not working in production

### ISSUE THREAD

**Issue by anuj9196** [FERNman/angular-google-charts#164]
# Bug Report

## Prerequisites

Please answer the following questions for yourself before submitting an issue.
**YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the Readme and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] This is related to angular-google-charts and not to Google Charts directly (if it's a Google Charts issue, [their forum](https://groups.google.com/forum/#!forum/google-visualization-api) may help)

## Description
I'm using the `ChartType.GeoChart` and my components HTML is
```
<div class="row">
  <div class="col-md-12">
    <google-chart
      [type]="chartType"
      [data]="chartData"
      [options]="chartOptions"
      style="width: 100%;" [height]="400"
      (ready)="onReady($event)"
      (select)="onSelect($event)">
    </google-chart>
  </div>
</div>
```
the component's ts file
```
export class GoogleChartPreviewComponent implements OnInit, AfterViewInit {

  @Input() chartData = [
    ['India', 10]
  ];
  @Input() chartType: ChartType = ChartType.GeoChart;
  @Input() chartOptions = {
    colors: ['#8d8d8d', '#c0392b'],
  };

  @ViewChild('gChart', {static: false}) gChart: GoogleChartComponent;

  @Output() chartReady: EventEmitter<ChartReadyEvent<google.visualization.ChartBase>> =
    new EventEmitter<ChartReadyEvent<google.visualization.ChartBase>>();

  @Output() chartSelect: EventEmitter<ChartSelectionChangedEvent> = new EventEmitter<ChartSelectionChangedEvent>();

  constructor() { }

  ngOnInit() {
  }

  ngAfterViewInit() {
    console.log('afterViewInit called');
  }

  public getChartImage(format: string) {
    const wrapper = this.gChart.chartWrapper as any;
    return  wrapper.visualization.getImageURI();
  }

  onReady($event: ChartReadyEvent<google.visualization.ChartBase>) {
    this.chartReady.emit($event);
  }

  onSelect($event: ChartSelectionChangedEvent) {
    this.chartSelect.emit($event);
  }
}
```
This works fine in the development environment, but when pushed to the production server with the production build. the `GoogleChartPreviewComponent` renders nothing and just blank page.

I put `console` in `ngAfterViewInit` just to check if the component is completing the rendering, but this method is never called and the `afterViewInit called` log is never printed.

## To reproduce
Steps to reproduce the behaviour:

## Expected behaviour
The Google chart should be displayed in the production build just like it does in the local development.

## Exception or Error
<pre><code>

There is no error/exception in the console. The component's `ngAfterViewInit` is never called.
</code></pre>

## Your environment
<pre><code>

Angular CLI: 8.3.25
Node: 12.14.1
OS: darwin x64
Angular: 8.2.14
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.803.25
@angular-devkit/build-angular      0.803.25
@angular-devkit/build-ng-packagr   0.803.28
@angular-devkit/build-optimizer    0.803.25
@angular-devkit/build-webpack      0.803.25
@angular-devkit/core               8.3.25
@angular-devkit/schematics         8.3.25
@angular/cdk                       8.2.3
@angular/cli                       8.3.25
@angular/material                  8.2.3
@ngtools/webpack                   8.3.25
@schematics/angular                8.3.25
@schematics/update                 0.803.25
ng-packagr                         5.7.1
rxjs                               6.5.4
typescript                         3.5.3
webpack                            4.39.2
</code></pre>

## Anything else?

The `app.module.ts` has the configuration

```
GoogleChartsModule.forRoot({
    mapsApiKey: environment.googleMapAPIKey
}),
```

Even tried loading the chart loaders in the `index.html` `head`. But still, it does not show anything and the view is not completing rendering.

**Comment by dolphinsd** [comment]
@FERNman  any chance this will be fixed, library is useless for any map related charts. Thanks.

**Comment by dolphinsd** [comment]
Issues seems to be in contstrtor of ScriptLoaderService

this.config = { ...DEFAULT_CONFIG, ...(config || {}) };
should be replaced with 
this.config = { ...GOOGLE_CHARTS_CONFIG, ...(config || {}) };

**Comment by FERNman** [comment]
@dolphinsd Do you have any idea on why that happens?

**Comment by anuj9196** [comment]
Solved. In order to use `map`, it is required to define in the `packages`

```
const MyGoogleChartsSettings: GoogleChartsSettings = {
  mapsApiKey: environment.googleMapAPIKey,
  packages: ['map']
};
```

**Comment by FERNman** [comment]
I will close this for now as per @anuj9196 's comment. If there really is something wrong with the config, I'll re-investigate this issue.

**Comment by cscrum** [comment]
I'm not sure I understand the fix. In what package do we place that code?

**Comment by anuj9196** [comment]
@cscrum In the app.module.ts file

**Comment by chiragvels** [comment]
@anuj9196 ,

I cannot see any option to add packages. and how I can use GoogleChartsSettings? 

 If there really is something wrong with the config, I'll re-investigate this issue.
@FERNman, Yes I think config has no option to pass package.

**Comment by anuj9196** [comment]
@chiragvels I hope the following configuration will help you

```
import {BrowserModule} from '@angular/platform-browser';
import {NgModule} from '@angular/core';
import {AppComponent} from './app.component';
import {AgmCoreModule, GoogleMapsAPIWrapper} from '@agm/core';

const MyGoogleChartsSettings: GoogleChartsSettings = {
  mapsApiKey: environment.googleMapAPIKey,
  packages: ['map']
};

@NgModule({
  declarations: [
    AppComponent
  ],
  imports: [
    BrowserModule,
    BrowserAnimationsModule,
    AgmCoreModule.forRoot({
      apiKey: environment.googleMapAPIKey,
      libraries: ['places']
    })
  ],
  providers: [
    GoogleMapsAPIWrapper,
    {
      provide: 'googleChartsSettings',
      useValue: MyGoogleChartsSettings,
    },
  ],
  exports: [
  ],
  bootstrap: [
    AppComponent,
  ]
})
export class AppModule { }
```

**Comment by dolphinsd** [comment]
@anuj9196 your solution above does not compile as GoogleChartsSettings  does not exit
@FERNman issue is not fixed, as I tested @anuj9196 and it does not work, key never passed
