### ISSUE TITLE
Customize tooltip

### ISSUE THREAD

**Issue by wijnandhonselaar** [FERNman/angular-google-charts#165]
# Feature request
I'm having trouble to get custom tooltips to work.

## Describe the solution you'd like
I'm looking to alter the default tooltip. According to the documentation the column definition should be the following: 

`{type: 'string', role: 'tooltip'}`. 

## Describe alternatives you've considered
I've tried to alter the columns by using the same structure as above for the other columns:
`chartColumns = [{type: 'string', id: 'Bike'}, {type: 'string', id: 'Name'}, {type: 'date', id: 'From'}, {type: 'date', id: 'Until'}, {type: 'string', role: 'tooltip'}];`
When a column has the 'tooltip' role assigned to it, it will not show up in the chart.

## Additional context
I'm using the 'timeline' chart.
`<google-chart #chartRef *ngIf="data" [type]="'Timeline'" [data]="data" [dynamicResize]="true" (select)="onSelect($event)" [columns]="chartColumns" [options]="chartOptions"></google-chart>`

**Comment by FERNman** [comment]
Hi @wijnandhonselaar, sorry for not getting back to you for that long. I hope you already solved this problem by now!

I just tried adding tooltips to a timeline chart as per the [official example](https://developers.google.com/chart/interactive/docs/gallery/timeline#customizing-tooltips) and it works perfectly fine for me. 

If anybody else has troubles with tooltips, I'm happy to investigate further. For now, I'll close this issue.

**Comment by FERNman** [comment]
Hi @caseyjfer, did you try upgrading to a newer version of Angular-Google-Charts? It should be backwards compatible with all Angular versions from 6.0 upwards.

**Comment by caseyjfer** [comment]
> Hi @caseyjfer, did you try upgrading to a newer version of Angular-Google-Charts? It should be backwards compatible with all Angular versions from 6.0 upwards.

I just tried bumping up to the latest version (2.2.2) again, and I saw again why I tried downgrading: 
angular-google-charts.js:300 Uncaught TypeError: _angular_core__WEBPACK_IMPORTED_MODULE_1__.ɵɵdefineInjectable is not a function
    at Module../node_modules/angular-google-charts/fesm2015/angular-google-charts.js (angular-google-charts.js:300)

Using angular 7.2

**Comment by ErnestoCamilo** [comment]
`<google-chart [type]="classType" [data]="chartData" [options]="classOptions" *ngIf="!loading" [dynamicResize]="dynamicResize" class="chart">
  </google-chart>`

`classType = ChartType.ColumnChart;`

`classLabels: any[] = ['Class', 'Usage', { role: 'tooltip', type: 'string', p: {html: true} }];`

`result = [['2010', '600','$600K in our first year!'],
          ['2011', '1500', 'Sunspot activity made this our best year ever!'],
          ['2012', '800', '$800K in 2012.'],
          ['2013', '1000', '$1M in sales last year.']]
    this.chartData = result;
    console.log(this.chartData)
    this.loadFinished.emit();
    this.loading = loading;
  }`
this is basically my configuration, this is the package in my package.json installed
`"angular-google-charts": "2.0.1",`
and this is the declaration in my module 
`
@NgModule({
  declarations: [],
  imports: [
    CommonModule, FlexLayoutModule, GoogleChartsModule.forRoot({ version: '49' }),
    
  ],
  entryComponents: [],
  providers: [],
  exports: []
})
export class ClassesModule { }`
with this configuration, I can't see the graphic with the toolbar. I need a little help here. 
Greetings
