### ISSUE TITLE
Add custom error handler and use google.visualization.errors.removeError method

### ISSUE THREAD

**Issue by rafaelcoutinho** [FERNman/angular-google-charts#170]
# Feature request

## Describe the solution you'd like
I would like to remove the default error div generated by google charts. It is possible with the API to do that by catching the event and using this function google.visualization.errors.removeError(googleError.id); 

How could we achieve the same behavior? If not already in the wrapper?

**Comment by FERNman** [comment]
Hi @rafaelcoutinho, sorry for not getting back to you sooner - I somehow completely missed this issue!

Hopefully, you've already resolved this by now. For future reference, this can be done by accessing the native google chart instance through `googleChartComponent.chart` and using the method provided in the description of the issue. The `error` event emitter can be used to catch the error in the first place.

If someone wants this functionality to be added without using `google.visualization`, feel free to create a PR or write another comment. For now, I'll close this 🙂
