### ISSUE TITLE
Compile error with Angular 10.1.2: `error TS2380: 'get' and 'set' accessor must have the same type`

### ISSUE THREAD

**Issue by guss77** [FERNman/angular-google-charts#173]
# Bug Report

## Prerequisites

Please answer the following questions for yourself before submitting an issue.
**YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the Readme and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] This is related to angular-google-charts and not to Google Charts directly (if it's a Google Charts issue, [their forum](https://groups.google.com/forum/#!forum/google-visualization-api) may help)

## Description

After installing as per the instructions, and adding the `<google-chart>` component to the app, Angular `ng serve` spews:

```
    ERROR in node_modules/angular-google-charts/lib/components/chart-wrapper/chart-wrapper.component.d.ts:28:9 - error TS2380: 'get' and 'set' accessor must have the same type.
    
    28     get chartWrapper(): google.visualization.ChartWrapper | null;
               ~~~~~~~~~~~~
    node_modules/angular-google-charts/lib/components/chart-wrapper/chart-wrapper.component.d.ts:29:9 - error TS2380: 'get' and 'set' accessor must have the same type.
    
    29     set chartWrapper(wrapper: google.visualization.ChartWrapper);
               ~~~~~~~~~~~~
```

I'm using Angular 10.1.2 with Ivy.

Looking at the code, it indeed looks that `set chartWrapper` is missing `|null`.

## Your environment
<pre><code>
Angular CLI: 10.1.2
Node: 10.19.0
OS: linux x64

Angular: 10.1.2
... animations, cli, common, compiler, compiler-cli, core, forms
... localize, platform-browser, platform-browser-dynamic, router
Ivy Workspace: Yes

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1001.2
@angular-devkit/build-angular   0.1001.2
@angular-devkit/core            10.1.2
@angular-devkit/schematics      10.1.2
@angular/cdk                    10.2.1
@angular/material               10.2.1
@schematics/angular             10.1.2
@schematics/update              0.1001.2
rxjs                            6.6.3
typescript                      4.0.2
</code></pre>

**Comment by edupinof** [comment]
Same error here... waiting for an answer

**Comment by Airblader** [comment]
If you disable strictNullChecks the issue should go away, though unfortunately this is project-wide.

**Comment by ronagalvao** [comment]
I'm with this problem here:

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1100.1
@angular-devkit/build-angular   0.1100.1
@angular-devkit/core            11.0.1
@angular-devkit/schematics      11.0.1
@angular/cli                    11.0.1
@schematics/angular             11.0.1
@schematics/update              0.1100.1
rxjs                            6.6.3
typescript                      4.0.5

Thank you!

**Comment by GabrielMJin** [comment]
i'm with this problem too.
angular v 11

**Comment by FabricioMarrone** [comment]
Same problem here (angular 11)

"@angular-devkit/build-angular": "~0.1100.4",
"@angular/cli": "~11.0.4",
"@angular/compiler-cli": "~11.0.4",
"ts-node": "~8.3.0",
"tslint": "~6.1.0",
"typescript": "~4.0.2"

Disabling strict mode makes it work, but it's a workaround, not a fix. Why [PR185](https://github.com/FERNman/angular-google-charts/pull/185) is not merged?

**Comment by kussmaul** [comment]
This is a kludge, but I edited node_modules/angular-google-charts/lib/components/chart-wrapper/chart-wrapper.component.d.ts to have consistent types:
```
    get chartWrapper(): google.visualization.ChartWrapper | null;
    set chartWrapper(wrapper: google.visualization.ChartWrapper | null);
```
I agree that it would be better to fix chart-wrapper-component.ts

**Comment by kussmaul** [comment]
I updated to angular-google-charts@2.01 and no longer see this problem
