### ISSUE TITLE
Chart not drawing because firstRowIsData is set to true

### ISSUE THREAD

**Issue by luisvargasexepron** [FERNman/angular-google-charts#174]
# Bug Report

## Description
When creating a `google-chart` component with only data passed, it does not draw the chart. This is because `firstRowIsData` is true.

## To reproduce
1. Create a component containing a `google-chart` with columns inside `data`  attribute like next:

```html
<google-chart id="my-daily-activities"
              title="My Daily Activities"
              type="PieChart"
              [data]="[
                        ['Task', 'Hours per Day'],
                        ['Work',     11],
                        ['Eat',      2],
                        ['Commute',  2],
                        ['Watch TV', 2],
                        ['Sleep',    7]
                      ]"></google-chart>
```

2. See that chart will be created but not drawn.

## Expected behaviour
Chart should be created and drawn

## Exception or Error
There is no error messages

## Your environment
<pre><code>
Angular CLI: 10.1.4
Node: 12.18.4
OS: win32 x64

Angular: 10.1.4
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router
Ivy Workspace: Yes

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1001.4
@angular-devkit/build-angular   0.1001.4
@angular-devkit/core            10.1.4
@angular-devkit/schematics      10.1.4
@schematics/angular             10.1.4
@schematics/update              0.1001.4
rxjs                            6.6.3
typescript                      4.0.3
angular-google-charts           1.1.6
google.api.version              49
</code></pre>

## Anything else?
Looks like the error is produced in next line:

https://github.com/FERNman/angular-google-charts/blob/master/libs/angular-google-charts/src/lib/components/google-chart/google-chart.component.ts#L225

changing it from:

```ts
this.dataTable = google.visualization.arrayToDataTable(this.getDataAsTable(), firstRowIsData);
```

to:

```ts
this.dataTable = google.visualization.arrayToDataTable(this.getDataAsTable());
```

would solve the issue.

**Comment by FERNman** [comment]
The first row in your `data` array should be passed using a separate property, `columns`. Alternatively you could use the `ChartWrapperComponent`, which would allow you to pass a data array just like you do when using Google charts natively.
