### ISSUE TITLE
Lazy load configuration

### ISSUE THREAD

**Issue by learnuser521** [FERNman/angular-google-charts#175]
# Feature request

## Describe the solution you'd like
There is an option to provide configuration when we import GoogleChartsModule.

GoogleChartsModule.forRoot({ version: 'chart-version' });

It would be very helpful if the configuration can be lazy loaded. The reason for asking the option to lazy load the config is we can receive the maps api key from a http call, which can then be set if there is a lazy loading option.

**Comment by FERNman** [comment]
Hi @learnuser521,

How would you like this option to work? I'm happy for any suggestions or PRs :)

**Comment by learnuser521** [comment]
The only way I could think of is providing the config as an input to google-chart component.

**Comment by FERNman** [comment]
The problem with this approach is that the config needs to be provided when loading the package (as far as I know at least). And the package can be loaded in multiple situations, not only when creating a new Google chart component.

Maybe there's an option in the Google Chart script to update the config.

**Comment by AlmaniaM** [comment]
@learnuser521 You can update your charts to the latest version to be able to lazy-load a config object. Please see the readme for instructions on how to do so.

**Comment by FERNman** [comment]
I will close this as @AlmaniaM's PR should fix this.
