### ISSUE TITLE
(Gantt) Chart can't be displayed if date has hours specified

### ISSUE THREAD

**Issue by AaronWiora** [FERNman/angular-google-charts#176]
## Description
I want to create a gantt chart. When a date includes a time the chart can't be displayed:

### Using angular-google-charts:
`new Date(2020, 3, 10)` ✅ 
`new Date(2020, 3, 10, 8)` ❌
`new Date("2020-10-14T00:00:00.00+02:00")` ✅ 
`new Date("2020-10-14T08:43:45.773+02:00")` ❌

### Using google chart's .arrayToDataTable():
`new Date(2020, 3, 10)` ✅ 
`new Date(2020, 3, 10, 8)`✅ 
`new Date("2020-10-14T00:00:00.00+02:00")` ✅ 
`new Date("2020-10-14T08:43:45.773+02:00")`  ✅ 

## To reproduce
Steps to reproduce the behaviour:
1. Add gantt chart
2. In data array use a date with hours specified

## Expected behaviour
Gantt chart get displayed

## Exception or Error
<pre><code>
Invalid data table format: column #3 must be of type 'date'.×

</code></pre>

<pre><code>
Angular CLI: 10.0.8
Node: 10.19.0
OS: linux x64

Angular: 10.0.14
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.1000.8
@angular-devkit/build-angular     0.1000.8
@angular-devkit/build-optimizer   0.1000.8
@angular-devkit/build-webpack     0.1000.8
@angular-devkit/core              10.0.8
@angular-devkit/schematics        10.0.8
@angular/cdk                      10.2.0
@angular/cli                      10.0.8
@angular/material                 10.2.0
@ngtools/webpack                  10.0.8
@schematics/angular               10.0.8
@schematics/update                0.1000.8
rxjs                              6.5.5
typescript                        3.9.7
webpack                           4.43.0
</code></pre>

**Comment by FERNman** [comment]
Did you manage to resolve this? Internally, the `GoogleChartComponent` uses `arrayToDataTable`, so I'm really wondering why this doesn't work.

**Comment by AaronWiora** [comment]
Not yet. I was surprised myself because as I was aware that the Component uses arrayToDataTable. I don't really know where to start looking. Do you use some form of type validation? I found the following lines searching for "Date":
package-lock.json: is-date-object
chart-base.component.ts: Row(string | number |Date)[];
control-type.model.ts: DateRange = 'DateRangeFilter'

**Comment by FERNman** [comment]
I don't validate any inputs except by using the Typescript compiler (obviously) and then passing them to Google Charts.

**Comment by FERNman** [comment]
I will close this for now. If it comes up again, feel free to comment here!
