### ISSUE TITLE
Debounce resizing

### ISSUE THREAD

**Issue by jrabek** [FERNman/angular-google-charts#18]
Thanks for the project!

I started using angular-google-charts before you had dynamic resize and added my own.  I noticed the recently added implementation resizes on every window resize event which is fired a lot.

I did the the following at the parent container level but would be nice to have something like this at the component level:

```
  ngAfterViewInit() {
    fromEvent(window, 'resize')
      .pipe(debounceTime(500))
      .subscribe(() => {
        this.chartComponents.forEach( c => {
          c.wrapper.draw();
        })
      })
  }
```

**Comment by FERNman** [comment]
Thanks a lot for this code. I didn't know `fromEvent` existed. I was concerned with performance when writing the code, however, for the test cases I wrote, it was fast enough.
Nevertheless, I used your code as a replacement. Made Unit testing easier and surely improves the performance! Thanks a lot 👍
