### ISSUE TITLE
Tooltips not displayed

### ISSUE THREAD

**Issue by cyberbobjr** [FERNman/angular-google-charts#180]
# Bug Report

## Description
Tooltips are not displayed

## To reproduce
A very simple sample chart with 3 rows and 1 tooltip column :
https://angular-ivy-cbs51b.stackblitz.io
https://stackblitz.com/edit/angular-ivy-cbs51b?file=src/app/app.component.ts

## Expected behaviour
Custome Tooltip must be displayed, but instead default tooltip are used

## Exception or Error
No errors at all

## Your environment
Angular 10 / last version of angular-google-charts

**Comment by FERNman** [comment]
Hi @cyberbobjr,

Material Charts don't yet support custom tooltips - see [google/google-visualization-issues#2143](https://github.com/google/google-visualization-issues/issues/2143).
