### ISSUE TITLE
An accessor cannot be declared in an ambient context.

### ISSUE THREAD

**Issue by VadimKhismatov** [FERNman/angular-google-charts#181]
# Bug Report
## Description
After adding GoogleChartsModule to my module in angular app, I receive list of errors when compiling application. 

## To reproduce
Steps to reproduce the behaviour:
1. Install package
2. Import GoogleChartsModule to your module
3. Compile
4. See errors in terminal

## Error
<pre><code>
ERROR in node_modules/angular-google-charts/lib/components/chart-editor/chart-editor.component.d.ts(14,9): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/angular-google-charts/lib/components/chart-wrapper/chart-wrapper.component.d.ts(25,9): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/angular-google-charts/lib/components/chart-wrapper/chart-wrapper.component.d.ts(26,9): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/angular-google-charts/lib/components/chart-wrapper/chart-wrapper.component.d.ts(27,9): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/angular-google-charts/lib/components/chart-wrapper/chart-wrapper.component.d.ts(28,9): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/angular-google-charts/lib/components/control-wrapper/control-wrapper.component.d.ts(79,9): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/angular-google-charts/lib/components/control-wrapper/control-wrapper.component.d.ts(80,9): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/angular-google-charts/lib/components/google-chart/google-chart.component.d.ts(82,9): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/angular-google-charts/lib/components/google-chart/google-chart.component.d.ts(83,9): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/angular-google-charts/lib/components/google-chart/google-chart.component.d.ts(84,9): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/angular-google-charts/lib/components/google-chart/google-chart.component.d.ts(85,9): error TS1086: An accessor cannot be declared in an ambient context.

</code></pre>

## Your environment
<pre><code>
{
"dependencies": {
    "@angular/animations": "^6.1.9",
    "@angular/cdk": "~6.2.1",
    "@angular/common": "^6.1.9",
    "@angular/compiler": "^6.1.9",
    "@angular/core": "^6.1.9",
    "@angular/forms": "^6.1.9",
    "@angular/http": "^6.1.9",
    "@angular/material": "~6.2.1",
    "@angular/platform-browser": "^6.1.9",
    "@angular/platform-browser-dynamic": "^6.1.9",
    "@angular/platform-server": "^6.1.9",
    "@angular/router": "^6.1.9",
    "@angularclass/hmr": "~2.1.3",
    "angular-google-charts": "^1.1.6",
    "chart.js": "2.7.3",
    "core-js": "^2.4.1",
    "file-saver": "^2.0.2",
    "font-awesome": "^4.7.0",
    "hammerjs": "^2.0.8",
    "http-server": "^0.11.1",
    "ie-shim": "^0.1.0",
    "ng2-charts": "1.6.0",
    "ngx-autosize": "^1.6.4",
    "reflect-metadata": "^0.1.12",
    "rxjs": "^6.3.3",
    "rxjs-compat": "~6.2.2",
    "xlsx": "~0.14.0",
    "zone.js": "^0.8.26"
  },
  "devDependencies": {
    "@angular-devkit/build-optimizer": "^0.6.8",
    "@angular/cli": "^6.0.8",
    "@angular/compiler-cli": "^6.0.6",
    "@angular/flex-layout": "6.0.0-beta.18",
    "@angular/language-service": "^6.0.6",
    "@compodoc/compodoc": "^1.1.3",
    "@ngtools/webpack": "^6.0.8",
    "@types/hammerjs": "^2.0.35",
    "@types/jasmine": "^2.8.8",
    "@types/node": "^10.3.5",
    "@types/uglify-js": "^3.0.2",
    "@types/webpack": "^4.4.2",
    "add-asset-html-webpack-plugin": "^2.1.3",
    "angular2-template-loader": "^0.6.2",
    "assets-webpack-plugin": "^3.8.4",
    "awesome-typescript-loader": "^5.2.0",
    "codelyzer": "^4.3.0",
    "copy-webpack-plugin": "^4.5.1",
    "cross-env": "^5.2.0",
    "css-loader": "^0.28.11",
    "exports-loader": "^0.7.0",
    "expose-loader": "^0.7.5",
    "file-loader": "^1.1.11",
    "find-root": "^1.1.0",
    "gh-pages": "^1.2.0",
    "html-webpack-plugin": "^3.2.0",
    "imports-loader": "^0.8.0",
    "istanbul-instrumenter-loader": "^3.0.1",
    "jasmine-core": "^3.1.0",
    "json-loader": "^0.5.4",
    "karma": "^2.0.4",
    "karma-chrome-launcher": "^2.2.0",
    "karma-coverage": "^1.1.2",
    "karma-jasmine": "^1.1.2",
    "karma-mocha-reporter": "^2.2.5",
    "karma-remap-coverage": "^0.1.5",
    "karma-sourcemap-loader": "^0.3.7",
    "karma-webpack": "^3.0.0",
    "mini-css-extract-plugin": "^0.4.0",
    "ng-inline-svg": "2.0.0",
    "node-sass": "^4.9.0",
    "npm-run-all": "^4.1.3",
    "optimize-js-plugin": "^0.0.4",
    "parse5": "^5.0.0",
    "protractor": "^5.3.2",
    "raw-loader": "^0.5.1",
    "rimraf": "^2.6.2",
    "rxjs-tslint": "^0.1.5",
    "sass-loader": "^7.0.3",
    "script-ext-html-webpack-plugin": "^2.0.1",
    "source-map-loader": "^0.2.3",
    "string-replace-loader": "^2.1.1",
    "style-loader": "^0.21.0",
    "to-string-loader": "^1.1.5",
    "ts-node": "^7.0.0",
    "tslib": "^1.9.3",
    "tslint": "^5.10.0",
    "tslint-loader": "^3.6.0",
    "typedoc": "^0.11.1",
    "typescript": "~2.9.2",
    "uglifyjs-webpack-plugin": "^1.2.6",
    "url-loader": "^1.0.1",
    "webpack": "^4.12.0",
    "webpack-cli": "^3.0.8",
    "webpack-dev-middleware": "^3.1.3",
    "webpack-dev-server": "^3.1.4",
    "webpack-inline-manifest-plugin": "^4.0.1",
    "webpack-merge": "^4.1.3"
  },
}
</code></pre>

## Anything else?
Not using Angular CLI, Node 12.16.1. What can I do with this error ?

**Comment by cyberbobjr** [comment]
Hi,
i think your angular version is really too older, angular 9 introduce new compiler system and most packages are compatible only with 9+

**Comment by FERNman** [comment]
I actually think this library should be compatible with most versions of Angular, even as old as Angular 6. However, the Typescript version could be a problem. Please refer to [this StackOverflow question](https://stackoverflow.com/q/60092642/4471085) for more information.
