### ISSUE TITLE
In bar chart role not work for version above 1

### ISSUE THREAD

**Issue by diveshdobal** [FERNman/angular-google-charts#182]
I update package to latest version or 1.1.0. In my bar chart I use -

```ts
column =['Label', 'Value', { role: 'style' }]
Data= [['A', 0, '#f37037'], ['B', 1 0, '#34bfa3']]
```

It give me issue "All series on a given axis must be of the same data type".

**Comment by FERNman** [comment]
Hi @diveshdobal, I hope you already managed to resolve this problem. If the issue remains, feel free to add another comment with more information!
