### ISSUE TITLE
is it possible to express the width of the Chart as a percentage ?

### ISSUE THREAD

**Issue by frsab** [FERNman/angular-google-charts#186]
# Bug Report

## Prerequisites

Please answer the following questions for yourself before submitting an issue.
**YOU MAY DELETE THE PREREQUISITES SECTION.**

- [X ] I am running the latest version
- [X ] I checked the Readme and found no answer
- [X ] I checked to make sure that this issue has not already been filed
- [ X] This is related to angular-google-charts and not to Google Charts directly (if it's a Google Charts issue, [their forum](https://groups.google.com/forum/#!forum/google-visualization-api) may help)

## To reproduce
Steps to reproduce the behaviour:
1. Go to https://stackblitz.com/edit/angular-ivy-p2mz7g?file=src/app/app.component.ts'
Error in src/app/app.component.html (8:5)
Type 'string' is not assignable to type 'number'.
## Exception or Error
<pre><code>

</code></pre>

## Your environment
<pre><code>

</code></pre>

## Anything else?

https://stackblitz.com/edit/angular-ivy-p2mz7g?file=src/app/app.component.ts

**Comment by vajkri** [comment]
You can just use CSS for this. Like so:

In the HTML:
```
<google-chart class="google-chart" ...></google-chart>
```

In the CSS:
.google-chart {
    width: 80%;
}

The same goes for the height :)

**Comment by alekstrust** [comment]
I tried that but it is overflowing when using inside a ngIf. Works fine on first load but when hiding and showing again, the chart area gets bigger than expected. dynamicResize does not help either.

**Comment by FERNman** [comment]
Hi @alekstrust, I sadly don't think it is possible in all browsers yet to watch for div resize events. If you manage to find a solution though, feel free to add it here!
