### ISSUE TITLE
allow div, span, or table tags with dashboard controls and charts

### ISSUE THREAD

**Issue by kussmaul** [FERNman/angular-google-charts#191]
# Feature request

## Describe the solution you'd like
I would like more control of the layout and positioning of a dashboard's controls and charts. I tried to do this with existing HTML/CSS, but if I put div, span, or table elements around controls or charts, they vanish (although they still exist if I explore the DOM in the browser debugger.

## Describe alternatives you've considered
- There might be some way to do this with CSS (without div/span/table), but I am not an expert.
- I don't know if this issue is tied to the main Google Charts or the Angular wrapper.

## Additional context

For example, I might want to have several stacked controls, then a set of charts:
<pre>
| controlA |        |        |
|----------| chartC | chartD |
| controlB |        |        |

</pre>

**Comment by kussmaul** [comment]
found a way to do this with CSS:
<pre><code>
&lt;style>
  div.graphs              { height: 200px; }
  .graphs div,
  .graphs control-wrapper { float:  left; height:  25%; width: 40% }
  .graphs google-chart    { float: right; height: 100%; width: 25% }
&lt;/style>

&lt;div class="graphs"&gt;
  &lt;dashboard          [columns]="[ 'Response', 'Count' ]" [data]="data"&gt;
    &lt;div&gt;&lt;/div&gt;
    &lt;google-chart     #pChart type="PieChart"   [options]="opts" &gt;&lt;/google-chart&gt;
    &lt;google-chart     #bChart type="BarChart"   [options]="opts" &gt;&lt;/google-chart&gt;
    &lt;control-wrapper  [for]="[pChart, bChart]"  type="StringFilter"
                      [options]="{ filterColumnLabel : 'Response',  matchType : 'any' }"&gt;&lt;/control-wrapper&gt;
    &lt;control-wrapper  [for]="[pChart, bChart]"  type="NumberRangeFilter"
                      [options]="{ filterColumnLabel : 'Count',     minValue : 0      }"&gt;&lt;/control-wrapper&gt;
  &lt;/dashboard&gt;
&lt;/div&gt;
</code></pre>

**Comment by FERNman** [comment]
The solution provided seems good to me, I'll close this for now. If there's anything else you need help with feel free to comment here or open another issue!
