### ISSUE TITLE
PatternFormat doesn't work - wrong parameters

### ISSUE THREAD

**Issue by kussmaul** [FERNman/angular-google-charts#193]
# Bug Report

## Description
PatternFormat doesn't work, at least in part because it requires 3 params (not 2) when called in 
`google-chart.component.ts:applyFormatters()`

## To reproduce
1. Make a formatter using PatternFormat, e.g.:
<pre><code>
    this.formatters = [
      { colIndex : 1, formatter : new google.visualization.PatternFormat('TEST {1} TEST') },
     ];
</code></pre>
2. Use formatter in chart. e.g.:
<pre><code>
  &lt;google-chart type="Timeline" [dynamicResize]="true"
                [data]="data" [columns]="[ 'Team', 'Question', 'Start Time', 'End Time' ]"
                [options]="opts" [formatters]="formatters" &gt;&lt;/google-chart&gt;
</code></pre>
3. Load page.
4. See error.

## Exception or Error
<pre><code>
core.js:5967 ERROR Error: Invalid column index undefined.  Should be an integer in the range [0-3].
    at gvjs_tj (jsapi_compiled_default_module.js:213)
    at gvjs_G.gvjs_.Ha (jsapi_compiled_default_module.js:222)
    at jsapi_compiled_default_module.js:492
    at String.replace (<anonymous>)
    at gvjs_Go.format (jsapi_compiled_default_module.js:492)
    at GoogleChartComponent.applyFormatters (angular-google-charts.js:640)
    at GoogleChartComponent.createDataTable (angular-google-charts.js:607)
    at GoogleChartComponent.ngOnChanges (angular-google-charts.js:581)
    at GoogleChartComponent.rememberChangeHistoryAndInvokeOnChangesHook (core.js:1471)
    at callHook (core.js:2490)
</code></pre>

The code below appears to be the problem - most Formats have `format(table, index)` but `PatternFormat.format()` has 3 params (table, source indices, dest index)
<pre><code>
  private applyFormatters(dataTable: google.visualization.DataTable): void {
    if (this.formatters == null) {
      return;
    }
    for (const val of this.formatters) {
      val.formatter.format(dataTable, val.colIndex); // ERROR OCCURS HERE
    }
  }
</code></pre>

## Your environment
<pre><code>
Angular CLI: 11.0.4
Node: 10.16.3
OS: linux x64

Angular: 11.0.4
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: Yes

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1100.4
@angular-devkit/build-angular   0.1100.4
@angular-devkit/core            11.0.4
@angular-devkit/schematics      11.0.4
@angular/cdk                    11.0.2
@angular/material               11.0.2
@schematics/angular             11.0.4
@schematics/update              0.1100.4
rxjs                            6.6.3
typescript                      4.0.5
</code></pre>

**Comment by kussmaul** [comment]
I wrote a wrapper to adds the missing indices for my situation:
<pre><code>
    const wrapPatternFormat = (pattern : string) => {
      const pf = new google.visualization.PatternFormat(pattern);
      return  { format : (data : any, dest : number) => { pf.format(data, [0, 1, 2, 3], dest); } };
    }

    this.formatters = [
      { colIndex : 0, formatter : wrapPatternFormat('TEST {0} TEST') }, // NO ERROR
      { colIndex : 1, formatter : new google.visualization.PatternFormat('TEST {1} TEST') }, // ERROR
    ];
</code></pre>

**Comment by FERNman** [comment]
That's a great solution! If you want to, I'd be happy to accept a PR regarding the formatters, allowing them to be more generic.
For now, I will close this ticket - the solution you provided should work for many cases I hope 😃
