### ISSUE TITLE
Using formatters in dashboards

### ISSUE THREAD

**Issue by kussmaul** [FERNman/angular-google-charts#194]
# Bug Report

## Description
The `[formatters]` option works for a stand-alone `<google-chart>` but not within a `<dashboard>`.

(Please don't take these issues as complaints - I really like angular-google-charts.)

## To reproduce
1. Create charts with formatters within and outside a dashboard:
2. Check which charts run formatters - dashboard chart doesn't, standalone chart does.

<pre><code>
  &lt;dashboard  [data]="data" [columns]="[ 'Team', 'Question', 'Start Time', 'End Time' ]" class="timeline" &gt;
      &lt;control-wrapper  [for]="[tChart]" type="DateRangeFilter"&gt;&lt;/control-wrapper&gt;
      &lt;google-chart     #tChart type="Timeline" [dynamicResize]="true"
                        [options]="opts"
                        [formatters]="formatters">&lt;/google-chart&gt; &lt;!-- NOT USED --&gt;
  &lt;/dashboard&gt;
  &lt;google-chart     type="Timeline" [dynamicResize]="true"
                    [data]="data" [columns]="[ 'Team', 'Question', 'Start Time', 'End Time' ]"
                    [options]="opts"
                    [formatters]="formatters" >&lt;/google-chart&gt; &lt;!-- USED --&gt;
</code></pre>

## Expected behaviour
The `[formatters]` should work the same inside or outside a dashboard.

## Your environment
<pre><code>
Angular CLI: 11.0.4
Node: 10.16.3
OS: linux x64

Angular: 11.0.4
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: Yes

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1100.4
@angular-devkit/build-angular   0.1100.4
@angular-devkit/core            11.0.4
@angular-devkit/schematics      11.0.4
@angular/cdk                    11.0.2
@angular/material               11.0.2
@schematics/angular             11.0.4
@schematics/update              0.1100.4
rxjs                            6.6.3
typescript                      4.0.5
</code></pre>

**Comment by FERNman** [comment]
Hi @kussmaul, thanks for the detailed report! After thinking this through, I'm pretty sure it is not possible to reuse the `formatters` property from the charts themselves, but rather provide the same property for the `DashboardComponent`. What do you think, would this satisfy your requirements?

**Comment by kussmaul** [comment]
Hi @FERNman! Yes, I think `<dashboard [formatters]="..." >` would work for me. This also seems consistent with the `columns` and `data` properties. Thanks for making a bug into a feature. :-)

**Comment by kussmaul** [comment]
Hi @FERNman, any idea if or when you might add this feature?
If you don't think it will be anytime soon, any hints for me (or others) who might try to work on it?

**Comment by FERNman** [comment]
Hi @kussmaul, I will probably tackle this over the upcoming weekend. I already did some refactorings and hope that the final changes will be straight-forward.

**Comment by kussmaul** [comment]
See #208
