### ISSUE TITLE
(Question)How to re-render chart which use ScriptLoaderService

### ISSUE THREAD

**Issue by AndreHermanto** [FERNman/angular-google-charts#198]
Hi,

I'm having trouble to re-render Calendar chart which use ScriptLoaderService. When I try to re-render the chart it shows error `The chart type is not defined.`.

Below is the snippet of the code:

```
private readonly chartPackage2 = getPackageForChart(ChartType.Calendar);
@ViewChild('containerCalendar', { read: ElementRef })
private containerCalendar: ElementRef<HTMLElement>;

ngOnInit(): void {
this.loaderService.loadChartPackages(this.chartPackage).subscribe(() => {
      this.subscriptions.push(this.vas.getData().subscribe((e) => {
          this.chartData = this.convertToChartFormat(e);
          this.chartCols = this.convertToChartColumn(e);

          let ea = [this.chartCols].concat(this.chartData);

          this.mapData = google.visualization.arrayToDataTable(ea);

          this.mapOptions = {
            displayMode: 'markers',
            colorAxis: {colors: ['green', 'blue']}
            
          };
          this.mapChart = new google.visualization.GeoChart(this.containerEl.nativeElement);
          this.mapChart.draw(this.mapData, this.mapOptions);
      }));
    });
}
```
The chart will re-render based on checkbox
```
<div *ngIf="item.id === 'loginArea'">
  <span>Login area</span>
  <google-chart #containerEl style="width: 100%;"></google-chart>
</div>
```

**Comment by FERNman** [comment]
Hi @AndreHermanto,

Some parts of your code don't really add up - the definition of `this.chartPackage`, for example, is missing. Anyway, I think the problem is that you're using the `google-chart` component as a container and try to render the geo chart manually. That's not necessary using this library, instead, the `google-chart` component does everything for you (even loading the correct packages) if you provide the correct inputs. Going through the Readme again should help to resolve your problem!

**Comment by AndreHermanto** [comment]
hi @FERNman,

thank you for your response. I have used `google-chart` component to do everything. 

```
  chartData7=[];
  chartCols7=[];
  options7={
    width: 700,
    height: 300,
    calendar: {
      cellSize: 12
    }
  };
ngOnInit(): void {
this.vas.getData("date(timestamp) as day, count(timestamp) from USER_LOGIN group by day;").subscribe((e) => {
      let temp = this.convertToChartFormat(e);
      this.chartData7 = temp.map(e => {
        e[0] = new Date(e[0])
        return e;
      })
      this.chartCols7 = this.convertToChartColumn(e);
    })
}
```

Then I use the component as follows: 

```
<div *ngIf="item.id === 'loginChart'">
    <span>Login</span>
    <google-chart [type]="'Calendar'" [columns]='chartCols7' [data]='chartData7' [options]="options7"></google-chart>
</div>
```

Its fine the first time it renders, but when I try to interact to hide/show the chart. It will fail to re-render the calendar chart and the whole site freeze. I'm not sure if this is Google chart issue or angular-google-charts issue. Re-rendering chart works fine for other charts

I recorded the behaviour as follows: https://recordit.co/h2mVsDW2nh. Any help would be appreciated. 

Thank you very much

**Comment by FERNman** [comment]
Hi @AndreHermanto,

can you reproduce the issue in some way I can also access the code? Seems like an actual bug to me, however, I don't know why this happens. Are there any error messages in the console?
