### ISSUE TITLE
does dynamic resize works for dashboard?

### ISSUE THREAD

**Issue by AndreHermanto** [FERNman/angular-google-charts#205]
Hi,

```                
<dashboard *ngIf="visibleDelayed[item.id]" [columns]="cohortSearchCols" [data]="cohortSearchData" style="height: 100%;width: 100%;" [dynamicResize]="true">
  <control-wrapper [for]="[dashboardChart,dashboardCharts]" [type]="controlFilterType" [options]="controlOptions">
       <google-chart #dashboardChart type="ColumnChart" style="height: 50%;width: 100%;" [options]="cohortSearchOptions"></google-chart>
       <google-chart #dashboardCharts type="PieChart" style="height: 50%;width: 100%;" [options]="cohortSearchOptions"></google-chart>
  </control-wrapper>
</dashboard>
```

Its a straightforward question, does dashboard support dynamicResize? I tried with following code but the chart doesn't re-render when window resize.

Thanks

**Comment by kussmaul** [comment]
Hi @AndreHermanto,
I don't see `dynamicResize` in your code, so I'm not clear how you're trying to use it.
Looking at the angular-google-charts source code, `dynamicResize` looks like an option for `<google-chart>` not `<dashboard>`, so you would apply it to each chart, not the dashboard. (This works for me.)

**Comment by AndreHermanto** [comment]
Thanks, your solution works.
