### ISSUE TITLE
How to open/fork angular-google-charts in StackBlitz

### ISSUE THREAD

**Issue by kussmaul** [FERNman/angular-google-charts#206]
# Bug Report

## Description
I can't fork/open and run angular-google-charts in StackBlitz. I have minimal experience with StackBlitz, so maybe this is simple. :-)

## To reproduce
1. Go to stackblitz.com, click "New Project" (top right corner).
2. In new project, click "Connect repository" (top left corner).
3. In dialog, click "import an existing repository" and enter url: https://github.com/FERNman/angular-google-charts (or my new fork, https://github.com/kussmaul/angular-google-charts)
4. Observe errors in browser:

        Import error, can't find files:
        /src/index.html
        /src/polyfills.ts
        /src/main.ts
        /src/styles.css

5. In angular.json, notice that these paths exist for "Playground". In Settings, change "Default Project" from "angular-google-charts" to "playground". (not sure if this is correct)
6. Observe errors in browser:

        Import error, can't find files:
        /apps/playground/apps/playground/src/index.html
        /apps/playground/apps/playground/src/polyfills.ts
        /apps/playground/apps/playground/src/main.ts
        /apps/playground/apps/playground/src/styles.scss

8. In angular.json, notice that "apps/playground" appears in "root" _and_ in paths, so remove "apps/playground" from paths for index, main, polyfills, main, and styles.
10. Observe error in browser:

        Can't find package: angular-google-charts

11. If I click "Install Package", the app loads successfully, but Stackblitz is using the package, not the repository.
12. Here is the resulting Stackblitz: https://stackblitz.com/edit/angular-ivy-vxm1ln?file=angular.json

**Comment by kussmaul** [comment]
could be a StackBlitz limitation, since it seems related to:
https://github.com/stackblitz/core/issues/220
https://github.com/stackblitz/core/issues/530 (closed, refers to 220)
https://github.com/stackblitz/core/issues/533 (closed, refers to 220)

**Comment by FERNman** [comment]
After going over the issues, I suppose what you observed is related to them and not a problem with the config. 

If someone still manages to "fix" the config in a way so that it's working similarly to how it currently does but allows forking the repository on Stackblitz, I'd be happy to accept a PR!
