### ISSUE TITLE
Legends Not showing text provided in ColumnNames.

### ISSUE THREAD

**Issue by viralsanghavi** [FERNman/angular-google-charts#209]
Hi, I want to pass columnNames which generate the legends.
Below is the code the line chart I am using and columnNames Passed
type = 'LineChart';
  dynamicResize = true;
  columnNames = ['Date', 'Asd', 'Jane', 'Jone', 'Average'];
  width = '100%';
  height = '100%';
  options = {
    pointSize: 5,
    chartArea: {
      width: '70%',
      height: '80%',
      borderLeft: '2px solid',
    },
    hAxis: {
      scaleType: 'date',
      textStyle: {
        fontSize: 10,
      },
    },
    vAxis: {
      minValue: 0,
    },
    legend: {
      position: 'right',
      maxLines: 3,
      alignment: 'center',

    },
  };

  data = [
    [new Date(2021, 7, 30), 20.0, 20.2, 90, 30.9],
    [new Date(2021, 7, 20), 67.9, 30.8, 10.6, 40.2],
    [new Date(2021, 7, 10), 90.5, 50.7, 30.5, 50.7],
    [new Date(2021, 7, 2), 10.5, 10.3, 80.4, 80.5],
  ]

Following is the output I get.
![code](https://user-images.githubusercontent.com/54470601/109786226-f674f080-7c32-11eb-9451-3212625d9d59.png)
Expected: The column Names to be displayed as the text of legends

**Comment by kussmaul** [comment]
You've shown data and options, but not the actual code calling angular-google-charts - could you share a stackblitz with your code, like this:
https://stackblitz.com/edit/angular-ivy-ur6j7n

Your chartArea width might be too big, not leaving enough space for legend texts.

**Comment by viralsanghavi** [comment]
```
<google-chart
  #chart
  style="width: 100%"
  [type]="type"
  [data]="data"
  [options]="options"
  [height]="height"
  [dynamicResize]="dynamicResize"
  [width]="width"
  [columnNames]="columnNames"
>
</google-chart>

```
Hi This is where I am calling angular-google-charts

**Comment by viralsanghavi** [comment]
Hi, I figured that columnNames Is to be used as columns worked for me.
Thanks 😄
