### ISSUE TITLE
Regarding Type 'string' is not assignable to type 'ChartType'

### ISSUE THREAD

**Issue by aditmehta9** [FERNman/angular-google-charts#210]
# Bug Report

## Prerequisites

Please answer the following questions for yourself before submitting an issue.
**YOU MAY DELETE THE PREREQUISITES SECTION.**

- [ ] I am running the latest version
- [ ] I checked the Readme and found no answer
- [ ] I checked to make sure that this issue has not already been filed
- [ ] This is related to angular-google-charts and not to Google Charts directly (if it's a Google Charts issue, [their forum](https://groups.google.com/forum/#!forum/google-visualization-api) may help)

## Description
Error: src/app/components/home/home.component.html:47:22 - error TS2322: Type 'string' is not assignable to type 'ChartType'.

47       <google-chart [type]='chart.PieChart' [options]='chart.options' style="width: 100%;" [height]='chart.height'
                        ~~~~

  src/app/components/home/home.component.ts:7:16
    7   templateUrl: './home.component.html',
                     ~~~~~~~~~~~~~~~~~~~~~~~
    Error occurs in the template of component HomeComponent.

Error: src/app/components/home/home.component.html:51:22 - error TS2322: Type 'string' is not assignable to type 'ChartType'.

51       <google-chart [type]='chart.ColumnChart' style="width: 100%;" [options]='chart.options' [height]='chart.height'
                        ~~~~

  src/app/components/home/home.component.ts:7:16
    7   templateUrl: './home.component.html',
                     ~~~~~~~~~~~~~~~~~~~~~~~
    Error occurs in the template of component HomeComponent.

## To reproduce
Below is the code where error is occurring:
homecomponent.ts file code:
export class HomeComponent implements OnInit {

  totalConfirmed = 0;
  totalActive = 0;
  totalDeaths = 0;
  totalRecovered = 0;
  loading = true;
  globalData: GlobalDataSummary[]=[];
  datatable :any= [];
  chart = {
    PieChart : "PieChart" ,
    ColumnChart : 'ColumnChart' ,
    LineChart : 'LineChart', 
    height: 500, 
    options: {
      animation:{
        duration: 1000,
        easing: 'out',
      },
      is3D: true
    }

  }
  
.....
---------------------------------------
homecomponent.html file last lines code where error is occurring
<google-chart [type]='chart.PieChart' [options]='chart.options' style="width: 100%;" [height]='chart.height'
        [data]='datatable'></google-chart>
    </div>
    <div class="col">
      <google-chart [type]='chart.ColumnChart' style="width: 100%;" [options]='chart.options' [height]='chart.height'
        [data]='datatable'></google-chart>
    </div>

## Expected behaviour
Type should be assigned directly but it is not.

## Your environment
<pre><code>
Angular CLI: 11.2.3
Node: 12.21.0
OS: linux x64

</code></pre>

**Comment by kussmaul** [comment]
If the type is fixed, I set it directly (no brackets):
`<google-chart type="WordTree" [options]="info.opts"></google-chart>`

If the type is dynamic, I use a ChartType enum, not a string:
`import { ChartType, Row } from "angular-google-charts";`
`myType = ChartType.OrgChart;`
and then
`<google-chart [type]='myType' ... >`

**Comment by aditmehta9** [comment]
Thanks it worked sorry for the silly issue.

**Comment by PriyankaMali-13** [comment]
Hello I am getting this error even if I changed to this 
import { ChartType, Row } from "angular-google-charts";
myType = ChartType.OrgChart;
and then
<google-chart [type]='myType' ... >


Column 1 must be of type string×
