### ISSUE TITLE
google-charts not loading when angular build is done using buildOptimizer=true

### ISSUE THREAD

**Issue by jatin10269** [FERNman/angular-google-charts#214]

**Comment by FERNman** [comment]
Hi @jatin10269, if you want me to be able to help you, please provide additional information and a reproduction.

**Comment by jatin10269** [comment]
Hi @FERNman, 
So it works fine for the normal build on my local,  but for test and prod environments we build using the below configuration where buildOptimizer is set to true which seems to not load the chart. If I set it to false and build it works. Any ideas for resolution on this?
  "hm-test": {
              "outputPath": "dist",
              "stylePreprocessorOptions": {
              },
              "optimization": true,
              "outputHashing": "none",
              "sourceMap": false,
              "extractCss": true,
              "namedChunks": true,
              "aot": true,
              "extractLicenses": true,
              "vendorChunk": false,
              **"buildOptimizer": true,**


I am using the  "angular-google-charts": "1.1.4"  did the import { GoogleChartsModule } from 'angular-google-charts'; into my module and used below in html :
 <google-chart #chart
      [title]="title"
      [type]="type"
      [data]="data"
      [columns]="columnNames"
      [options]="options"
      [width]="width"
      [height]="height"
      [dynamicResize]="dynamicResize" style="width: 100%;">
    </google-chart>

**Comment by FERNman** [comment]
Could you upgrade to the latest version of angular-google-charts (2.0.1) and try again?

**Comment by jatin10269** [comment]
@FERNman this worked with the latest version. Thanks for the help!!
