### ISSUE TITLE
failed to load google charts script

### ISSUE THREAD

**Issue by adamscottv** [FERNman/angular-google-charts#217]
I'm using version 2.0.1, and I get this error from angular-google-charts.js line 122. It's trying to access gstatic.com to load the script, but that URL cannot be accessed from my environment. Is there a way to load this as an npm dependency?

**Comment by FERNman** [comment]
I don't think loading Google Charts from NPM is possible. If it is and Google Charts themselves claim it is a valid option, I'd be happy to accept a PR.

**Comment by FXLima** [comment]
Hi could you help me.
I'm getting the error: ERROR TypeError: "c is undefined":

> ERROR TypeError: c is undefined
>     zc https://www.gstatic.com/charts/loader.js:147
>     zc https://www.gstatic.com/charts/loader.js:147
>     Ec https://www.gstatic.com/charts/loader.js:149
>     load https://www.gstatic.com/charts/loader.js:150
>     loadChartPackages http://localhost:4200/main.js:5

https://stackoverflow.com/questions/68702683/google-charts-error-typeerror-c-is-undefined
