### ISSUE TITLE
Attempting to load Google Charts package multiple times

### ISSUE THREAD

**Issue by AlmaniaM** [FERNman/angular-google-charts#220]
# Bug Report

- [x] I am running the latest version
- [x] I checked the Readme and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] This is related to angular-google-charts and not to Google Charts directly (if it's a Google Charts issue, [their forum](https://groups.google.com/forum/#!forum/google-visualization-api) may help)

## Description
The script loader is called every time a chart is created and it's throwing a warning that a version of the chart is being loaded when one already exists in the following image.
![image](https://user-images.githubusercontent.com/8919797/114789134-7795cc00-9d37-11eb-832b-542e9db698d6.png)

## To reproduce
I just ran the angular-charts-playground demo and you'll get these warnings. I'm having the same issue on our site at work.

**Comment by FERNman** [comment]
Ah, that makes sense. I was actually always wondering why this warning appears.
Do you think we can fix this? We have to call `google.charts.load` multiple times (and that's a [valid thing to do](https://developers.google.com/chart/interactive/docs/basic_load_libs#basic-library-loading)) to load additional packages.

**Comment by AlmaniaM** [comment]
@FERNman After looking into this a little further, it appears that the `ChartWrapper` always loads the laters minor version of the provided chart version. I'm thinking this is intentional and not really sure what we can do about it. To remove the warning you just have to provide the exact version to the charts such as `46.2`. Going to close the issue as I don't believe Google Charts will do anything to change this.
