### ISSUE TITLE
How to change layout of control-wrapper in Dashboard

### ISSUE THREAD

**Issue by viniciostorres** [FERNman/angular-google-charts#223]
# Layout of control-wrapper in Dashboard

## We need control the width and height of control-wrapper

I use this structure:

```
    <dashboard
       [columns]="columns"
       [data]="temperatures">

      <google-chart #myChart
        [type]="chartType"
        [options]="chart.options"
      ></google-chart>

      <control-wrapper
        [for]="myChart"
        [type]="filterType"
        [options]="control.options"
        [state]="control.state"
      ></control-wrapper>
      
    </dashboard>
```

The type of graphs are:

```
  public filterType = FilterType.ChartRange;
  public chartType = ChartType.ComboChart;
```

And gets this result:

![Captura de tela_2021-04-20_22-30-17](https://user-images.githubusercontent.com/1395631/115484369-184d2580-a229-11eb-9607-dfb4717950d9.png)

My desire is the control-wrapper have the same width of the chart and I want to apply other styles too, controlling margins and colors.
But I can't discover how to do that with this component.

My initial inspiration is the example of ChartRangeFilter on the [Google Chart manual](https://developers.google.com/chart/interactive/docs/gallery/controls#chartrangefilter):

![gcm](https://user-images.githubusercontent.com/1395631/115484987-310a0b00-a22a-11eb-8d88-8b6071bbba56.png)

How can I do that?

Thanks in advance.

Vinicios

**Comment by FERNman** [comment]
Hi @viniciostorres ,

how do you set the width of the chart? Did you try using CSS?

**Comment by viniciostorres** [comment]
Hi, @FERNman 

The structure of my component is:

<div fxFlex fxLayout="column" fxLayoutAlign="flex-start">
  <dashboard ....
  <google-chart #myChart ...
  <control-wrapper ...
</div>

The flexbox sets the width and the chart expands to right width. But the control-wrapper doesn't do it. It has always dimension 400x18.

I tried to use css many ways, but the divs generated by google-chart dont have Id or class  and css applied to <ggogle-chart> or <control-wrapper> don't make effects.

**Comment by viniciostorres** [comment]
Hi,

I discovered that just now.
The same code generates this in Firefox:

![firefox](https://user-images.githubusercontent.com/1395631/115757010-b7caff00-a374-11eb-98db-7141bb0417e9.png)

And this in Chrome:

![chrome](https://user-images.githubusercontent.com/1395631/115757199-c31e2a80-a374-11eb-898d-175bba0e5bde.png)

**Comment by viniciostorres** [comment]
Hi,

After a long fight I found a solution:  I must to put 'display: inline-block' in the tags. After that, dimensions has effect over the elements.

```
.dashboard    { height: 380px; width: 100%; display: inline-block;}
.google-chart    { height: 350px; width:100%; display: inline-block;}
.control-wrapper  { height:  50px; width:100%; display: inline-block;}
```

**Comment by FERNman** [comment]
Hi @viniciostorres,

happy to hear you found a solution! Is this issue therefore resolved?

**Comment by viniciostorres** [comment]
Yes. Thanks for your attention
