### ISSUE TITLE
Title does not work with Material charts

### ISSUE THREAD

**Issue by gantispam** [FERNman/angular-google-charts#224]
# Bug Report

## Prerequisites
* "angular-google-charts": "^2.2.0"
* "@angular/core": "10.0.0"

## Description
According with documentation and all closed tickets on this subject : some properties not work (see exemple)

## To reproduce
* Template
```
<google-chart
                    class="w-100"
                    [title]="chart.title"
                    [type]="chart.type"
                    [data]="chart.data"
                    [columns]="chart.columns"
                    [options]="chart.options"
                >
                </google-chart>
```
* Component :
```
chart: { title: string, type: ChartType, data: Row[], columns: Column[], options: object } = {
    type: ChartType.Bar,
    title: 'My title not work',
    data: [
      ['London', 8136000, 8136000],
      ['New York', 8538000, 8136000],
      ['Paris', 2244000, 8136000],
      ['Berlin', 3470000, 8136000],
      ['Kairo', 19500000, 8136000],
    ],
    columns: ['City', 'Inhabitants', 'other'],
    options: {
      legend: { position: 'top', maxLines: 3 },
    }
  };
```
* Result :
![image](https://user-images.githubusercontent.com/15685552/116518093-1e4da100-a8d0-11eb-97c7-3755e581b0c7.png)

## Bugs
* Property "title" : not work
* Property "options.legend" : not work (only legend: { position: 'none' } seen to be work)

**Comment by FERNman** [comment]
Hi @gantispam,

thanks for reporting this. The reason why it's not working is that you're using a material bar chart, which doesn't support the options in the same way as other charts. Please provide the `title` and all other config options using the `config` property directly. For more information, see [the official documentation](https://developers.google.com/chart/interactive/docs/gallery/barchart#creating-material-bar-charts).

I don't know if it makes sense to create a "hack" to support material charts as well, I'll leave this open and think about it.
