### ISSUE TITLE
Geochart does not render region colors or color axis

### ISSUE THREAD

**Issue by musabhusaini** [FERNman/angular-google-charts#236]
# Bug Report

## Prerequisites

- [x] I am running the latest version
- [x] I checked the Readme and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] This is related to angular-google-charts and not to Google Charts directly (if it's a Google Charts issue, [their forum](https://groups.google.com/forum/#!forum/google-visualization-api) may help)

## Description

I am trying to recreate [this chart](https://developers.google.com/chart/interactive/docs/gallery/geochart#coloring-your-chart) from the official documentation. However, none of the colors get rendered and the color axis legend does not display at all.

## To reproduce

Steps to reproduce the behaviour:

Try to recreate any GeoChart from the official documentation. See this [StackBlitz](https://stackblitz.com/edit/angular-ivy-rkm8of?file=src/app/app.component.ts) for a minimal reproduction. You will need to add an API key in `app.module.ts`.

## Expected behaviour

Expected the chart to render with correct colors and axis legend.

![image](https://user-images.githubusercontent.com/579203/120495850-be15b780-c3c5-11eb-8406-3b9706ce6d34.png)

## Exception or Error

![image](https://user-images.githubusercontent.com/579203/120494728-bbff2900-c3c4-11eb-944a-4079f7e35d88.png)

## Your environment

<pre><code>
Angular CLI: 12.0.1
Node: 14.17.0
Package Manager: npm 6.14.13
OS: linux x64

Angular: 12.0.1
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1200.1
@angular-devkit/build-angular   12.0.1
@angular-devkit/core            12.0.1
@angular-devkit/schematics      12.0.1
@schematics/angular             12.0.1
rxjs                            6.6.7
typescript                      4.2.4
</code></pre>

Also tried on version `11.2.14` as in the StackBlitz link.

**Comment by chiragvels** [comment]
Hi,

Also there is no Options working.

I tried this
`region: 'US',
      colorAxis: { colors:['#b2dbee','#2c8dc4'] },
      displayMode: 'auto',
      keepAspectRatio: true,`

But no effect on Geo chart.

**Comment by BazylPL** [comment]
How do you run it on Angular 12 when angular-google-charts doesn't support it?

**Comment by chiragvels** [comment]
@BazylPL You can see the example at [StackBlitz](https://stackblitz.com/edit/angular-ivy-rkm8of?file=src/app/app.component.ts) for a minimal reproduction created by @musabhusaini .

Thanks,

**Comment by musabhusaini** [comment]
@BazylPL, the StackBlitz uses Angular 11 and exhibits the same problem. I just don't have the full version output for it, so I provided the one that I tried locally.

**Comment by FERNman** [comment]
So I had a brief look at the StackBlitz repo (thanks a lot for providing it!), and the problem is that you provided the columns in the data. It works right away if you change the code in the `app.component.ts` to

```ts
@Component({
  selector: 'my-app',
  templateUrl: './app.component.html',
  styleUrls: [ './app.component.css' ]
})
export class AppComponent  {
  chartType: ChartType = ChartType.GeoChart;
  columns = ['Country',   'Latitude'];
  chartData = [
    ['Algeria', 36],
    ['Angola', -8],
    ['Benin', 6],
    ['Botswana', -24],
    //...
}
```

and in the HTML

```html
<google-chart [type]="chartType" [columns]="columns" [data]="chartData" [options]="chartOptions"></google-chart>
```

I hope this helps to resolve the issue!

**Comment by chiragvels** [comment]
hi @FERNman ,

Question is about color axis.

I think color axis still be an issue with this. Color axis is not rendering colors.
https://developers.google.com/chart/interactive/docs/gallery/geochart#configuration-options

Thanks,

**Comment by FERNman** [comment]
You don't have to load the packages by yourself, that should be done automatically by the `GoogleChartsComponent`. The maps API key can be passed wherever you import Angular Google Charts for the first time, this can be your `AppModule` or any other module.

**Comment by chiragvels** [comment]
Hi @FERNman ,

No it is not taking mapsAPIKey from individual module unless I passed it through `app.module.ts`
I am using like this in `testing.module.ts`
```

import { NgModule } from '@angular/core';
import { BrowserModule } from '@angular/platform-browser';
import { FormsModule } from '@angular/forms';
import { GoogleChartsModule } from 'angular-google-charts';
import { HttpClientModule, HTTP_INTERCEPTORS } from '@angular/common/http';
import { environment } from '../environments/environment';

@NgModule({
declarations: [
   //Something here
  ],
  imports: [
    BrowserModule,
    FormsModule,
    GoogleChartsModule.forRoot({ mapsApiKey: environment.mapsApiKey, version: '50' }),
  ],
  providers:[
    //something here
  ]
})
export class TestingModule { }

```

**Comment by FERNman** [comment]
What happens in this case? Is the `TestingModule` the only module where you're importing the `GoogleChartsModule`?

**Comment by chiragvels** [comment]
Hi,

In this case when I get console error which is suggesting no key is passed. I also checked with google map key validation extension for chrome. When I passed it through app.module.ts it works and passed the check as well.
Yes. Currently it’s the only module where I have imported GoogleChartsModule.

**Comment by FERNman** [comment]
Hi @chiragvels,

could you create a new issue containing a reproduction for your problem? It's not related to this issue at all. Thanks!
