### ISSUE TITLE
Support extra load parameters

### ISSUE THREAD

**Issue by mii-pabortdom** [FERNman/angular-google-charts#237]
# How could we do the equivalent of this:

    google.charts.load('current', {
       'packages': ['geochart'],
       // Note: you will need to get a mapsApiKey for your project.
       // See: https://developers.google.com/chart/interactive/docs/basic_load_libs#load-settings
       'mapsApiKey': '<your key here>'
     });

Please update the README to show how. It is not clear.

**Comment by mii-pabortdom** [comment]
Never mind, I figured it out reading the source code. I've created a pull request to improve the README.

**Comment by chiragvels** [comment]
Can you please small snippet how I can set?
