### ISSUE TITLE
Namespace 'google.visualization' has no exported object 'errors' 

### ISSUE THREAD

**Issue by krishnasoft21** [FERNman/angular-google-charts#239]
I need to customize/remove the chart error messages like - 'Not enough columns given to draw the requested chart.' and 'Table has no columns'. I'm trying to catch the error event object and tried  `google.visualization.errors.removeError(err.id) `method to remove the error from displaying, but webpack compiler errors out as the 'errors' object is not found in google.visualization namespace. Any help ?

**Comment by FERNman** [comment]
Hi @krishnasoft21,

I suppose this is a problem with the typings in `@types/google.visualization`. If the method should exist, I advise you to cast as `any` or to add your own typings.
