### ISSUE TITLE
DataTable from Google spreadsheet URL

### ISSUE THREAD

**Issue by pliski** [FERNman/angular-google-charts#243]
# Feature request

## Be able to load datas from a google spreadsheet.

As described on https://developers.google.com/chart/interactive/docs/spreadsheets , it is possible to load data for a chart directly from a google spreadsheet.

## Additional context

For lack of time I already implemented the feature in my fork: https://github.com/pliski/angular-google-charts.git.

My apologies for not starting the discussion before; in case you find that my implementation could be useful fell free to ask for modification and a PR.

![2021-07-07_13-29](https://user-images.githubusercontent.com/6731247/124751965-88fe0700-df27-11eb-9861-9c1c011f79bb.png)

**Comment by FERNman** [comment]
This is supported through the `ChartWrapper` component. What's to be done is to add a section to the `README` that explains how to use it.
