### ISSUE TITLE
in lib/types/chart-type.ts, ChartType.WordTree should be 'WordTree' not 'wordtree'

### ISSUE THREAD

**Issue by kussmaul** [FERNman/angular-google-charts#248]
# Bug Report

## Description

[`lib/types/chart-type.ts`](https://github.com/FERNman/angular-google-charts/blob/master/libs/angular-google-charts/src/lib/types/chart-type.ts) defines `enum ChartType`. The last enum value is `WordTree = 'wordtree'` but should be `WordTree = 'WordTree'`.

## To reproduce

1. Visit [this StackBlitz](https://stackblitz.com/edit/angular-ivy-ur6j7n)
1. Open `app.component.ts`, which declares data used in sample charts. 
1. `wType=ChartType.WordTree;` produces an error: `Invalid visualization type: wordtree`
1. `wType = "WordTree" as ChartType;` is a wordaround that shows the wordtree.

**Comment by kussmaul** [comment]
FYI - I found this while trying to debug another problem. WordTree worked fine for me (in Jan 2021), and then at some later point (not sure when) it stopped working. I don't **think** I changed anything (but it's certainly possible). Now I get a "TypeError : c is undefined" after `ScriptLoaderService.loadChartPackages()` calls `https://www.gstatic.com/charts/loader.js`.

I'm not sure if these problems are related, but the `ChartType.WordTree` problem might cause problems for `getPackageForChart()`, which could cause other problems.

**Comment by kussmaul** [comment]
I updated the StackBlitz to angular-google-charts 2.2.2, and now it also gives the error "c is undefined".
Should I open this as a separate issue?

**Comment by ramitvakil** [comment]
Hi,
Any update on the issue ? Anyone working on this? After I tried the workaround provided by @kussmaul  it gives me the below error.  
![image](https://user-images.githubusercontent.com/3701777/160239274-02c145e1-22ba-4b75-87fe-454fc4cca8e5.png)

@FERNman Please if you could look into the issue?

**Comment by kussmaul** [comment]
FYI - in 2.1.0, `'WordTree' as ChartType` works. However, in 2.1.1, I get `c is undefined`.
Looking at [the difference](https://github.com/FERNman/angular-google-charts/compare/v2.1.0...v2.1.1), I suspect the problem is that `chart.helper.ts:ChartTypesToPackages` uses the (wrong) `ChartType.WordTree`.
