### ISSUE TITLE
Uncaught TypeError : _angular_core__WEBPACK_IMPORTED_MODULE_1__.ɵɵdefineInjectable

### ISSUE THREAD

**Issue by dhruvlatitude** [FERNman/angular-google-charts#251]
# Bug Report

Uncaught TypeError: _angular_core__WEBPACK_IMPORTED_MODULE_1__.ɵɵdefineInjectable is not a function
    at Module../node_modules/angular-google-charts/fesm2015/angular-google-charts.js

I am getting this while setting project in new system. it has angular 10 and project has 7.3.7 with same angular material version.

**Comment by caseyjfer** [comment]
I also see this precise error. Specifically on line 300

Angular 7.2, angular-google-charts v2.2.2
