### ISSUE TITLE
Updating peer dependences of @angular/common from 12.x.x to 13.x.x

### ISSUE THREAD

**Issue by siddhant-dev** [FERNman/angular-google-charts#252]
The current peer dependences are : 
 "peerDependencies": {
    "@angular/common": ">=6.0.0 <=12.x.x",
    "@angular/core": ">=6.0.0 <=12.x.x"
  },

Please updated them to 
 "peerDependencies": {
    "@angular/common": ">=6.0.0 <=13.x.x",
    "@angular/core": ">=6.0.0 <=13.x.x"
  },

**Comment by BazylPL** [comment]
@FERNman are you planning to support angular 13 in the near future?

**Comment by milenkovicstefan** [comment]
@FERNman it would be great if you support angular 13

**Comment by claimrevolution** [comment]
I was hoping to use this too, but can't find an alternative for 13, anybody have examples?

**Comment by FERNman** [comment]
I've finally released a new version including support for up to Angular 14. I hope it works for everyone!
