### ISSUE TITLE
Cannot format label, options just partly works, no google variable

### ISSUE THREAD

**Issue by cncDAni2** [FERNman/angular-google-charts#253]
Hi,

Wanted to draw a simple line graph: x axis time; y axis numeric value.
The graph appear, but the time value on the label is only seconds, like ":15 ... :16", so I want to format it. 
For that, I use the `[options]="myOptions"` attribute, where I can say `{ vAxis: { format: '...' } }`
Problem is, that this is TOTALLY ignored. No matter if I format v or h axis, no matter what value I write - simply nothing happens at all.
I tried the same with the pure JS library, and everything works fine.

I wanted to use similar than in the "formatter" section the readme: `new google.visualization.DateFormat({ formatType: 'long' })`
..but there is no "google" global variable. After I included the loader.js from gstatic, the variable become available, but there was no "visualization" object inside. For that, I need to wait for something.. unknow... no word about that in this readme; but ~1 second, it appears.
_By the way: "Formatters" works for tooltips, it really do something!_

...also in my early stages, other options was bad as well, but I thought the problem was with me, and I use something bad; but now I think it's just simple not supported.

Angular 12, clean project, with only angular-google-charts dependency.

**Comment by wauwau0977** [comment]
Same on Angular 13 with regular formatters

**Comment by FERNman** [comment]
I'm not entirely sure if I understand this correctly, but I assume it has to do with how we're loading the Google Charts script in the background. I'd recommend subscribing to the `ScriptLoaderService` and waiting for it to finish.
