### ISSUE TITLE
GeoChart while in Lazy Loading

### ISSUE THREAD

**Issue by vitmfs** [FERNman/angular-google-charts#255]
Hello, my name is Vítor and I am a developer from Portugal. I have been trying for days to get the GeoChart working in a lazy loaded environment. I tried both options listed (1 and 2), both in my app and in a simple example, and I keep getting the error that the api key is non existent. If I load the GeoChart in a eagerly loaded environment it works fine. Can you please direct me to an lazy loaded example that is already working? It is probably one detail that I am missing, and I really did not want to bother you, but I am without ideas at this point. Thanks in advance and best wishes from Portugal.

Vítor Silva
<img width="837" alt="api_error" src="https://user-images.githubusercontent.com/32262103/144866023-f4b9e93c-611d-48f8-9a6c-dd4816f0e8a6.png">

**Comment by AlmaniaM** [comment]
Hi @vitmfs,

Can you post some example code of your API key provider?

**Comment by FERNman** [comment]
Sorry for not answering for so long, I hope you managed to resolve the issue back then!
