### ISSUE TITLE
Publish an Ivy Distribution

### ISSUE THREAD

**Issue by lacroixdavid1** [FERNman/angular-google-charts#257]
When running `ng serve` I get this:

```
⠙ Generating browser application bundles (phase: setup)...Processing legacy "View Engine" libraries:
- angular-google-charts [es2015/esm2015] (https://github.com/FERNman/angular-google-charts)
Encourage the library authors to publish an Ivy distribution.
```

My general understanding is that "View Engine" is deprecated and will eventually be removed and "Ivy" is the new next-level Angular compiler/packager. So I'm opening this issue to encourage you folks to publish an Ivy distribution of `angular-google-charts` :slightly_smiling_face: 

More info:
https://angular.io/guide/creating-libraries
https://blog.angular.io/upcoming-improvements-to-angular-library-distribution-76c02f782aa4
https://dev.to/this-is-angular/the-angular-ivy-guide-for-library-authors-9md

**Comment by FERNman** [comment]
The next release that'll support Angular 16+ will be built with Ivy. Sorry for taking so long!
