### ISSUE TITLE
Annotation Chart- Zoom option not working with angular

### ISSUE THREAD

**Issue by gp-birender** [FERNman/angular-google-charts#264]
Annotation Chart- Zoom not working with angular
https://www.npmjs.com/package/angular-google-charts

` <google-chart
            #chart
            [title]="title + '(Annotation Chart)'"
            [type]="annotationChart"
            [data]="annotationChartData"
            [options]="annotationOptions"
            [width]="annotationWidth"
            [height]="annotationHeight"
          >
          </google-chart>`
![123](https://user-images.githubusercontent.com/33862424/161265759-5ccabe31-f56d-4962-8b28-c8e6251555c5.png)

**Comment by FERNman** [comment]
I'm pretty sure that's an issue with Google Charts. If not, please explain a little further what would need to be done in order to incorporate this in this package 🙂
