### ISSUE TITLE
Waterfall chart is not working.

### ISSUE THREAD

**Issue by prasadsheetal** [FERNman/angular-google-charts#267]
# Bug Report

## Prerequisites

Please answer the following questions for yourself before submitting an issue.
**YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the Readme and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] This is related to angular-google-charts and not to Google Charts directly (if it's a Google Charts issue, [their forum](https://groups.google.com/forum/#!forum/google-visualization-api) may help)

## To reproduce

Steps to reproduce the behaviour:

## Exception or Error

<pre><code>

</code></pre>

## Your environment

<pre><code>

</code></pre>

**Comment by umernaeem217** [comment]
Can you share some code snippets?

**Comment by prasadsheetal** [comment]
Waterfall chart component is not created.
