### ISSUE TITLE
Editing Charts (README.md)

### ISSUE THREAD

**Issue by FXLima** [FERNman/angular-google-charts#272]
# Update documentation

## Capture google-chart component by id
To pass to ChartEditorComponent, add the lines to the example:
```
@ViewChild('editable')
public readonly editable: GoogleChartComponent;
```
https://github.com/FERNman/angular-google-charts#editing-charts

## Additional context

```
// my.component.ts
class MyComp {
  @ViewChild(ChartEditorComponent)
  public readonly editor: ChartEditorComponent;

/* read google-chart id */
  @ViewChild('editable')
  public readonly editable: GoogleChartComponent;

  public editChart(chart: ChartBase) {
    this.editor
      .editChart(chart)
      .afterClosed()
      .subscribe(result => {
        if (result) {
          // Saved
        } else {
          // Cancelled
        }
      });
  }
}

```

**Comment by FERNman** [comment]
Hi @FXLima, thanks for your PR!

I'd prefer to keep the example in the documentation as-is, though. The `chart` reference is passed directly in the template `click` event listener, no need to query the document. One could even do the same for the `ChartEditorComponent` and completely remove any `@ViewChild` properties.

Of course, your example is also completely valid and could be used (however, you don't need the `chart` argument in the `editChart` method of your component).
