### ISSUE TITLE
Library is not working with Angular v14

### ISSUE THREAD

**Issue by faraz-ahmad** [FERNman/angular-google-charts#275]

**Comment by abrasat** [comment]
@FERNman : Could you please add support for at least Angular v13? Angular v12 is the last supported version....

**Comment by faraz-ahmad** [comment]
@abrasat  My project is using Angular v13 and It is working fine on that. I tried to migrate my project on Angular v14 but this library is not compatible with Angular v14.

Due to this issue, I am think to replace this library with new one If I don't get solution of this issue.

**Comment by abrasat** [comment]
@faraz-ahmad : Thanks for the information! How did you install angular-google-charts in angular v13? I tried with "npm i angular-google-charts" and got this error:
```
Could not resolve dependency:
 @angular/common@">=6.0.0 <=12.x.x" from angular-google-charts@2.2.2
 node_modules/angular-google-charts
 angular-google-charts@"^2.2.2" from the root project
```
Or did you use the "--legacy-peer-deps" option to install it?

**Comment by faraz-ahmad** [comment]
@abrasat - I used **npm i angular-google-charts** only.

**Comment by NicolasBonnin** [comment]
got the same error

**Comment by miguelhuayhua** [comment]
Hi, i got the issue, why?
Found: @angular/common@14.0.4
node_modules/@angular/common
@angular/common@"^14.0.0" from the root project

Could not resolve dependency:
peer @angular/common@">=6.0.0 <=12.x.x" from angular-google-charts@2.2.2
node_modules/angular-google-charts
 ngular-google-charts@"*" from the root project

**Comment by FERNman** [comment]
2.2.3 should include support for Angular 13 and 14, I hope it works for everyone!
