### ISSUE TITLE
Google chart editor UI is not working with Bootstrap and is broken

### ISSUE THREAD

**Issue by SDAdham** [FERNman/angular-google-charts#276]
# Bug Report

## Prerequisites

Please answer the following questions for yourself before submitting an issue.
**YOU MAY DELETE THE PREREQUISITES SECTION.**

- [X] I am running the latest version
- [X] I checked the Readme and found no answer
- [X] I checked to make sure that this issue has not already been filed
- [ ] This is related to angular-google-charts and not to Google Charts directly (if it's a Google Charts issue, [their forum](https://groups.google.com/forum/#!forum/google-visualization-api) may help)

## Description

It seems that Google chart UI is using a different modal other than https://getbootstrap.com/docs/5.1/components/modal/
Output html:
<img width="1021" alt="image" src="https://user-images.githubusercontent.com/11182824/175165071-4c22e045-0c26-4eb8-b3c9-c7ff4e425c48.png">

How can I apply bootstrap classes for bootstrap or get Chart editor to work in a bootstrap environment?

Here is how chart looks like:
<img width="475" alt="image" src="https://user-images.githubusercontent.com/11182824/175165487-0bf15737-902e-4efa-9adc-6e40dbb3dacb.png">

There are no errors in the console

## To reproduce

Steps to reproduce the behaviour:

## Exception or Error

<pre><code>

</code></pre>

## Your environment

<pre><code>

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1303.6
@angular-devkit/build-angular   13.3.6
@angular-devkit/core            13.1.4
@angular-devkit/schematics      13.3.5
@angular/cdk                    13.3.7
@angular/cli                    13.1.4
@angular/language-service       13.3.9
@angular/localize               13.3.9
@angular/platform-server        13.3.9
@angular/service-worker         13.3.9
@nguniversal/builders           12.1.3
@nguniversal/express-engine     12.1.3
@schematics/angular             13.1.4
rxjs                            7.5.5
typescript                      4.5.5
webpack                         5.72.1
</code></pre>

**Comment by FERNman** [comment]
I'm sorry, this is a question that should be asked in the Google Charts community and doesn't directly affect this package.
