### ISSUE TITLE
New version release which is compatible with Angular 13+

### ISSUE THREAD

**Issue by situlindia** [FERNman/angular-google-charts#279]
Hi, 

In the https://www.npmjs.com/package/angular-google-charts , we have the latest version as 2.2.2 which is incompatible with Angular 13 onwards. The last released version is more than a year ago i.e. June 2021.

When can we have a new release compatible with Angular 13 onwards.?

**Comment by FERNman** [comment]
I've just released 2.2.3, I hope it works for everyone! 🙂

**Comment by situlindia** [comment]
Thank you so much, You're doing absolute fab job.. Kudos!

**Comment by situlindia** [comment]
Dear @FERNman The new version is not compatible with the current stable version of Angular (v13.2.0).
Getting the below error during ng serve
![image](https://user-images.githubusercontent.com/32801470/179739189-64705b13-37f8-482b-8783-6cd5c4faeccd.png)
