### ISSUE TITLE
Add Controls and Dashboards

### ISSUE THREAD

**Issue by jkon** [FERNman/angular-google-charts#28]
I was wondering if someone could add a public function to the google-chart component that returns the wrapper object (the chart javascript object) so that I could be able to add dashboards and controls to my charts. To do that I need access to the chart object to bind to like in the example here:
https://developers.google.com/chart/interactive/docs/gallery/controls
```
dashboard.bind(donutRangeSlider, pieChart);
```
the pieChart object in the example is created the same way as the wrapper object in the component:
```
var pieChart = new google.visualization.ChartWrapper();
```
A function that returns the wrapper would allow all me to do all kinds of things the way they are done in the google documentation, without having to figure out how you got the library into the component.

thanks

**Comment by FERNman** [comment]
Hi @jkon,

This functionality already exists. Please refer to the [README](https://github.com/FERNman/angular-google-charts#advanced) for more detailed instructions.

Hope this helps, I'll close this for now!

**Comment by jkon** [comment]
Sorry, I’m not sure how I missed that part of the readme. Thanks for the quick response

**Comment by jkon** [comment]
Hey, so I tried to do this and I am able to get the wrapper property from the component, but now I've run into another issue that I do think I need your help with. When I try to setup the dashboard and control, I get this error:
```
error TS2339: Property 'ControlWrapper' does not exist on type 'typeof visualization'.
```
I think it is because the namespace in the types configuration doesn't have an interface for ControlWrapper or Dashboard. Am I right about that? And how can I get around it? Do I have to wait until the types definition is updated?
Thanks

**Comment by FERNman** [comment]
Sorry for not replying that long. I must have overlooked this reply somehow. 

If you didn't fix it by now (or someone else has this problem in the future), that's how you ignore typings:

```typescript
(<any>google.visualization>).ControlWrapper
```

You must be very sure on what to do from there on though, as you won't have any of the nice typescript things to help you.
You could also create a PR or an Issue for the Type Definitions Repo.
