### ISSUE TITLE
how to clear table in the latest api?

### ISSUE THREAD

**Issue by xkx9431** [FERNman/angular-google-charts#281]
what change should make this  api correct?, I have upgrade the package version from `^1.1.0` to ^`2.2.0`
and this will cause a build error.
```js
    @ViewChild('ganttChart') 
    public ganttEl: GoogleChartComponent;
```
![image](https://user-images.githubusercontent.com/44063249/179709708-1ae8d825-bfb9-4314-be93-c632e69c1159.png)

**Comment by xkx9431** [comment]
Before I'm using this code from https://github.com/FERNman/angular-google-charts/issues/230

**Comment by FERNman** [comment]
This is also related to #304. See my latest answer there for more information. In short, you'll have to check for the existence of the `clearChart` property on your current chart. I hope this helps!
