### ISSUE TITLE
New version 2.2.3 is not compatible with the current stable version of Angular (v13.2.0)

### ISSUE THREAD

**Issue by situlindia** [FERNman/angular-google-charts#282]
The new version 2.2.3 is not compatible with the current stable version of Angular (v13.2.0).
Getting the below error during ng serve
![image](https://user-images.githubusercontent.com/32801470/179739564-b3f0f0c4-64ce-47d9-87f7-d2ab3437d92e.png)

**Comment by daddyschmack** [comment]
I'm also getting an error.. 
generic type 'ɵɵComponentDeclaration' requires 7 type argument(s).
Not sure if it's related.. getting peer dependency errors on install

**Comment by arindammojumder** [comment]
I am also getting the same error and that's why I downgraded the version to **"angular-google-charts": "^2.2.2",**
It is working fine now with the angular version **"~13.3.0"**

**Comment by situlindia** [comment]
> I am also getting the same error and that's why I downgraded the version to **"angular-google-charts": "^2.2.2",** It is working fine now with the angular version **"~13.3.0"**

I tried with Angular 12, downgraded it but when added the module, I got the same error.

**Comment by gaaral** [comment]
@situlindia change `"angular-google-charts": "^2.2.2",` to `"angular-google-charts": "2.2.2",

**Comment by situlindia** [comment]
> @situlindia change `"angular-google-charts": "^2.2.2"` to `"angular-google-charts": "2.2.2"`

Thanks a lot. It's now working :)

**Comment by arindammojumder** [comment]
Frankly speaking, they should provide some example code, otherwise, it is too tough to integrate the chart. For the Maximum time, I am getting errors with input data. Can anyone send me a good example of a line and donut chart that has been implemented with this package?

**Comment by flobuc** [comment]
Currently, no version is working with Angular 13.x
Version 2.2.2 works only with Angular 12.x
Version 2.2.3 has the error described by @situlindia

**Comment by daddyschmack** [comment]
Dang.  I would love to try your package

**Comment by FERNman** [comment]
I'm sorry for the trouble. We were unaware that Angular requires packages to be compiled with the minimum supported version of Angular. We've reverted version 2 to Angular 12 and will release a new major version supporting Angular 16+ in the upcoming days.
