### ISSUE TITLE
Unable to install angular-google-charts in project

### ISSUE THREAD

**Issue by mca-binita** [FERNman/angular-google-charts#284]
# Bug Report

Hi, 
I am trying to install angular-google-charts in project but I am facing lots of errors while doing so.
Pasting my package.json:

**{
  "name": "frontend",
  "version": "0.0.0",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "~9.1.0",
    "@angular/cdk": "^9.2.0",
    "@angular/common": "~9.1.0",
    "@angular/compiler": "~9.1.0",
    "@angular/core": "~9.1.0",
    "@angular/flex-layout": "^9.0.0-beta.29",
    "@angular/forms": "~9.1.0",
    "@angular/material": "^9.2.0",
    "@angular/material-moment-adapter": "^11.0.2",
    "@angular/platform-browser": "~9.1.0",
    "@angular/platform-browser-dynamic": "~9.1.0",
    "@angular/router": "~9.1.0",
    "@angular/service-worker": "^9.1.13",
    "@auth0/angular-jwt": "^5.0.2",
    "@bokeh/bokehjs": "^2.0.1",
    "@ckeditor/ckeditor5-angular": "^2.0.1",
    "@ckeditor/ckeditor5-build-classic": "file:ckeditor5/packages/ckeditor5-build-classic",
    "@fullcalendar/angular": "^5.11.0",
    "@fullcalendar/daygrid": "^5.11.0",
    "@fullcalendar/interaction": "^5.11.0",
    "d3": "^7.0.0",
    "file-saver": "^2.0.5",
    "html-to-pdfmake": "^2.1.5",
    "jsonpath": "^1.1.1",
    "jszip": "^3.5.0",
    "jwt-decode": "^3.1.2",
    "moment": "^2.29.1",
    "ng-connection-service": "^1.0.4",
    "ngx-countdown": "^10.0.1",
    "ngx-image-compress": "^8.0.4",
    "ngx-image-cropper": "^3.2.1",
    "ngx-lightbox": "^2.2.2",
    "pdfmake": "^0.1.70",
    "rxjs": "~6.5.4",
    "tslib": "^1.10.0",
    "xlsx": "^0.17.0",
    "zone.js": "~0.10.2"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.901.0",
    "@angular/cli": "^9.1.0",
    "@angular/compiler-cli": "~9.1.0",
    "@angular/language-service": "~9.1.0",
    "@types/jasmine": "~3.5.0",
    "@types/jasminewd2": "~2.0.3",
    "@types/jsonpath": "^0.2.0",
    "@types/node": "^12.11.1",
    "codelyzer": "^5.1.2",
    "jasmine-core": "~3.5.0",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~4.4.1",
    "karma-chrome-launcher": "~3.1.0",
    "karma-coverage-istanbul-reporter": "~2.1.0",
    "karma-jasmine": "~3.0.1",
    "karma-jasmine-html-reporter": "^1.4.2",
    "protractor": "~5.4.3",
    "ts-node": "~8.3.0",
    "tslint": "~6.1.0",
    "typescript": "~3.8.3"
  }
}**

Can you please let me know which version I need to install? I tried several versions but every time I am facing one or another issue. 

## Prerequisites

Please answer the following questions for yourself before submitting an issue.
**YOU MAY DELETE THE PREREQUISITES SECTION.**

- [ ] I am running the latest version
- [x] I checked the Readme and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] This is related to angular-google-charts and not to Google Charts directly (if it's a Google Charts issue, [their forum](https://groups.google.com/forum/#!forum/google-visualization-api) may help)

## To reproduce

Steps to reproduce the behaviour:

## Exception or Error

<pre><code>

</code></pre>

## Your environment

<pre><code>

</code></pre>

**Comment by FERNman** [comment]
I'm sorry, @mca-binita , but this package only supports Angular 12 and up.
