### ISSUE TITLE
Angular google chart Version 2.2.2 Is not working on my existing Angular 9 Application

### ISSUE THREAD

**Issue by naveenroy001** [FERNman/angular-google-charts#285]
Hi Team,

My angular 9 Was running perfectly with angular-google-chart Version 2.2.2. Suddenly my PC OS was crashed. After resinstall npm packages angular google charts is not working.

Please check and let me know what I can do for resolve the issue I also tried to Update the angular Version and also tried angular-google-chart 2.2.3 Version. But No Luck.

Issue Trace
============

ERROR in node_modules/angular-google-charts/lib/services/script-loader.service.d.ts:41:21 - error TS2694: Namespace '"F:/myproject/angular update/ng-app/node_modules/@angular/core/core"' has no exported member 'ɵɵFactoryDeclaration'.

41     static ɵfac: i0.ɵɵFactoryDeclaration<ScriptLoaderService, never>;
                       ~~~~~~~~~~~~~~~~~~~~
node_modules/angular-google-charts/lib/services/script-loader.service.d.ts:42:22 - error TS2694: Namespace '"F:/myproject/angular update/ng-app/node_modules/@angular/core/core"' has no exported member 'ɵɵInjectableDeclaration'.

42     static ɵprov: i0.ɵɵInjectableDeclaration<ScriptLoaderService>;
                        ~~~~~~~~~~~~~~~~~~~~~~~
node_modules/angular-google-charts/lib/components/chart-editor/chart-editor.component.d.ts:26:21 - error TS2694: Namespace '"F:/myproject/angular update/ng-app/node_modules/@angular/core/core"' has no exported member 'ɵɵFactoryDeclaration'.

26     static ɵfac: i0.ɵɵFactoryDeclaration<ChartEditorComponent, never>;
                       ~~~~~~~~~~~~~~~~~~~~
node_modules/angular-google-charts/lib/components/chart-editor/chart-editor.component.d.ts:27:21 - error TS2694: Namespace '"F:/myproject/angular update/ng-app/node_modules/@angular/core/core"' has no exported member 'ɵɵComponentDeclaration'.

27     static ɵcmp: i0.ɵɵComponentDeclaration<ChartEditorComponent, "chart-editor", never, {}, {}, never, ["*"], false>;
                       ~~~~~~~~~~~~~~~~~~~~~~
node_modules/angular-google-charts/lib/services/data-table.service.d.ts:9:21 - error TS2694: Namespace '"F:/myproject/angular update/ng-app/node_modules/@angular/core/core"' has no exported member 'ɵɵFactoryDeclaration'.

9     static ɵfac: i0.ɵɵFactoryDeclaration<DataTableService, never>;
                      ~~~~~~~~~~~~~~~~~~~~
node_modules/angular-google-charts/lib/services/data-table.service.d.ts:10:22 - error TS2694: Namespace '"F:/myproject/angular update/ng-app/node_modules/@angular/core/core"' has no exported member 'ɵɵInjectableDeclaration'.

10     static ɵprov: i0.ɵɵInjectableDeclaration<DataTableService>;
                        ~~~~~~~~~~~~~~~~~~~~~~~
node_modules/angular-google-charts/lib/components/dashboard/dashboard.component.d.ts:55:21 - error TS2694: Namespace '"F:/myproject/angular update/ng-app/node_modules/@angular/core/core"' has no exported member 'ɵɵFactoryDeclaration'.

55     static ɵfac: i0.ɵɵFactoryDeclaration<DashboardComponent, never>;
                       ~~~~~~~~~~~~~~~~~~~~
node_modules/angular-google-charts/lib/components/dashboard/dashboard.component.d.ts:56:21 - error TS2694: Namespace '"F:/myproject/angular update/ng-app/node_modules/@angular/core/core"' has no exported member 'ɵɵComponentDeclaration'.

56     static ɵcmp: i0.ɵɵComponentDeclaration<DashboardComponent, "dashboard", ["dashboard"], { "data": "data"; "columns": "columns"; "formatters": "formatters"; }, { "ready": "ready"; "error": "error"; }, ["controlWrappers"], ["*"], false>;
                       ~~~~~~~~~~~~~~~~~~~~~~
node_modules/angular-google-charts/lib/components/google-chart/google-chart.component.d.ts:106:21 - error TS2694: Namespace '"F:/myproject/angular update/ng-app/node_modules/@angular/core/core"' has no exported member 'ɵɵFactoryDeclaration'.

106     static ɵfac: i0.ɵɵFactoryDeclaration<GoogleChartComponent, [null, null, null, { optional: true; }]>;
                        ~~~~~~~~~~~~~~~~~~~~
node_modules/angular-google-charts/lib/components/google-chart/google-chart.component.d.ts:107:21 - error TS2694: Namespace '"F:/myproject/angular update/ng-app/node_modules/@angular/core/core"' has no exported member 'ɵɵComponentDeclaration'.

107     static ɵcmp: i0.ɵɵComponentDeclaration<GoogleChartComponent, "google-chart", ["googleChart"], { "type": "type"; "data": "data"; "columns": "columns"; "title": "title"; "width": "width"; "height": "height"; "options": "options"; "formatters": "formatters"; "dynamicResize": "dynamicResize"; }, { "ready": "ready"; "error": "error"; "select": "select"; "mouseover": "mouseover"; "mouseleave": "mouseleave"; }, never, never, false>;
                        ~~~~~~~~~~~~~~~~~~~~~~
node_modules/angular-google-charts/lib/components/chart-wrapper/chart-wrapper.component.d.ts:35:21 - error TS2694: Namespace '"F:/myproject/angular update/ng-app/node_modules/@angular/core/core"' has no exported member 'ɵɵFactoryDeclaration'.

35     static ɵfac: i0.ɵɵFactoryDeclaration<ChartWrapperComponent, never>;
                       ~~~~~~~~~~~~~~~~~~~~
node_modules/angular-google-charts/lib/components/chart-wrapper/chart-wrapper.component.d.ts:36:21 - error TS2694: Namespace '"F:/myproject/angular update/ng-app/node_modules/@angular/core/core"' has no exported member 'ɵɵComponentDeclaration'.

36     static ɵcmp: i0.ɵɵComponentDeclaration<ChartWrapperComponent, "chart-wrapper", ["chartWrapper"], { "specs": "specs"; }, { "error": "error"; "ready": "ready"; "select": "select"; }, never, never, false>;
   m                    ~~~~~~~~~~~~~~~~~~~~~~
node_modules/angular-google-charts/lib/components/control-wrapper/control-wrapper.component.d.ts:85:21 - error TS2694: Namespace '"F:/myproject/angular update/ng-app/node_modules/@angular/core/core"' has no exported member 'ɵɵFactoryDeclaration'.

85     static ɵfac: i0.ɵɵFactoryDeclaration<ControlWrapperComponent, never>;
                       ~~~~~~~~~~~~~~~~~~~~
node_modules/angular-google-charts/lib/components/control-wrapper/control-wrapper.component.d.ts:86:21 - error TS2694: Namespace '"F:/myproject/angular update/ng-app/node_modules/@angular/core/core"' has no exported member 'ɵɵComponentDeclaration'.

86     static ɵcmp: i0.ɵɵComponentDeclaration<ControlWrapperComponent, "control-wrapper", ["controlWrapper"], { "for": "for"; "type": "type"; "options": "options"; "state": "state"; }, { "error": "error"; "ready": "ready"; "stateChange": "stateChange"; }, never, never, false>;
                       ~~~~~~~~~~~~~~~~~~~~~~
node_modules/angular-google-charts/lib/google-charts.module.d.ts:11:21 - error TS2694: Namespace '"F:/myproject/angular update/ng-app/node_modules/@angular/core/core"' has no exported member 'ɵɵFactoryDeclaration'.

11     static ɵfac: i0.ɵɵFactoryDeclaration<GoogleChartsModule, never>;
                       ~~~~~~~~~~~~~~~~~~~~
node_modules/angular-google-charts/lib/google-charts.module.d.ts:12:21 - error TS2694: Namespace '"F:/myproject/angular update/ng-app/node_modules/@angular/core/core"' has no exported member 'ɵɵNgModuleDeclaration'.

12     static ɵmod: i0.ɵɵNgModuleDeclaration<GoogleChartsModule, [typeof i1.GoogleChartComponent, typeof i2.ChartWrapperComponent, typeof i3.DashboardComponent, typeof i4.ControlWrapperComponent, typeof i5.ChartEditorComponent], never, [typeof i1.GoogleChartComponent, typeof i2.ChartWrapperComponent, typeof i3.DashboardComponent, typeof i4.ControlWrapperComponent, typeof i5.ChartEditorComponent]>;
                       ~~~~~~~~~~~~~~~~~~~~~
node_modules/angular-google-charts/lib/google-charts.module.d.ts:13:21 - error TS2694: Namespace '"F:/myproject/angular update/ng-app/node_modules/@angular/core/core"' has no exported member 'ɵɵInjectorDeclaration'.

13     static ɵinj: i0.ɵɵInjectorDeclaration<GoogleChartsModule>;
                       ~~~~~~~~~~~~~~~~~~~~~

** Angular Live Development Server is listening on localhost:4200, open your browser on http://localhost:4200/ **
30% building 2/2 modules 0 active
    ERROR in node_modules/angular-google-charts/lib/services/script-loader.service.d.ts:41:21 - error TS2694: Namespace '"F:/myproject/angular update/ng-app/node_modules/@angular/core/core"' has no exported member 'ɵɵFactoryDeclaration'.

    41     static ɵfac: i0.ɵɵFactoryDeclaration<ScriptLoaderService, never>;
                           ~~~~~~~~~~~~~~~~~~~~
    node_modules/angular-google-charts/lib/services/script-loader.service.d.ts:42:22 - error TS2694: Namespace '"F:/myproject/angular update/ng-app/node_modules/@angular/core/core"' has no exported member 'ɵɵInjectableDeclaration'.

    42     static ɵprov: i0.ɵɵInjectableDeclaration<ScriptLoaderService>;
                            ~~~~~~~~~~~~~~~~~~~~~~~
    node_modules/angular-google-charts/lib/components/chart-editor/chart-editor.component.d.ts:26:21 - error TS2694: Namespace '"F:/myproject/angular update/ng-app/node_modules/@angular/core/core"' has no exported member 'ɵɵFactoryDeclaration'.

    26     static ɵfac: i0.ɵɵFactoryDeclaration<ChartEditorComponent, never>;
                           ~~~~~~~~~~~~~~~~~~~~
    node_modules/angular-google-charts/lib/components/chart-editor/chart-editor.component.d.ts:27:21 - error TS2694: Namespace '"F:/myproject/angular update/ng-app/node_modules/@angular/core/core"' has no exported member 'ɵɵComponentDeclaration'.

    27     static ɵcmp: i0.ɵɵComponentDeclaration<ChartEditorComponent, "chart-editor", never, {}, {}, never, ["*"], false>;
                           ~~~~~~~~~~~~~~~~~~~~~~
    node_modules/angular-google-charts/lib/services/data-table.service.d.ts:9:21 - error[0m TS2694: Namespace '"F:/myproject/angular update/ng-app/node_modules/@angular/core/core"' has no exported member 'ɵɵFactoryDeclaration'.

    9     static ɵfac: i0.ɵɵFactoryDeclaration<DataTableService, never>;
                          ~~~~~~~~~~~~~~~~~~~~
    node_modules/angular-google-charts/lib/services/data-table.service.d.ts:10:22 - error TS2694: Namespace '"F:/myproject/angular update/ng-app/node_modules/@angular/core/core"' has no exported member 'ɵɵInjectableDeclaration'.

    10     static ɵprov: i0.ɵɵInjectableDeclaration<DataTableService>;
                            ~~~~~~~~~~~~~~~~~~~~~~~
    node_modules/angular-google-charts/lib/components/dashboard/dashboard.component.d.ts:55:21 - error TS2694: Namespace '"F:/myproject/angular update/ng-app/node_modules/@angular/core/core"' has no exported member 'ɵɵFactoryDeclaration'.

    55     static ɵfac: i0.ɵɵFactoryDeclaration<DashboardComponent, never>;
                           ~~~~~~~~~~~~~~~~~~~~
    node_modules/angular-google-charts/lib/components/dashboard/dashboard.component.d.ts:56:21 - error TS2694: Namespace '"F:/myproject/angular update/ng-app/node_modules/@angular/core/core"' has no exported member 'ɵɵComponentDeclaration'.

    56     static ɵcmp: i0.ɵɵComponentDeclaration<DashboardComponent, "dashboard", ["dashboard"], { "data": "data"; "columns": "columns"; "formatters": "formatters"; }, { "ready": "ready"; "error": "error"; }, ["controlWrappers"], ["*"], false>;
                           ~~~~~~~~~~~~~~~~~~~~~~
    node_modules/angular-google-charts/lib/components/google-chart/google-chart.component.d.ts:106:21 - error TS2694: Namespace '"F:/myproject/angular update/ng-app/node_modules/@angular/core/core"' has no exported member 'ɵɵFactoryDeclaration'.

    106     static ɵfac: i0.ɵɵFactoryDeclaration<GoogleChartComponent, [null, null, null, { optional: true; }]>;
                            ~~~~~~~~~~~~~~~~~~~~
    node_modules/angular-google-charts/lib/components/google-chart/google-chart.component.d.ts:107:21 - error TS2694: Namespace '"F:/myproject/angular update/ng-app/node_modules/@angular/core/core"' has no exported member 'ɵɵComponentDeclaration'.

    107     static ɵcmp: i0.ɵɵComponentDeclaration<GoogleChartComponent, "google-chart", ["googleChart"], { "type": "type"; "data": "data"; "columns": "columns"; "title": "title"; "width": "width"; "height": "height"; "options": "options"; "formatters": "formatters"; "dynamicResize": "dynamicResize"; }, { "ready": "ready"; "error": "error"; "select": "select"; "mouseover": "mouseover"; "mouseleave": "mouseleave"; }, never, never, false>;
                            ~~~~~~~~~~~~~~~~~~~~~~
    node_modules/angular-google-charts/lib/components/chart-wrapper/chart-wrapper.component.d.ts:35:21 - error TS2694: Namespace '"F:/myproject/angular update/ng-app/node_modules/@angular/core/core"' has no exported member 'ɵɵFactoryDeclaration'.

    35     static ɵfac: i0.ɵɵFactoryDeclaration<ChartWrapperComponent, never>;
                           ~~~~~~~~~~~~~~~~~~~~
    node_modules/angular-google-charts/lib/components/chart-wrapper/chart-wrapper.component.d.ts:36:21 - error TS2694: Namespace '"F:/myproject/angular update/ng-app/node_modules/@angular/core/core"' has no exported member 'ɵɵComponentDeclaration'.

    36     static ɵcmp: i0.ɵɵComponentDeclaration<ChartWrapperComponent, "chart-wrapper", ["chartWrapper"], { "specs": "specs"; }, { "error": "error"; "ready": "ready"; "select": "select"; }, never, never, false>;
                           ~~~~~~~~~~~~~~~~~~~~~~
    node_modules/angular-google-charts/lib/components/control-wrapper/control-wrapper.component.d.ts:85:21 - error TS2694: Namespace '"F:/myproject/angular update/ng-app/node_modules/@angular/core/core"' has no exported member 'ɵɵFactoryDeclaration'.

    85     static ɵfac: i0.ɵɵFactoryDeclaration<ControlWrapperComponent, never>;
                           ~~~~~~~~~~~~~~~~~~~~
    node_modules/angular-google-charts/lib/components/control-wrapper/control-wrapper.component.d.ts:86:21 - error TS2694: Namespace '"F:/myproject/angular update/ng-app/node_modules/@angular/core/core"' has no exported member 'ɵɵComponentDeclaration'.

    86     static ɵcmp: i0.ɵɵComponentDeclaration<ControlWrapperComponent, "control-wrapper", ["controlWrapper"], { "for": "for"; "type": "type"; "options": "options"; "state": "state"; }, { "error": "error"; "ready": "ready"; "stateChange": "stateChange"; }, never, never, false>;
                           ~~~~~~~~~~~~~~~~~~~~~~
    node_modules/angular-google-charts/lib/google-charts.module.d.ts:11:21 - error TS2694: Namespace '"F:/myproject/angular update/ng-app/node_modules/@angular/core/core"' has no exported member 'ɵɵFactoryDeclaration'.

    11     static ɵfac: i0.ɵɵFactoryDeclaration<GoogleChartsModule, never>;
                           ~~~~~~~~~~~~~~~~~~~~
    node_modules/angular-google-charts/lib/google-charts.module.d.ts:12:21 - error TS2694: Namespace '"F:/myproject/angular update/ng-app/node_modules/@angular/core/core"' has no exported member 'ɵɵNgModuleDeclaration'.

    12     static ɵmod: i0.ɵɵNgModuleDeclaration<GoogleChartsModule, [typeof i1.GoogleChartComponent, typeof i2.ChartWrapperComponent, typeof i3.DashboardComponent, typeof i4.ControlWrapperComponent, typeof i5.ChartEditorComponent], never, [typeof i1.GoogleChartComponent, typeof i2.ChartWrapperComponent, typeof i3.DashboardComponent, typeof i4.ControlWrapperComponent, typeof i5.ChartEditorComponent]>;
                           ~~~~~~~~~~~~~~~~~~~~~
    node_modules/angular-google-charts/lib/google-charts.module.d.ts:13:21 - error TS2694: Namespace '"F:/myproject/angular update/ng-app/node_modules/@angular/core/core"' has no exported member 'ɵɵInjectorDeclaration'.

    13     static ɵinj: i0.ɵɵInjectorDeclaration<GoogleChartsModule>;

**Comment by cguilhermef** [comment]
As expected, will not work. Version 2.2.2 is based Angular 12. And version 2.2.3, based on Angular 14. This project has a Semver's misusing. Angular upgrades should be considered major updates, as breaking changes.

**Comment by FERNman** [comment]
Sorry for the issues! We've now reverted the current version back to Angular 12, however, we'll release a breaking change for Angular 16+ in the upcoming days.
