### ISSUE TITLE
Use Types interfaces in project

### ISSUE THREAD

**Issue by avocadosarelife** [FERNman/angular-google-charts#286]
Hello, 
 
Is it possible to access to the interfaces in the `index.d.ts` file?
As of now I am defining my own `ChartOptions` but would love to use `BarChartOptions` for example directly.

Then, taking the example from the documentation, I could type the options and profit from Intellisense : )
```
// original example
myOptions = {
  colors: ['#e0440e', '#e6693e', '#ec8f6e', '#f3b49f', '#f6c7b6'],
  is3D: true
};

```
```
// typed example
myOptions: BarChartOptions = {
  colors: ['#e0440e', '#e6693e', '#ec8f6e', '#f3b49f', '#f6c7b6'],
  is3D: true
};
```

**Comment by FERNman** [comment]
This package doesn't include typings for the different charts. Instead, it relies on the types from `@types/google.visualization` and only provides additions to them where necessary. So feel free to use `google.visualization.BarChartOptions` :)
