### ISSUE TITLE
Update peerDependencies for Angular 15

### ISSUE THREAD

**Issue by timfogarty1549** [FERNman/angular-google-charts#292]
npm ERR! Could not resolve dependency:
npm ERR! peer @angular/common@">=6.0.0 <=14.x.x" from angular-google-charts@2.2.3
npm ERR! node_modules/angular-google-charts
npm ERR!   angular-google-charts@"^2.2.3" from the root project

the file libs/angular-google-charts/package.json needs to be updated for Angular 15

**Comment by timfogarty1549** [comment]
temporary solution is to add the following to your package.json file

` 
  "overrides": {
    "angular-google-charts": {
      "@angular/common": "^15.0.3",
      "@angular/core": "^15.0.3"
    }
  }
`

**Comment by mohamed-badaoui** [comment]
Update peerDependencies for Angular 16 now ?

**Comment by mohamed-badaoui** [comment]
> Update peerDependencies for Angular 16 now ?

Update peerDependencies for Angular 17 now ?

**Comment by dkavanagh** [comment]
I read that this package was being maintained, but with the last update a year ago, I'm beginning to wonder.

**Comment by FERNman** [comment]
This was included in #296 and will be released soon :) Of course, @mohamed-badaoui is right and by now, we'll need a much more recent version of Angular. This will also follow in the next few days!
