### ISSUE TITLE
Locale Support

### ISSUE THREAD

**Issue by cheesgno** [FERNman/angular-google-charts#295]
Hi!
As defined in the google documentation 

 // Load Google Charts for the Japanese locale.
 google.charts.load('current', {'packages':['corechart'], 'language': 'ja'});

is there a way to load a graph with a specific locale and change it dinamically?

Best Regards

**Comment by GertrudMathilde** [comment]
Is there any chance for this to be implemented? The project seems pretty dead :(
While I can use workarounds to use this package with angular 16, I can't make the locale work...

**Comment by FERNman** [comment]
Would be open to accepting PRs implementing this feature! If I have some time in the upcoming days, I'll maybe look into it.

**Comment by FERNman** [comment]
Okay, as promised: I looked into it. This is implemented in a specific way: The `ScriptLoaderService` loads the language provided by `LOCALE_ID`.

If this should be reworked, I'd be very open to reopening this issue and accepting PRs (I'll rework the module to support standalone components in the upcoming releases, this might cause me to look at the DI anyways).
