### ISSUE TITLE
Expand Row interface definition

### ISSUE THREAD

**Issue by oobayly** [FERNman/angular-google-charts#297]
# Feature request

The interface definition for `Row` should also include the type `{v: any, f: any}` - see [Cell Objects](https://developers.google.com/chart/interactive/docs/reference#cell_object)

## Describe the solution you'd like

Update the Row interface
```diff
-export type Row = (string | number | Date | null)[];
+export type Row = (string | number | Date | { v: string | number | Date | null, f: string | null } | null)[];
```

I've added this into #296.

## Describe alternatives you've considered

n/a
## Additional context

n/a

**Comment by kussmaul** [comment]
Please add `boolean` as a valid data type, too.

**Comment by FERNman** [comment]
@kussmaul I've checked the `google.visualization` typings, they simply use `any` as the type. Probably they actually only allow primitives and `Date` (and no custom objects), but I'm not even sure about that.

Would you prefer sticking with the current typing (adding `boolean` to support all primitives), or simply switch to `any` to be more flexible? I'm leaning toward the latter. The resulting type would be

```ts
export type Row = (any | google.visualization.DataObjectCell)[];
```

**Comment by kussmaul** [comment]
@FERNman using `any` seems reasonable, especially since it matches `google.visualization`.

**Comment by FERNman** [comment]
@kussmaul great, then I'll go ahead and merge the PR! 👍
