### ISSUE TITLE
I don't get any error but I don't see anything

### ISSUE THREAD

**Issue by kintela** [FERNman/angular-google-charts#298]
Hi

I have a component where I am going to embed several graphics

...`
<app-grafica [title]="'Costes y Horas'" [type]="'ColumnChart'" [data]="dataHorasCostesOfertas" [columns]="chartHorasCostesOfertasColumns" [options]="options"></app-grafica>
...
<app-grafica [title]="'Ofertas Presentadas y Adjudicadas'" [type]="'ColumnChart'"
        [data]="dataPorcentajeAdjudicadas" [columns]="chartPorcentajeAdjudicadasColumns" [options]="options"></app-grafica>

chartPorcentajeAdjudicadasColumns = ['Año', 'Presentadas', 'Adjudicadas'];
chartHorasCostesOfertasColumns = ['Año', 'Horas', 'Costes'];

options={
    hAxis: {
      title: 'Años',
    },
    vAxis: {
      minValue: 0,
    },
    legend: { position: 'top' }
`

then I have this graficaComponent

`
<div class="grafica">
  <google-chart #chart [title]="title" [type]="type" [data]="data" [options]="options" [columns]="columns" [width]="800" [height]="500">
  </google-chart>
</div>

import { Component, Input, OnChanges, OnInit, SimpleChanges, ViewChild } from '@angular/core';

@Component({
  selector: 'app-grafica',
  templateUrl: './grafica.component.html',
  styleUrls: ['./grafica.component.scss']
})
export class GraficaComponent implements OnInit, OnChanges {
  @Input() title: string;
  @Input() type: string;
  @Input() origen: string;
  @Input() data: any[][];
  @Input() columns: string[];
  @Input()  options: any;

  
  constructor() { }
  ngOnChanges(changes: SimpleChanges): void {
    console.log('GraficaComponent-ngOnChanges-data', this.data);
  }
  ngOnInit(): void {
  }
}

`
But nothing is shown, no error appears and the graphic component receives the data correctly

![image](https://github.com/FERNman/angular-google-charts/assets/10060242/40bdb974-0e8d-4c9b-81aa-735d51c2888d)

Any idea, please?

Thanks

**Comment by FERNman** [comment]
I'll close this since it's quite old already. I hope you managed to resolve this in the meantime!
