### ISSUE TITLE
Default color gradient & colorAxis property does not apply on GeoChart.

### ISSUE THREAD

**Issue by snaik2064** [FERNman/angular-google-charts#30]
demo.html
`<google-chart [type]="type" [data]="data" [options]="options"></google-chart> `

In demo.component.ts I have declared options variable with following values:

```
data = [
    ['State', 'Sales'], 
    ['US-NY', 100],
    ['US-OR', 200],
    ['US-PA', 300], 
    ['US-TX', 400],
   ['US-UT', 500] 
];

options = {
    region: 'US',
    resolution: 'provinces',
    defaultColor: '#3687ee'
}
```
By default GeoChart shows color gradient of 'defaultColor: '#3687ee', but after implementing it only shows same color (#3687ee) for every state 'data'  and ' colorAxis' property also doesn't apply on chart.

**Comment by FERNman** [comment]
Hi @snaik2064 

I've just tried out your example. Are you sure the `defaultColor` property works the way you expect it to?

For me, the following configuration does everything I want it to:

```html
<google-chart
  width="600"
  title="Geo Chart"
  type="GeoChart"
  [data]="[
    ['US-NY', 100],
    ['US-OR', 200],
    ['US-PA', 300], 
    ['US-TX', 400],
    ['US-UT', 500] 
  ]"
  [columnNames]="['State', 'Sales']"
  [options]="{
    region: 'US',
    resolution: 'provinces',
    colorAxis: {colors: ['#e7711c', '#4374e0']}
  }">
</google-chart>
```

Anyways, it's definitely not this library making those errors you're seeing. Either it's a bug in the Google Charts library or it's a user error.

Hope this helps,
FERNman

**Comment by shashank221** [comment]
Thanks it worked.

**Comment by snaik2064** [comment]
Thanks it worked.
