### ISSUE TITLE
This library is unmaintained

### ISSUE THREAD

**Issue by krabouilleur** [FERNman/angular-google-charts#305]
Archive this projet, if it not maintained

**Comment by volhakireyeva** [comment]
Is this project supported?

**Comment by geojaz** [comment]
The original author does not seem to be accepting updates etc... we're trying to resurrect this repo over here https://github.com/onix-net/angular-google-charts

First effort is support for angular v17

**Comment by FERNman** [comment]
Hi @krabouilleur, I'm sorry for not actively maintaining this project over the last two years, work was keeping me too busy. I now again have some more capacity (and I'm also back to web development professionally, which makes the maintenance easier). I will be more than happy to again accept any contributions from now on!
