### ISSUE TITLE
How to get selected element value?

### ISSUE THREAD

**Issue by keshav1007** [FERNman/angular-google-charts#31]
I have created org chart using this angular 6 wrapper. I would like to do some changes based on click events.

(select)="onSelect($event) - this gives me only row and column. How can i get which item i have clicked?

**Comment by FERNman** [comment]
Hi @keshav1007 ,

To get the selected item, use the Row and Column index on your data set. If your data set is, for example,

```typescript
[8, 12],
[4, 5.5],
[11, 14],
[4, 5],
[3, 3.5],
[6.5, 7]
```

and the selected event tells you that you selected row 0 column 1, that means you've selected the 12 in the first row of the dataset.

Hope this helps,
FERNman
