### ISSUE TITLE
ERROR in node_modules/angular-google-charts/lib/google-charts.module.d.ts(5,44): error TS2315: Type 'ModuleWithProviders' is not generic.

### ISSUE THREAD

**Issue by ahanad** [FERNman/angular-google-charts#34]
I keep getting this error when I compile - 
ERROR in node_modules/angular-google-charts/lib/google-charts.module.d.ts(5,44): error TS2315: Type 'ModuleWithProviders' is not generic.

I have installed google charts. After installation, it does not give any error. 
ng serve is throwing this error. 
![google-charts-module screenshot](https://user-images.githubusercontent.com/44961859/48332233-199dbf80-e679-11e8-9033-602a0fd16e17.PNG)

**Comment by FERNman** [comment]
Hi @ahanad,

This is now fixed in the newly published version. I'd love to hear from you if it works if you update the library!

Hope everything works now, 
FERNman

**Comment by ahanad** [comment]
Newly published version of?? Could you please let me know how to update the
library?

**Comment by FERNman** [comment]
By using `npm update`.

**Comment by ahanad** [comment]
Getting below error..


D:\242425\CoE\Pristine\pristine2.0\trunk\Customer360\customer360>npm update
npm WARN deprecated @angular/flex-layout@5.0.0-beta.14-17a70ee: deprecate
faulty release
npm WARN deprecated angularfire2@5.1.0: AngularFire has moved, we're now
@angular/fire
npm WARN deprecated circular-json@0.5.9: CircularJSON is in maintenance
only, flatted is its successor.
npm WARN deprecated nodemailer@2.7.2: All versions below 4.0.1 of
Nodemailer are deprecated. See https://nodemailer.com/status/
npm WARN deprecated node-uuid@1.4.8: Use uuid module instead
npm WARN deprecated socks@1.1.9: If using 2.x branch, please upgrade to at
least 2.1.6 to avoid a serious bug with socket data flow and an import
issue introduced in 2.1.0
npm WARN deprecated mailcomposer@4.0.1: This project is unmaintained
npm WARN deprecated buildmail@4.0.1: This project is unmaintained
npm WARN deprecated uws@9.14.0: stop using this version
npm ERR! code ENOGIT
npm ERR! No git binary found in $PATH
npm ERR!
npm ERR! Failed using git.
npm ERR! Please check if you have git installed and in your PATH.

npm ERR! A complete log of this run can be found in:
npm ERR!
 C:\Users\242425\AppData\Roaming\npm-cache\_logs\2018-11-12T09_25_22_005Z-debug.log


I am very new to this.. Thanks in advance for all your help.
