### ISSUE TITLE
Can't get this to work – 404 on google resource

### ISSUE THREAD

**Issue by kak-tuss** [FERNman/angular-google-charts#36]
Hello,

I get a loader.js:222 GET https://www.gstatic.com/charts/45.2/js/jsapi_compiled_undefined_module.js 404 () for some reason, please help!

![screen shot 2018-11-14 at 15 06 03](https://user-images.githubusercontent.com/18115767/48484492-ec8b1180-e81e-11e8-89ac-d26bc06537c9.png)
![screen shot 2018-11-14 at 15 06 34](https://user-images.githubusercontent.com/18115767/48484495-ec8b1180-e81e-11e8-85ae-2dfe1845a33e.png)

Thank you

**Comment by kak-tuss** [comment]
Sorry, was my fault :))

**Comment by pahide** [comment]
Some issue here. how did you solve it?

**Comment by kak-tuss** [comment]
probably wrong url for the plugin


Katya Perlin
kaktuss@gmail.com
