### ISSUE TITLE
google.charts not loaded if google.maps already loaded

### ISSUE THREAD

**Issue by mark-roy** [FERNman/angular-google-charts#42]
I'm using both Angular Google Maps https://angular-maps.com/ and angular-google-charts in my app. However, if google.maps gets loaded prior to google.charts, I get this error:

core.js:14597 ERROR TypeError: Cannot read property 'load' of undefined
    at Observable._subscribe (angular-google-charts.js:87)

which is this line:
            google.charts.load('45.2', config);

I believe that the source of the issue is here: 

```javascript
    Object.defineProperty(ScriptLoaderService.prototype, "doneLoading", {
        get: /**
         * @return {?}
         */
        function () {
            if (typeof (google) !== 'undefined') {
                return true;
            }
            return false;
        },
        enumerable: true,
        configurable: true
    });
    Object.defineProperty(ScriptLoaderService.prototype, "isLoading", {
        get: /**
         * @return {?}
         */
        function () {
            var _this = this;
            if (typeof (google) === 'undefined') {
                /** @type {?} */
                var pageScripts = Array.from(document.getElementsByTagName('script'));
                return pageScripts.findIndex(function (script) { return script.src === _this.scriptSource; }) >= 0;
            }
            return false;
        },
        enumerable: true,
        configurable: true
    });
 ```

where the test if (typeof (google) !== 'undefined') fails when google.maps is already loaded, which short-circuits the loading of google.charts.

My chart works fine if I avoid displaying a map prior to a chart. Is there a workaround?

**Comment by antoinevulcain** [comment]
I have the same problem you find a solution?
