### ISSUE TITLE
Angular 7

### ISSUE THREAD

**Issue by jkon** [FERNman/angular-google-charts#44]
Are you planning upgrading to Angular 7 soon?

**Comment by jkon** [comment]
I updated a fairly large project earlier this week and the performance difference is like night and day. They made huge improvements to the way change detection works so that larger apps won’t get bogged down. The charts work fine in that project, but I imagine they might also gain some performance from the upgrade. Also, the upgrade itself is quite quick. There weren’t any config file changes like last time, just upgrading all the packages to 7.0.0+. Only issue I ran across was that the guide I used told me to turn on enableIvy in the angularCompilerOptions and that didn’t work for me, I had to turn it back off to get my build to work

**Comment by FERNman** [comment]
Ok so I was just trying it out and there's nothing that has to be changed in the library to be able to use it with Angular 7. The demo project in this repo is now on Angular 7 and works just as before, and the library is compatible with both Angular 6 and 7.

If I misunderstood or overlooked something, feel free to reopen this issue. I'll close it for now!
