### ISSUE TITLE
Material Charts

### ISSUE THREAD

**Issue by jkon** [FERNman/angular-google-charts#5]
Hi, great project and I love that I don't have to try and do this myself. I do have a question/request though. I looked at the script loader service and I see that you only include the corechart package and I was wondering if you are planning on adding the new material packages as well. It would be nice if I didn't have to do additional theming on the charts that already have the material themes in the newer packages like this example: https://google-developers.appspot.com/chart/interactive/docs/gallery/barchart#creating-material-bar-charts
thanks

**Comment by FERNman** [comment]
I hope that this is now working - feel free to track down any bugs you're experiencing! 👍
