### ISSUE TITLE
Would offloading dynamic resizing to a webworker improve performance?

### ISSUE THREAD

**Issue by hvent90** [FERNman/angular-google-charts#50]
I'm not too sure on the specifics of web workers, just voicing a curiosity out loud. Cheers!

**Comment by FERNman** [comment]
I'm not really sure. I didn't work with web workers too much yet, either, but I think that this would create some problems as the GoogleCharts library is probably not built for multithreaded updates or similar things. If someone knows more about this, I'd love to hear it (or see a pull request), however, in my opinion, it wouldn't be worth the effort.

Thanks for the idea though!

**Comment by hvent90** [comment]
Thanks for the response, and thank you for taking the time to create this repository. This has saved me buckets of time! Have a wonderful day.
