### ISSUE TITLE
ERROR ReferenceError: google is not defined

### ISSUE THREAD

**Issue by simonmoreau** [FERNman/angular-google-charts#53]
I am sorry, but I keep having the 'google is not defined' error when I am using the "Formatter" object and I don't see how to load the script as you describe in the Readme.

**Comment by FERNman** [comment]
Hi @simonmoreau 

If you want to use the Formatter object of GoogleCharts, here's what you have to do (also found in the [README](https://github.com/FERNman/angular-google-charts#custom-components).

In the component where you want to create the chart, inject the `ScriptLoaderService`.
Example:

```typescript
constructor(private loaderService: ScriptLoaderService) {}
```

Then subscribe to the `onReady` event of the `ScriptLoaderService` and load the package you need in the callback. As an example and to follow best practices, I'll do this in the `onInit` method. It can, however, be done anywhere in your component:

```typescript
ngOnInit() {
  this.loaderService.onReady.subscribe(() => {
     this.loaderService.loadChartPackages(this.type).subscribe(() => {
       // Start creating your chart now
       // Example:
       const formatter = new google.visualization.BarFormat();
     });
  });
}
```

where `this.type` is your chart type, e.g. `BarChart`.

Hope this helps. If you still have any problems regarding this issue, feel free to point them out.

**Comment by simonmoreau** [comment]
I get it, it is working fine by now ! Thank you for your help !
