### ISSUE TITLE
Custom tooltip in TimeLine chart

### ISSUE THREAD

**Issue by DanielOrfeu** [FERNman/angular-google-charts#55]
Hi, @FERNman.
I tried to create a custom tooltip in a Timeline chart, but this chart not change the default tooltip.
Follow example of default tooltip:
![image](https://user-images.githubusercontent.com/28579324/53510005-c589e000-3a9b-11e9-9a2f-13336e636fcd.png)
The component has no errors.
I tested this same method in Bar chart and he works..
Example:
![image](https://user-images.githubusercontent.com/28579324/53510407-ad669080-3a9c-11e9-9d65-80064cebf6fb.png)

**Comment by FERNman** [comment]
Did you fix it? If not, could you please provide the code used?

**Comment by DanielOrfeu** [comment]
No. With a new requirements in system, i decided for use an Modal Components with onClick event in this chart.

One more quesition:
Is it possible to create a link property inside this names (ANTONIO, CARLOS, etc) in row label?

![image](https://user-images.githubusercontent.com/28579324/57643679-a8d85100-7590-11e9-8063-8fa74462d271.png)

**Comment by FERNman** [comment]
Yes, by using event handlers. Event handlers are supported by this library via angular bindings (see the [Readme](https://github.com/FERNman/angular-google-charts#events), however, you can always access the plain google charts javascript object. See for example [this thread](https://stackoverflow.com/questions/6205621/how-to-add-links-in-google-chart-api) on how to do this.

I hope this helps and will close the issue for now. If anything new comes to your mind, feel free to ask!
