### ISSUE TITLE
Timeline - Can't change specific bars color

### ISSUE THREAD

**Issue by FernandoC13** [FERNman/angular-google-charts#58]
Hi there, 
So i'm trying to make a Timeline chart where the manager can see if the consultant is on a project or not.

The issue is that I can't change the color on each bar the right way, because I want the bar with projects in green and the bar without projects in red.

**Here's what I get:** 
![Screenshot_1](https://user-images.githubusercontent.com/35776049/55873800-82398b80-5b88-11e9-9922-8a36b1abd4f6.png)

As you see, the consultant 2 has a project associated and it appears red instead of green, and when he doesn't have a project it appears green instead of red.

This is because I can't apply roles to the timeline chart, in others chart I tested and I could change the color as I wished, but in the timeline chart is other story.

So I have in options this: 
` chart.options = {        
  colors: ["green", "red"] }`

So the first value I insert will be green, the second (different from the 1st) red and the third will be green. 
If I only needed two inserts (On Project and Without Project) this would work just fine, but I want (NameOfProject1, NameOfProject2, NameOfProject3, NameOfProjectN and Without Project)

**I think it's a bug from this chart, but I want to make sure with you**

Thanks for your help!
_________________________
Best regards,
Fernando Caria

**Comment by FERNman** [comment]
Hi @FernandoC13 ,

I'm really sorry for not being able to reply earlier. I've been busy during the last months and therefore am not able to check with this project very often.

As you already pointed out, though, this really isn't related to this library, but more a problem of Google Charts itself. I suggest you go to the official documentation (and maybe StackOverflow) to find how to solve your problem (if you didn't yet). 

I'll close this for now, but if you found a solution I'd be happy to see it as it will help others who find this thread!
