### ISSUE TITLE
Is possible to Add image to treemap chart?

### ISSUE THREAD

**Issue by pcbimon** [FERNman/angular-google-charts#61]
I'm creating SDG Goal to treemap chart. now I can generate chart with label text like this
![image](https://user-images.githubusercontent.com/8252967/57011299-27e19700-6c2b-11e9-8a22-426b02de6792.png)

 If it possible,I would like to insert some image and label to each data like this
![english_SDG_17goals_poster_all_languages_with_UN_emblem_1](https://user-images.githubusercontent.com/8252967/57011215-d802d000-6c2a-11e9-92f5-e4bd10dd7573.png)

Thanks.

**Comment by FERNman** [comment]
I'm pretty sure this is not possible using GoogleCharts, you'd have to create something on your own using CSS and maybe Javascript. Good luck!
