### ISSUE TITLE
NodeClass option doesnt work for orgchart

### ISSUE THREAD

**Issue by soleanos** [FERNman/angular-google-charts#62]
Hello, 
I have a probleme witch i cant solve .. i try to add nodeClass : 'myClass' in my optionObject but the class is not loaded, but when i inspect node i see her in html but not any style applyed !! .. 
Can't google chart component load class from my component .css file ? 
Thank you

**Comment by FERNman** [comment]
Hi @soleanos ,

Usually, it should be possible to load CSS from a separate CSS file. In this special case, I'm not really able to help you though, as you didn't provide source code or at least a more detailed description.

For now, I suggest you go through your code (and maybe the documentation) once more to make sure everything looks as expected. Looking forward to hearing whether you managed to resolve your issue!
