### ISSUE TITLE
Next publish to NPM?

### ISSUE THREAD

**Issue by almania69** [FERNman/angular-google-charts#64]
Hi FERNman,

Do you have a timeline on when the next publish to npm will be for the latest updates?

Thanks,
Alex

**Comment by FERNman** [comment]
Hi @almania69 ,

I just published v0.1.4. It has a few improvements (including your pull request) and also the fix for #60 .
If the new release breaks anything, feel free to mention it here. I'll leave this thread open for the next few days.

Greetings,
FERNman

**Comment by almania69** [comment]
Sweet, thanks!
