### ISSUE TITLE
Current version blocks ng update.

### ISSUE THREAD

**Issue by wdunn001** [FERNman/angular-google-charts#67]
Angular 8 was release. Running ng update results in the following error

` ng update @angular/cli @angular/core
Your global Angular CLI version (7.3.8) is greater than your local
version (7.3.1). The local Angular CLI version is used.

To disable this warning use "ng config -g cli.warnings.versionMismatch false".
                  Package "angular-google-charts" has an incompatible peer dependency to "@angular/core" (requires "^6.0.0-rc.0 || ^6.0.0" (extended), would install "8.0.0").
                  Package "angular-google-charts" has an incompatible peer dependency to "@angular/common" (requires "^6.0.0-rc.0 || ^6.0.0" (extended), would install "8.0.0").
Incompatible peer dependencies found. See above.`

**Comment by FERNman** [comment]
Hi @wdunn001 ,

I just tried updating my local angular version to 8.0 and it worked like a charm, no need to specify all the versions. ^6.0.0 is enough for angular to allow everything from there on, at least I think so. Could you maybe try again?

If the problem remains, I'll try to find a solution. For now, I'll leave this issue and the PR open.

**Comment by BlueAlder** [comment]
I also am having this issue, when trying to update to angular 8

**Comment by wdunn001** [comment]
@FERNman you can update manually the issues is with ng update. it identifies that angular 8 is not a valid peer dependency target.

**Comment by FERNman** [comment]
Ok, I've merged the PR now and will Release a new version today,
