### ISSUE TITLE
Unmet peer dependency of Angular 6 with v0.1.4

### ISSUE THREAD

**Issue by deepankar-j** [FERNman/angular-google-charts#69]
I'm using angular-google-charts v0.1.4 with Angular 7, but npm is still complaining about angular-google-charts depending on angular core v6.   

`npm ERR! peer dep missing: @angular/core@^6.0.0-rc.0 || ^6.0.0, required by angular-google-charts@0.1.5`

Is the peer dependency accurate?

**Comment by FERNman** [comment]
I think this should already be fixed in the newest version of the package. If not, feel free to reopen this issue.
