### ISSUE TITLE
OnReady listener does not trigger the event

### ISSUE THREAD

**Issue by JCepedaVillamayor** [FERNman/angular-google-charts#7]
Hi,

First of all, thank you for the project, the code it's pretty clear and it's easy to use. I've found a problem regarding the `ready` event. If you put inside your component a event binding for the `ready` event, the function associated to it does not execute. e.g. If you have this html

```html
<google-chart 
[type]="chartType" [data]="chartData" [options]="options" 
[width]="width" [height]="height" (ready)="onReady()"></google-chart>
```

And you put a function such as:
```typescript
 onReady() {
    console.log(height);
}
```

The code is not being executed when the chart is loaded.

Is there a way to solve this?
Thanks again for the library.

Regards

**Comment by FERNman** [comment]
This should be fixed now, at least in the demos it now works. Thanks for pointing it out!

**Comment by JCepedaVillamayor** [comment]
Wow, thank you for the speed of the response!

Cheers!
