### ISSUE TITLE
Conditional formatting

### ISSUE THREAD

**Issue by clegeard** [FERNman/angular-google-charts#73]
Hi,
I am new to Angular Google Charts and I am trying to format the bars of my chart differently if a condition applies (from 2003 to 2019 bars should be of a particular color and from 2020 onwards of another color)
Any help on how I can do this would be much appreciate.
Thanks
Christele

**Comment by AlmaniaM** [comment]
Hi @clegeard,

You could probably do something like this:
```
var data = google.visualization.arrayToDataTable([
         ['Element', 'Density'],
         ['Copper', 2008, '#b87333'],            // RGB value
         ['Silver', 2009, 'silver'],            // English color name
         ['Gold', 2020, 'gold'],
         ['Platinum', 2021, 'color: #e5e4e2' ], // CSS-style declaration
      ]);
var chartOptions = {
  roles: [{
    index: 2,
    role: 'style'
  }]
}
```
This was taken from the Google Charts Documentation [here](https://developers.google.com/chart/interactive/docs/gallery/barchart).
