### ISSUE TITLE
Custom tooltip in Line Chart

### ISSUE THREAD

**Issue by claraharguindey** [FERNman/angular-google-charts#74]
Hey!
I'm trying to custom the tooltip in a line chart, but it's not working. There's no any errors in the console. Any idea? Thanks in advance👵🏼

**TS:**
```
this.chart = {
      title: 'Chart',
      type: 'Line',
      data: ['2019-02-28', 11.774659,  'tooltip text'],
      columnNames: [date, value],
      roles: [
        {
          role: 'tooltip',
          type: 'string',
          index: 2,
        },
      ],
      options: {
        width: 900,
        height: 400,
      },
    };
```

**HTML**
```
 <google-chart
      [title]="chart.title"
      [type]="chart.type"
      [data]="chart.data"
      [columnNames]="chart.columnNames"
      [options]="chart.options"
      [roles]="chart.roles"
    >
```

**Comment by AlmaniaM** [comment]
Hello @claraharguindey,

You might want to set your index inside the role to the index of the data that it will apply to.
Example:

**Comment by claraharguindey** [comment]
Thank you, @AlmaniaM ! 
You were right, the problem was that I was using material charts. Now it works. Thanks for your help!
