### ISSUE TITLE
Please provide the link of the package Documentation

### ISSUE THREAD

**Issue by sunith-kumar** [FERNman/angular-google-charts#75]

**Comment by FERNman** [comment]
What package is this issue referring to? The Github documentation links the Google Charts documentation if that's what you meant.

**Comment by sunith-kumar** [comment]
@FERNman Is there a documentation for angular-google-charts. If yes Please provide the link

**Comment by FERNman** [comment]
Of course there is, just have a look at the readme here in this repository.
