### ISSUE TITLE
Providing columns as first row in data does not work

### ISSUE THREAD

**Issue by dropdevrahul** [FERNman/angular-google-charts#76]
If we use the first version of arrayToDataTable as show in [google doc](https://google-developers.appspot.com/chart/interactive/docs/reference#arraytodatatable) it does not work.

**Comment by FERNman** [comment]
Could you provide me with some code if this issue is still valid? Where are you using `arrayToDataTable`?

**Comment by FrankL-git** [comment]
Here's an example for the data definition which should work (token from https://google-developers.appspot.com/chart/interactive/docs/reference#arraytodatatable):

app.component.html:

`<google-chart [type]="'ColumnChart'" [data]="myData"> </google-chart>`

app.component.ts:

`import { Component } from '@angular/core';`
`import {GoogleChartComponent} from 'angular-google-charts';`

`@Component({`
`    selector: 'app-root',`
`    templateUrl: './app.component.html',`
`    styleUrls: ['./app.component.css']`
`})`
`export class AppComponent {`

`    myData = [`
`//      [{label: 'Country', type: 'string'},`
`//       {label: 'Population', type: 'number'},`
`//       {label: 'Area', type: 'number'}],`
`      ['CN', 1324, 9640821],`
`      ['IN', 1133, 3287263],`
`      ['US', 304, 9629091],`
`      ['ID', 232, 1904569],`
`      ['BR', 187, 8514877]`
`    ];`
`}`

works. But if you uncomment the first row of myData you get the error:
"ERROR Error: "Unknown type of value in 0,0"
I'm using angular 8.

**Comment by FERNman** [comment]
You have to provide the columns (aka the first row of the data table) via the `columnNames` property of the `GoogleChartComponent`.

This is because `arrayToDataTable` needs to know if the first row in the provided data is already part of the chart or if it's the column names.
