### ISSUE TITLE
Is it possible to add style in Orgchart ?

### ISSUE THREAD

**Issue by soleanos** [FERNman/angular-google-charts#77]
Good morning,

I'm actually trying to custom the color of specific node in my orgChart but it apparently  doesnt work .. 

Here is my code : 

ts : 

 columnNames = ['NodeTitle', 'ParentNodeTitle'];
  data = [
           ['Copper', 'toto', '#b87333'],
           ['Silver', 'coucou', 'silver'],
           ['Gold', 'coucou', 'gold'],
           ['Platinum', 'lol', 'green ' ],
        ];
  chartOptions = {
    roles: [{
      index: 2,
      role: 'style'
    }]
  };

Html : 

<google-chart
[title]="'My Chart'"
[type]="'OrgChart'"
[data]="data"
[columnNames]="columnNames"
[options]="chartOptions"
[roles]="chartOptions.roles"
></google-chart>

It 's work with an barChart !! I also tried  to do in my component " myDataTable.setRowProperty(3, 'style', 'border: 1px solid green');" but not way too 

Would you have an idea ? I want to do that for coloring two node who are duplicate for exemple ( because we can't have two parents node in google orgchart .. )

Thank's you :)

**Comment by moazraza** [comment]
I'm stuck with the same problem. Did you figure out a way?

**Comment by soleanos** [comment]
nop :/

**Comment by moazraza** [comment]
@soleanos I did manage to figure out a solution. Follow the link: https://github.com/FERNman/angular-google-charts/issues/86
