### ISSUE TITLE
Capture event when user clicks on x axis on Google charts

### ISSUE THREAD

**Issue by mahesh-kedari** [FERNman/angular-google-charts#78]
I am working on a requirement where I need to change the format of x axis values when user clicks on them. Like absolute value <=> Percentage Value. Is there any way I can capture the event when user clicks anywhere on x axis and not other parts of chart?

I tried angular's (click) event however It is not giving me any information as which part of the chart is clicked.

**Comment by FERNman** [comment]
You should have a look at the events in the [original documentation](https://google-developers.appspot.com/chart/interactive/docs/reference#events). The select event is probably what you need, it's also described in the package documentation of this package.
