### ISSUE TITLE
dynamicResize does not work in Chrome or Safari.

### ISSUE THREAD

**Issue by niftyhawk** [FERNman/angular-google-charts#80]
It appears that the property "dynamicResize" for a "google-chart" component, does not work in Chrome or Safari. It works in IE11 and Firefox.

Here's a StackBlitz example, addressing the issue:

https://stackblitz.com/edit/angular-hx6pij

**Comment by FERNman** [comment]
Dynamic resize doesn't work in your example because the width and height input properties only accept numbers. Just leave these properties empty and set the width and/or height to percentage values in CSS.

Hope this helps!
