### ISSUE TITLE
Clarification : ControlWrapper - Need to know if we can add filters using ControlWrapper 

### ISSUE THREAD

**Issue by boopathy-m** [FERNman/angular-google-charts#81]
Is it possible to use ControlWrapper , can you help me with some samples 

 // Create a range slider, passing some options
        var donutRangeSlider = new google.visualization.ControlWrapper({
          'controlType': 'NumberRangeFilter',
          'containerId': 'filter_div',
          'options': {
            'filterColumnLabel': 'Donuts eaten'
          }
        });
.........
........
        dashboard.bind(donutRangeSlider, pieChart);

**Comment by FERNman** [comment]
Yes, this is definitely possible. I am planning on improving the support for ControlWrapper by providing a component or directive for it. For now, you should just query for the chart using ViewChild or ContentChild and then get the native chart element.

You can do this by using the `RawChartComponent.wrapper` property which is public. It provides access to the chart reference through `Wrapper.getChart()`.

Hope this helps!

**Comment by FERNman** [comment]
I will start implementing this for the 1.0 release. Please refer to #122 for further progress.
