### ISSUE TITLE
wrapper undefined - but I can see it in dev console??

### ISSUE THREAD

**Issue by jb44** [FERNman/angular-google-charts#82]
. . . 
  @ViewChild('timelinechart', { static: true }) timeline: GoogleChartComponent;

  . . .
  ngOnInit() {
    console.log(this.timeline);
    const wrapper = this.timeline.wrapper;
    console.log(wrapper);
  }

  The first log line dumps debug information which shows a "wrapper" element within it, but the second log line gives me "undefined"

**Comment by FERNman** [comment]
I can verify that this is true, and it doesn't make sense right now. The wrapper is undefined in the ngOnInit method if you access it directly, but it's visible in the parent object in the console.

It is, however, useable inside event listeners on charts. I'll try to find out if we can fix this. For now, you should be able to use the chart ready event and access the wrapper from there on.

**Comment by AlmaniaM** [comment]
@FERNman - I don't believe that this is necessarily a bug but rather a timing issue. The wrapper won't be defined until it's populated by the GoogleChartComponent.createChart() function. Given that createChart() is called after the loaderService.onReady observable emits a value AND GoogleChartComponent.ngOnInit() is called after any wrapping component such as the main.component in the demo, you will never be able to access the wrapper from main.component. The reason you don't see the wrapper in main.component but you see it in the console is simply a timing of accessing the object in the console. Take for example the code below:

**Comment by FERNman** [comment]
Thanks @AlmaniaM for your detailed explanation, I only saw your reply right now.

I wasn't aware of the order in which `ngOnInit` is called for parent and child components, but I'm happy that this is not a bug but rather the natural way of how Angular works.
