### ISSUE TITLE
Background color

### ISSUE THREAD

**Issue by diomededavid** [FERNman/angular-google-charts#84]
Thank you for creating this. Great work! I need some help. I have looked though the docs and googled around, but I am unable to change the background color in a bar chart. 

Here is a my options array 
`myOptions = {
  colors: ['#82d654', '#2b3445'],
  legend: {position: 'none'},
  backgroundColor: '#82d654',
};`

Thanks in advance.

**Comment by FERNman** [comment]
So I just tried it and for me, this works as expected. Maybe [this](https://stackoverflow.com/questions/8808100/google-chart-background-color) StackOverflow thread can help you.

**Comment by diomededavid** [comment]
Before asking I had found that post and it is where I got as far as what was posted in my previous post. Could you post the json that worked for you?
