### ISSUE TITLE
Can't add Data to Gantt - google is not define

### ISSUE THREAD

**Issue by jramirezcc** [FERNman/angular-google-charts#87]
Hello!

I was trying to implement , but when I try to implement the Gantt chart, its data type is from google.visualization.DataTable, and when I create the data, it shows the following error; "Cannot read property 'addColumn' of undefined"

![image](https://user-images.githubusercontent.com/52500740/62663034-a8efaf00-b93b-11e9-97a6-b30db882aa50.png)

And if it's not that, it shows me that "google is not defined"

![image](https://user-images.githubusercontent.com/52500740/62663124-01bf4780-b93c-11e9-9afd-da6c76bfe7fb.png)

This image is from google: https://developers.google.com/chart/interactive/docs/gallery/ganttchart

![image](https://user-images.githubusercontent.com/52500740/62662972-73e35c80-b93b-11e9-9657-99d082526a72.png)

This is from my site :

![image](https://user-images.githubusercontent.com/52500740/62663661-097feb80-b93e-11e9-8cc0-f162790eddc1.png)

How can I fix this?

**Comment by AlmaniaM** [comment]
@jramirezcc - Could you post some of your code that you are using and calling so people here can get a better idea of what you are doing?

**Comment by jramirezcc** [comment]
Sure:

> This is from my component

export class GanttComponent implements AfterViewInit {

    public charts: Array<{
        title: string;
        type: string;
        data: any;
        options: {};
    }> = [];

    constructor(private ganttService: GanttService) {
    }

    ngAfterViewInit() {
        this.charts = this.ganttService.getCharts();
    }
}

> And services

export class GanttService {

    public charts: Array<{
        title: string;
        type: string;
        data: any;
        options: {};
        width: number;
    }> = [];

    constructor() {
        this.buildCharts();
    }

    buildCharts() {
        const dataTable = new google.visualization.DataTable(); // Here crash
        dataTable.addColumn('string', 'Task ID');
        dataTable.addColumn('string', 'Task Name');
        dataTable.addColumn('date', 'Start Date');
        dataTable.addColumn('date', 'End Date');
        dataTable.addColumn('number', 'Duration');
        dataTable.addColumn('number', 'Percent Complete');
        dataTable.addColumn('string', 'Dependencies');

        dataTable.addRows([
            ['PMO', 'PMO',
                new Date(2015, 1, 1), new Date(2015, 1, 4), null, 100, null]
        ]);

        this.addChart({
            title: 'Gantt Chart',
            type: 'Gantt',
            data: dataTable,
            options: this.getChartOptions()
        });
    }

**Comment by AlmaniaM** [comment]
Hi @jramirezcc ,

If you don't have other libraries in your code that are initializing any google.visualization then I'll assume you can wait for the chart to do it like so.
In your GanttComponent and constructor do this:
```
import { ScriptLoaderService } from 'angular-google-charts';

private _destroyed = new Subject();

constructor(private ganttService: GanttService, private _loaderService: ScriptLoaderService) {
  this._loaderService.onReady.pipe(takeUntil(this._destroyed)).subscribe((ready: boolean) => {
    // You can't start building your charts until the ScriptLoader is ready. When it's ready then that
    // means it has loaded google into the DOM by creating a <script> tag that pulls the google
    // library down.
    this.ganttService.buildCharts();
  }  
}

// You would need to implement OnDestroy in your GanttComponent
ngOnDestroy(): void {
  this._destroyed.next();
}
```

Let us know if this works for you.

**Comment by jramirezcc** [comment]
It gives me this error, It still does not recognize DataTable, and yes I didn't initialize google.visualization in other part.


![image](https://user-images.githubusercontent.com/52500740/62801447-5fbe6d00-baab-11e9-9d41-f5cae6cc1671.png)

**Comment by AlmaniaM** [comment]
When your site loads are you able to type something like var dt = new google.visualization.DataTable(); in the browser console?

**Comment by jramirezcc** [comment]
Yes, I do it and throws me **undefine**

![image](https://user-images.githubusercontent.com/52500740/62807075-188ba880-baba-11e9-8621-b3881a69aa98.png)

**Comment by AlmaniaM** [comment]
That's not undefined you should be able to access `dt`. If you just do 
```
new google.visualization.DataTable();
```
it won't be undefined but that's besides the point. It looks like the visualization part is being loaded in so that's good. 

Looks like you'll need to use the (ready) output on the chart. It doesn't look like the `visualization` object is ready in the onReady observable of the ScriptLoader. You can do this and for sure the `visualization` object will be ready:
```
  <google-chart
    (ready)="onChartReady($event)">
  </google-chart>
```

In you GanttComponent do:
```
onChartReady(): void {
  this.ganttService.buildCharts();
}
```
That should work.

**Comment by jramirezcc** [comment]
Ok,

Well, I didn't works, but the process you do It's great, and I forgot to tell you, sorry, the visualization part is being loaded because I just add two external JS files

```
<script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
  <script type="text/javascript">
    google.charts.load('current', {'packages':['gantt']});
    google.charts.setOnLoadCallback(drawChart);
```

but It's not correctly to do it like this.

**Comment by AlmaniaM** [comment]
Are you adding those scripts yourself in the `index.html`?
I think the issue might be this section of code should be defined before calling `buildCharts();`.
```
 this.addChart({
        title: 'Gantt Chart',
        type: 'Gantt',
        data: dataTable,
        options: this.getChartOptions()
    });
```

Looks like that defines your chart options so it should be passed to GanttComponent or defined inside the GanttComponent so the chart knows what chart type of packages to load. So it should look like this if you define it inside the GanttComponent:

```
public charts: Array<{
    title: string;
    type: string;
    data: any;
    options: {};
    width: number;
}> = [{
        title: 'Gantt Chart',
        type: 'Gantt',
        data: dataTable,
        options: this.getChartOptions()
    }];
```

**Comment by jramirezcc** [comment]
I am adding those scripts on the angular.json

I did it like you indicates and doesn't works

I don't think that's the problem, cause when I using those external scripts works, look

![image](https://user-images.githubusercontent.com/52500740/62873602-56204980-bce5-11e9-8322-3745e5544c42.png)
