### ISSUE TITLE
chart created with pure google.charts.Line looks better than google.visualization.ChartWrapper

### ISSUE THREAD

**Issue by vitaliidasaev** [FERNman/angular-google-charts#88]
Example:
![image](https://user-images.githubusercontent.com/11960985/62760186-14489680-ba8c-11e9-8bf3-4a1e886d2197.png)

But there are some configurations still missed unfoutunately in material versions of chart:
https://github.com/google/google-visualization-issues/issues/2143 - unsupported options

**Comment by FERNman** [comment]
I will close this as this is not a real issue with this package I think.
