### ISSUE TITLE
Angular Application With Google Charts Getting Struck While Going To New Route

### ISSUE THREAD

**Issue by MorlaRamakrishna** [FERNman/angular-google-charts#89]
I have integrated google charts in my angular7 application. But If I go from charts page to new page via routing, application responding very late(Feeling application got struck for few seconds).

My angular application was JHipster application.

**Comment by FERNman** [comment]
I don't think this has anything to do with this package, except if you'd draw a very big amount of charts maybe. I will close this for now.
