### ISSUE TITLE
Is there a way to save the chart as an image?

### ISSUE THREAD

**Issue by peter-stuart-turner** [FERNman/angular-google-charts#9]
Trying to figure out a way to save the resulting chart as an image, sorry for opening this as an issue - not sure where else to ask?

**Comment by FERNman** [comment]
I'll look into it and provide a function to get an image from a chart. Will close this as soon as it's done.

**Comment by peter-stuart-turner** [comment]
You're unbelievably amazing

**Comment by peter-stuart-turner** [comment]
Its a table under the hood (unlike the usual google charts) so the chart object does not provide a getImageURI function - need to use html2canvas probably, trying that out now

**Comment by LazeBear** [comment]
you can have a look of [this](https://github.com/exupero/saveSvgAsPng)

**Comment by ianzimmerman** [comment]
Charts has a method for this: https://developers.google.com/chart/interactive/docs/printing
 Can we utilize this in any way?

**Comment by jtomek** [comment]
This would be great to have :)

**Comment by jtomek** [comment]
So I was looking into it a bit more and it's actually described on the homepage of this repository:

html:

`<google-chart #chart [data]="myData" etc. ></google-chart>`

component variable definition:

`@ViewChild('chart') chart: GoogleChartComponent;`

component function: 

```
const wrapper = this.chart.wrapper as any;

wrapper.visualization.getImageURI();

```

That's it.

**Comment by peter-stuart-turner** [comment]
Great! Havent looked in this thread in ages but then I assume @FERNman made the function but forgot to close the issue - will close it now
