### ISSUE TITLE
Error: "Can't create a Google Chart without data!" when data loaded inside an Angular Service

### ISSUE THREAD

**Issue by ranaalisaeed** [FERNman/angular-google-charts#93]
Hi guys,
I am really struggling to get this working.
When I get data from an Angular Service inside a component, I get console error that Google Chart can't be loaded without data. When I declare data outside of Service.subscribe the chart works fine. I think google charts is being called even before the service returns, so how can I make it wait for it?
Please take a look at code snippet below. Appreciate any help or pointers.

### app.module.ts
```javascript
import { GoogleChartsModule } from 'angular-google-charts';
...
  ],
  imports: [
...
		GoogleChartsModule
  ],
...
})
export class AppModule { }
```

### component.html
```html
<google-chart #chart
   [title]="title"
   [type]="type"
	 [data]="chartData"
   [options]="options"
   [width]="width"
   [height]="height">
</google-chart>
```

### component.ts
```javascript
import { Component, OnInit } from '@angular/core';
import { MilestoneService } from 'src/app/milestone.service';
import { Milestone } from 'src/app/milestone';

@Component({
	selector: 'app-timeline',
	templateUrl: './timeline.component.html',
	styleUrls: ['./timeline.component.css']
})
export class TimelineComponent implements OnInit {

	title: string
	type: string
	chartData: Array<Array<any>>
	options: {}
	width: number
	height: number

	constructor(
		private milestoneService: MilestoneService,
	) { }

	ngOnInit() {

		this.title = 'Some title'
		this.type = 'Timeline'
		this.width = 550
		this.height = 400
		this.options = {}

                // IF I UNCOMMENT THIS, IT WORKS!
		// this.chartData = [
		// 	['program 1', 'milestone 1', new Date('2019-10-10'), new Date('2019-11-11')],
		// 	['program 2', 'milestone 2', new Date('2019-11-14'), new Date('2019-12-10')],
		// ]

		this.milestoneService.getMilestonesTimeline().subscribe((data: Milestone[]) => {
			// WHY IS THIS NOT WORKING?
                        this.chartData = data.map(d => [d.program, d.title, new Date(d.start), new Date(d.end)])
		})
	}
}	

```

**Comment by FERNman** [comment]
I'm sorry for not answering earlier. This has to do with a design choice I made when writing this package: In `ngOnInit`, the chart component checks whether it has valid data. If you load the data asynchronously, it is probably undefined when the component gets initialized and that's why you see the error.

This can easily be fixed by using `ngIf` in HTML where you are creating the component, for example

```html
<google-chart *ngIf="data != null" [data]="data"></google-chart>
```

I will probably change this in the upcoming 1.0 release to allow undefined data.
