### ISSUE TITLE
Access restrictions to Google Charts

### ISSUE THREAD

**Issue by sajulio** [FERNman/angular-google-charts#94]
Hi,
day after day,...
and after some time of use, Google Charts stops from loading on my Angular project.
My Browser console shows like this:

> angular-google-charts.js:152 GET https://www.gstatic.com/charts/loader.js net::ERR_CERT_AUTHORITY_INVALID
> angular-google-charts.js:132 Failed to load the google chart script!
> core.js:4002 ERROR Failed to load the google chart script!

After this some of my Google services just stop working, namely Google maps 'till the day after.
I think this have something to do with access restrictions from the Google side but I'm not sure why it happens and more importantly how to solve this.
Any idea here please?

**Comment by sajulio** [comment]
I think I'm having problems with 'my-custom-maps-api-key ...

```
> @NgModule({
>   ...
>   imports: [
>     ...
>     GoogleChartsModule.forRoot('my-custom-maps-api-key'),
>     ...
>   ],
>   ...
> })
> export class AppModule {}
```

All I know is that after some time using Google Charts they just stop working
with the above error pasted on my 1st message

**Comment by FERNman** [comment]
You need to have a valid Google API key, 'my-custom-maps-api-key' was just a placeholder.
