### ISSUE TITLE
google bar chart haxis labels disappearing when navigating from one page to another

### ISSUE THREAD

**Issue by akshay-kale** [FERNman/angular-google-charts#95]
First time onload it working properly
![labels](https://user-images.githubusercontent.com/19792888/65879355-3f28da00-e3ad-11e9-8e99-c4537f8a3baa.PNG)

when clicking on List and again coming back to home the haxis labels are disappearing.
![image](https://user-images.githubusercontent.com/19792888/65879435-68e20100-e3ad-11e9-86f3-d3b4067e563c.png)

**Comment by FERNman** [comment]
I will close this for now as I think this is more of a problem with Google Charts than with this package. If it is still valid, feel free to comment here, but please provide a bit more background (source code etc.).
