### ISSUE TITLE
How to access getImageURI() 

### ISSUE THREAD

**Issue by subbareddy425** [FERNman/angular-google-charts#96]

**Comment by FERNman** [comment]
You have to access it through the chart wrapper object. Example:

```html
<google-chart #chart (ready)="chartReady(chart)"></google-chart>
```

```typescript
public chartReady(chart: GoogleChartComponent) {
   chart.wrapper.getChart().getImageURI();
}
```

**Comment by subbareddy425** [comment]
Excellent! Thank you Very much!!

**Comment by LennyZ71** [comment]
This seems to be broken now.  ".wrapper" does not exist on GoogleChartComponent, and getImageURI() is not available from chart.chartWrapper.getChart() either.

Any other options to getting a graph as an image to print?

**Comment by KasperSchodts** [comment]
Does this still work? I get an Exception telling me that chart.wrapper is private. I've tried the following:
`chart.chartWrapper.getChart();`
but I get an exception saying that "Property 'getImageURI' does not exist on type 'ChartBase'"
