### ISSUE TITLE
ViewChild not working - error: chart is undefined

### ISSUE THREAD

**Issue by ranaalisaeed** [FERNman/angular-google-charts#97]
Hi,
I can't get this example to work, and keep getting error "chart is undefined", is there a working example I can refer to? The documentation available with this library is very limited. 

`<google-chart #chart></google-chart>`

```
import { ViewChild } from '@angular/core';
import { GoogleChartComponent } from 'angular-google-charts';

@Component({
  ...
})
export class AppComponent implements OnInit {
  @ViewChild('chart')
  chart: GoogleChartComponent;

  ngOnInit() {
    const wrapper = this.chart.wrapper;

    wrapper.draw(myAdvancedData);
  }
}
```

**Comment by FERNman** [comment]
Oh I'm sorry, that's actually an error in the documentation. It should be `ngAfterViewInit()` instead of `ngOnInit()`. 

This has to do with how angular handles the `@ViewChild` decorator. If you could try the same example, but using `ngAfterViewInit` and tell me if it works, I'd change the documentation accordingly.

**Comment by ranaalisaeed** [comment]
I still get the same error, here is my updated code of component.ts:

Any other thoughts?

```
import { GoogleChartComponent } from 'angular-google-charts'

@Component({
...
})
export class TimelineComponent implements OnInit {

	@ViewChild('chart', {static: true}) 
	chart: GoogleChartComponent
	
	ngAfterViewInit() {
		const wrapper = this.chart.wrapper
		console.log(wrapper)
	}
```

**Comment by ranaalisaeed** [comment]
Hi @FERNman , hope you're well. Keen to understand if there's anything else I could try or if I'm doing anything wrong?

**Comment by FERNman** [comment]
I'm sorry for taking so long to reply, I just didn't find the time to look into this for the last month. 
I hope you already found the solution for the problem already, I'll just write down what caused the issue here.

The documentation is not correct, the wrapper is not necessarily defined as soon as the chart is defined. The following method would work:

```html
<google-chart #chart (ready)="chartReady(chart)"></google-chart>
```

```typescript
import { GoogleChartComponent } from 'angular-google-charts';

@Component({
  ...
})
export class AppComponent {
  private myAdvancedData: any; // Initialized somewhere else

  public chartReady(chart: GoogleChartComponent) {
    const wrapper = chart.wrapper;

    wrapper.draw(myAdvancedData);
  }
}
```

I will update the documentation accordingly.

**Comment by rgupta6** [comment]
Hi @FERNman : I am facing the same issue and tried the solution you provided. My actual use case is to download the graph as static png image and for the same I need image URI for the graph.

Could you please help me here how can I get the image from the google-chart.

Note: I am using angular 8

**Comment by kaiwendt92** [comment]
> I'm sorry for taking so long to reply, I just didn't find the time to look into this for the last month.
> I hope you already found the solution in the meantime, I'll just write down what caused the issue for anyone else having the same problem.
> 
> The documentation is not correct, the wrapper is not necessarily defined as soon as the chart is defined. The following method would work:
> 
> ```
> <google-chart #chart (ready)="chartReady(chart)"></google-chart>
> ```
> 
> ```ts
> import { GoogleChartComponent } from 'angular-google-charts';
> 
> @Component({
>   ...
> })
> export class AppComponent {
>   private myAdvancedData: any; // Initialized somewhere else
> 
>   public chartReady(chart: GoogleChartComponent) {
>     const wrapper = chart.wrapper;
> 
>     wrapper.draw(myAdvancedData);
>   }
> }
> ```
> 
> I will update the documentation accordingly.

How can you pass myAdvancedData into the draw() method, when it is expecting an HTMLElement?
