### ISSUE TITLE
Background Color 'Bar' Material Chart not working

### ISSUE THREAD

**Issue by bazookon** [FERNman/angular-google-charts#98]
backgroundColor or any other color change not working, this is my options object

```typescript
chartOptions = {
  backgroundColor:"#333"
}
```

pure javascript working

https://jsfiddle.net/s1nyfdw2/

**Comment by bazookon** [comment]
Edit this works on Material

```
options: {
        chart: {
          style:{
            background:{
              fillColor:'#333'
            }
          },
   }
}
```

**Comment by FERNman** [comment]
So can this be closed? This is just how Google wants you to style material charts, those don't accept the same options as 'normal' charts.
